import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addMom1681676379564 implements MigrationInterface {
    shortName = 'MOM';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Invasion of Ravnica // Guildpact Paragon',
                rarity: 'M',
                layout: 'battleform',
                types: 'Battle',
                colors: '',
            },
            {
                cardNumber: 2,
                name: 'Aerial Boost',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 3,
                name: 'Alabaster Host Intercessor',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'Alabaster Host Sanctifier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'Angelic Intervention',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Archangel Elspeth',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Attentive Skywarden',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Bola Slinger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Boon-Bringer Valkyrie',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Cut Short',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Dusk Legion Duelist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Elesh Norn // The Argent Etchings',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: "Elspeth\\'s Smite",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Enduring Bondwarden',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Golden-Scale Aeronaut',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Guardian of Ghirapur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Heliod, the Radiant Dawn // Heliod, the Warped Eclipse',
                rarity: 'R',
                layout: 'transform',
                types: 'Enchantment,Creature',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Infected Defector',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: 'Inspired Charge',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Invasion of Belenon // Belenon War Anthem',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: 'Invasion of Dominaria // Serra Faithkeeper',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Invasion of Gobakhan // Lightshield Array',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'Invasion of Theros // Ephara, Ever-Sheltering',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'Kithkin Billyrider',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Knight of the New Coalition',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Knight-Errant of Eos',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: 'Kor Halberd',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Monastery Mentor',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: "Norn\\'s Inquisitor",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Phyrexian Awakening',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Phyrexian Censor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Progenitor Exarch',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: "Realmbreaker\\'s Grasp",
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: 'Scrollshift',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: 'Seal from Existence',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: 'Seraph of New Capenna // Seraph of New Phyrexia',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Sigiled Sentinel',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Sun-Blessed Guardian // Furnace-Blessed Conqueror',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 39,
                name: 'Sunder the Gateway',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 40,
                name: 'Sunfall',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 41,
                name: 'Surge of Salvation',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 42,
                name: 'Swordsworn Cavalier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 43,
                name: 'Tarkir Duneshaper // Burnished Dunestomper',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 44,
                name: 'Tiller of Flesh',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 45,
                name: 'Zhalfirin Lancer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 46,
                name: 'Artistic Refusal',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Assimilate Essence',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Astral Wingspan',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Captive Weird // Compleated Conjurer',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Change the Equation',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: 'Chrome Host Seedshark',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: 'Complete the Circuit',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Corruption of Towashi',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Disturbing Conversion',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: "Ephara\\'s Dispersal",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'Expedition Lookout',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Eyes of Gitaxias',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: 'Faerie Mastermind',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Furtive Analyst',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Halo-Charged Skaab',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: 'Invasion of Arcavios // Invocation of the Founders',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Invasion of Kamigawa // Rooftop Saboteurs',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: 'Invasion of Segovia // Caetus, Sea Tyrant of Segovia',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'Invasion of Vryn // Overloaded Mage-Ring',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: 'Jin-Gitaxias // The Great Synthesis',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: 'Meeting of Minds',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Moment of Truth',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: 'Negate',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Oculus Whelp',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Omen Hawker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: 'Oracle of Tragedy',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'Order of the Mirror // Order of the Alabaster Host',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 73,
                name: 'Preening Champion',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Protocol Knight',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: 'Rona, Herald of Invasion // Rona, Tolarian Obliterator',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Saiba Cryptomancer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'See Double',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Skyclave Aerialist // Skyclave Invader',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 79,
                name: 'Stasis Field',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 80,
                name: 'Temporal Cleansing',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 81,
                name: 'Thunderhead Squadron',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 82,
                name: 'Tidal Terror',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 83,
                name: 'Transcendent Message',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 84,
                name: 'Wicked Slumber',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 85,
                name: 'Xerex Strobe-Knight',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 86,
                name: 'Zephyr Singer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 87,
                name: 'Zhalfirin Shapecraft',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 88,
                name: 'Aetherblade Agent // Gitaxian Mindstinger',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 89,
                name: 'Archpriest of Shadows',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 90,
                name: 'Ayara, Widow of the Realm // Ayara, Furnace Queen',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: 'Bladed Battle-Fan',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: 'Blightreaper Thallid // Blightsower Thallid',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Bloated Processor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'Breach the Multiverse',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Collective Nightmare',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Compleated Huntmaster',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: 'Consuming Aetherborn',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'Corrupted Conviction',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Deadly Derision',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Dreg Recycler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Etched Familiar',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Etched Host Doombringer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Failed Conversion',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: 'Final Flourish',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Flitting Guerrilla',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'Gift of Compleation',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 107,
                name: 'Glistening Deluge',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 108,
                name: 'Gloomfang Mauler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 109,
                name: 'Grafted Butcher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 110,
                name: 'Hoarding Broodlord',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 111,
                name: 'Ichor Drinker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 112,
                name: 'Ichor Shade',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 113,
                name: 'Invasion of Eldraine // Prickle Faeries',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B',
            },
            {
                cardNumber: 114,
                name: 'Invasion of Fiora // Marchesa, Resolute Monarch',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B',
            },
            {
                cardNumber: 115,
                name: 'Invasion of Innistrad // Deluge of the Dead',
                rarity: 'M',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B',
            },
            {
                cardNumber: 116,
                name: 'Invasion of Ulgrotha // Grandmother Ravi Sengir',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B',
            },
            {
                cardNumber: 117,
                name: 'Merciless Repurposing',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 118,
                name: 'Mirrodin Avenged',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 119,
                name: 'Nezumi Freewheeler // Hideous Fleshwheeler',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 120,
                name: 'Nezumi Informant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 121,
                name: 'Phyrexian Gargantua',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 122,
                name: 'Pile On',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 123,
                name: 'Render Inert',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 124,
                name: 'Scorn-Blade Berserker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 125,
                name: 'Sheoldred // The True Scriptures',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 126,
                name: 'Tenured Oilcaster',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 127,
                name: 'Traumatic Revelation',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 128,
                name: 'Unseal the Necropolis',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 129,
                name: 'Vanquish the Weak',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 130,
                name: 'Akki Scrapchomper',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 131,
                name: 'Beamtown Beatstick',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 132,
                name: 'Bloodfeather Phoenix',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 133,
                name: "Burning Sun\\'s Fury",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 134,
                name: "Chandra, Hope\\'s Beacon",
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R',
            },
            {
                cardNumber: 135,
                name: 'City on Fire',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 136,
                name: 'Coming In Hot',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 137,
                name: 'Etali, Primal Conqueror // Etali, Primal Sickness',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 138,
                name: 'Fearless Skald',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 139,
                name: 'Furnace Gremlin',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 140,
                name: 'Furnace Host Charger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 141,
                name: 'Furnace Reins',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 142,
                name: 'Hangar Scrounger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 143,
                name: 'Harried Artisan // Phyrexian Skyflayer',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 144,
                name: 'Into the Fire',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 145,
                name: 'Invasion of Kaldheim // Pyre of the World Tree',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'R',
            },
            {
                cardNumber: 146,
                name: 'Invasion of Karsus // Refraction Elemental',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'R',
            },
            {
                cardNumber: 147,
                name: 'Invasion of Mercadia // Kyren Flamewright',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'R',
            },
            {
                cardNumber: 148,
                name: 'Invasion of Regatha // Disciples of the Inferno',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'R',
            },
            {
                cardNumber: 149,
                name: 'Invasion of Tarkir // Defiant Thundermaw',
                rarity: 'M',
                layout: 'battleform',
                types: 'Battle',
                colors: 'R',
            },
            {
                cardNumber: 150,
                name: 'Karsus Depthguard',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: 'Khenra Spellspear // Gitaxian Spellstalker',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Lithomantic Barrage',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: 'Marauding Dreadship',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: 'Mirran Banesplitter',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: "Nahiri\\'s Warcrafting",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Onakke Javelineer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 157,
                name: 'Pyretic Prankster // Glistening Goremonger',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 158,
                name: "Ral\\'s Reinforcements",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 159,
                name: 'Ramosian Greatsword',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 160,
                name: 'Rampaging Raptor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 161,
                name: 'Redcap Heelslasher',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 162,
                name: 'Scrappy Bruiser',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 163,
                name: 'Searing Barb',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 164,
                name: 'Shatter the Source',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 165,
                name: 'Shivan Branch-Burner',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 166,
                name: 'Stoke the Flames',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 167,
                name: 'Thrashing Frontliner',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 168,
                name: 'Trailblazing Historian',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 169,
                name: 'Urabrask // The Great Work',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 170,
                name: 'Volcanic Spite',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 171,
                name: 'Voldaren Thrillseeker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 172,
                name: 'War-Trained Slasher',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 173,
                name: "Wrenn\\'s Resolve",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 174,
                name: 'Ancient Imperiosaur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 175,
                name: 'Arachnoid Adaptation',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 176,
                name: "Atraxa\\'s Fall",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 177,
                name: 'Blighted Burgeoning',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 178,
                name: 'Bonded Herdbeast // Plated Kilnbeast',
                rarity: 'C',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 179,
                name: 'Chomping Kavu',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 180,
                name: 'Converter Beast',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 181,
                name: 'Copper Host Crusher',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 182,
                name: 'Cosmic Hunger',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 183,
                name: 'Crystal Carapace',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 184,
                name: 'Deeproot Wayfinder',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 185,
                name: 'Doomskar Warrior',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: "Fertilid\\'s Favor",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Glistening Dawn',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Gnottvold Hermit // Chrome Host Hulk',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Herbology Instructor // Malady Invoker',
                rarity: 'U',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: 'Invasion of Ikoria // Zilortha, Apex of Ikoria',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Invasion of Ixalan // Belligerent Regisaur',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'G',
            },
            {
                cardNumber: 192,
                name: 'Invasion of Muraganda // Primordial Plasm',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'G',
            },
            {
                cardNumber: 193,
                name: 'Invasion of Shandalar // Leyline Surge',
                rarity: 'M',
                layout: 'battleform',
                types: 'Battle',
                colors: 'G',
            },
            {
                cardNumber: 194,
                name: 'Invasion of Zendikar // Awakened Skyclave',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'G',
            },
            {
                cardNumber: 195,
                name: 'Iridescent Blademaster',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 196,
                name: 'Kami of Whispered Hopes',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 197,
                name: 'Overgrown Pest',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 198,
                name: 'Ozolith, the Shattered Spire',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 199,
                name: 'Placid Rottentail',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 200,
                name: 'Polukranos Reborn // Polukranos, Engine of Ruin',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 201,
                name: 'Portent Tracker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 202,
                name: 'Ravenous Sailback',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 203,
                name: 'Sandstalker Moloch',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 204,
                name: 'Seed of Hope',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 205,
                name: 'Serpent-Blade Assailant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 206,
                name: 'Storm the Seedcore',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 207,
                name: 'Streetwise Negotiator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 208,
                name: 'Tandem Takedown',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 209,
                name: 'Tangled Skyline',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 210,
                name: 'Timberland Ancient',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 211,
                name: 'Tribute to the World Tree',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 212,
                name: 'Vengeant Earth',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 213,
                name: 'Vorinclex // The Grand Evolution',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 214,
                name: 'War Historian',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 215,
                name: 'Wary Thespian',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 216,
                name: 'Wildwood Escort',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 217,
                name: 'Wrenn and Realmbreaker',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'G',
            },
            {
                cardNumber: 218,
                name: 'Baral and Kari Zev',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 219,
                name: 'Borborygmos and Fblthp',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,U',
            },
            {
                cardNumber: 220,
                name: 'Botanical Brawler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 221,
                name: 'Djeru and Hazoret',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 222,
                name: 'Drana and Linvala',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 223,
                name: 'Elvish Vatkeeper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 224,
                name: 'Errant and Giada',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 225,
                name: 'Ghalta and Mavren',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 226,
                name: 'Glissa, Herald of Predation',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 227,
                name: 'Halo Forager',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 228,
                name: 'Hidetsugu and Kairi',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 229,
                name: 'Inga and Esika',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 230,
                name: 'Invasion of Alara // Awaken the Maelstrom',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 231,
                name: 'Invasion of Amonkhet // Lazotep Convert',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B,U',
            },
            {
                cardNumber: 232,
                name: 'Invasion of Azgol // Ashen Reaper',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B,R',
            },
            {
                cardNumber: 233,
                name: 'Invasion of Ergamon // Truga Cliffcharger',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'G,R',
            },
            {
                cardNumber: 234,
                name: 'Invasion of Kaladesh // Aetherwing, Golden-Scale Flagship',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'R,U',
            },
            {
                cardNumber: 235,
                name: "Invasion of Kylem // Valor\\'s Reach Tag Team",
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'R,W',
            },
            {
                cardNumber: 236,
                name: 'Invasion of Lorwyn // Winnowing Forces',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B,G',
            },
            {
                cardNumber: 237,
                name: 'Invasion of Moag // Bloomwielder Dryads',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'G,W',
            },
            {
                cardNumber: 238,
                name: 'Invasion of New Capenna // Holy Frazzle-Cannon',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B,W',
            },
            {
                cardNumber: 239,
                name: 'Invasion of New Phyrexia // Teferi Akosa of Zhalfir',
                rarity: 'M',
                layout: 'battleform',
                types: 'Battle',
                colors: 'U,W',
            },
            {
                cardNumber: 240,
                name: 'Invasion of Pyrulea // Gargantuan Slabhorn',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'G,U',
            },
            {
                cardNumber: 241,
                name: 'Invasion of Tolvada // The Broken Sky',
                rarity: 'R',
                layout: 'battleform',
                types: 'Battle',
                colors: 'B,W',
            },
            {
                cardNumber: 242,
                name: 'Invasion of Xerex // Vertex Paladin',
                rarity: 'U',
                layout: 'battleform',
                types: 'Battle',
                colors: 'U,W',
            },
            {
                cardNumber: 243,
                name: 'Joyful Stormsculptor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 244,
                name: 'Kogla and Yidaro',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 245,
                name: 'Kroxa and Kunoros',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R,W',
            },
            {
                cardNumber: 246,
                name: 'Marshal of Zhalfir',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 247,
                name: 'Mirror-Shield Hoplite',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 248,
                name: 'Mutagen Connoisseur',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 249,
                name: 'Omnath, Locus of All',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 250,
                name: 'Quintorius, Loremaster',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 251,
                name: 'Rampaging Geoderm',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 252,
                name: 'Rankle and Torbran',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 253,
                name: 'Sculpted Perfection',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B,W',
            },
            {
                cardNumber: 254,
                name: 'Stormclaw Rager',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 255,
                name: 'Thalia and The Gitrog Monster',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,W',
            },
            {
                cardNumber: 256,
                name: 'Yargle and Multani',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 257,
                name: 'Zimone and Dina',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U',
            },
            {
                cardNumber: 258,
                name: 'Zurgo and Ojutai',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U,W',
            },
            {
                cardNumber: 259,
                name: 'Flywheel Racer',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Halo Hopper',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'Kitesail',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'Phyrexian Archivist',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 263,
                name: 'Realmbreaker, the Invasion Tree',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 264,
                name: 'Skittering Surveyor',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Sword of Once and Future',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 266,
                name: 'Urn of Godfire',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Bloodfell Caves',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Blossoming Sands',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Dismal Backwater',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Jungle Hollow',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Rugged Highlands',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Scoured Barrens',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Swiftwater Cliffs',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'Thornwood Falls',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Tranquil Cove',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Wind-Scarred Crag',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 279,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 280,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 281,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 283,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 284,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 285,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 286,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 287,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 288,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 289,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 290,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 291,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 292,
                name: 'Elesh Norn // The Argent Etchings',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 293,
                name: 'Heliod, the Radiant Dawn // Heliod, the Warped Eclipse',
                rarity: 'R',
                layout: 'transform',
                types: 'Enchantment,Creature',
                colors: 'W',
            },
            {
                cardNumber: 294,
                name: 'Jin-Gitaxias // The Great Synthesis',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 295,
                name: 'Rona, Herald of Invasion // Rona, Tolarian Obliterator',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 296,
                name: 'Ayara, Widow of the Realm // Ayara, Furnace Queen',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 297,
                name: 'Sheoldred // The True Scriptures',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 298,
                name: 'Etali, Primal Conqueror // Etali, Primal Sickness',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 299,
                name: 'Urabrask // The Great Work',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 300,
                name: 'Polukranos Reborn // Polukranos, Engine of Ruin',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 301,
                name: 'Vorinclex // The Grand Evolution',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 302,
                name: 'Baral and Kari Zev',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 303,
                name: 'Borborygmos and Fblthp',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,U',
            },
            {
                cardNumber: 304,
                name: 'Djeru and Hazoret',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 305,
                name: 'Drana and Linvala',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 306,
                name: 'Errant and Giada',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 307,
                name: 'Ghalta and Mavren',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 308,
                name: 'Glissa, Herald of Predation',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 309,
                name: 'Hidetsugu and Kairi',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 310,
                name: 'Inga and Esika',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 311,
                name: 'Kogla and Yidaro',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 312,
                name: 'Kroxa and Kunoros',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R,W',
            },
            {
                cardNumber: 313,
                name: 'Omnath, Locus of All',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 314,
                name: 'Quintorius, Loremaster',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 315,
                name: 'Rankle and Torbran',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 316,
                name: 'Thalia and The Gitrog Monster',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,W',
            },
            {
                cardNumber: 317,
                name: 'Yargle and Multani',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 318,
                name: 'Zimone and Dina',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U',
            },
            {
                cardNumber: 319,
                name: 'Zurgo and Ojutai',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U,W',
            },
            {
                cardNumber: 320,
                name: 'Archangel Elspeth',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'W',
            },
            {
                cardNumber: 321,
                name: "Chandra, Hope\\'s Beacon",
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R',
            },
            {
                cardNumber: 322,
                name: 'Wrenn and Realmbreaker',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'G',
            },
            {
                cardNumber: 323,
                name: 'Essence of Orthodoxy',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 324,
                name: 'Phyrexian Pegasus',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 325,
                name: 'Seedpod Caretaker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 326,
                name: 'Interdisciplinary Mascot',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 327,
                name: 'Referee Squad',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 328,
                name: 'Zephyr Winder',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 329,
                name: 'Injector Crocodile',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 330,
                name: 'Seer of Stolen Sight',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 331,
                name: 'Terror of Towashi',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 332,
                name: 'Axgard Artisan',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 333,
                name: 'Cragsmasher Yeti',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 334,
                name: 'Orthion, Hero of Lavabrink',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 335,
                name: 'Fairgrounds Trumpeter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 336,
                name: 'Ruins Recluse',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 337,
                name: 'Surrak and Goreclaw',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 338,
                name: 'Elesh Norn // The Argent Etchings',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 339,
                name: 'Jin-Gitaxias // The Great Synthesis',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 340,
                name: 'Sheoldred // The True Scriptures',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 341,
                name: 'Urabrask // The Great Work',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 342,
                name: 'Vorinclex // The Grand Evolution',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 343,
                name: 'Boon-Bringer Valkyrie',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 344,
                name: 'Dusk Legion Duelist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 345,
                name: 'Guardian of Ghirapur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 346,
                name: 'Knight-Errant of Eos',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 347,
                name: 'Monastery Mentor',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 348,
                name: 'Progenitor Exarch',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 349,
                name: 'Sunfall',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 350,
                name: 'Chrome Host Seedshark',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 351,
                name: 'Complete the Circuit',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 352,
                name: 'Faerie Mastermind',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 353,
                name: 'See Double',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 354,
                name: 'Transcendent Message',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 355,
                name: 'Zephyr Singer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 356,
                name: 'Archpriest of Shadows',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 357,
                name: 'Bloated Processor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 358,
                name: 'Breach the Multiverse',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 359,
                name: 'Grafted Butcher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 360,
                name: 'Hoarding Broodlord',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 361,
                name: 'Pile On',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 362,
                name: 'Bloodfeather Phoenix',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 363,
                name: 'City on Fire',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 364,
                name: 'Into the Fire',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 365,
                name: "Nahiri\\'s Warcrafting",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 366,
                name: 'Rampaging Raptor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 367,
                name: 'Voldaren Thrillseeker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 368,
                name: 'Ancient Imperiosaur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 369,
                name: 'Deeproot Wayfinder',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 370,
                name: 'Doomskar Warrior',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 371,
                name: 'Glistening Dawn',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 372,
                name: 'Ozolith, the Shattered Spire',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 373,
                name: 'Tribute to the World Tree',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 374,
                name: 'Realmbreaker, the Invasion Tree',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 375,
                name: 'Sword of Once and Future',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 376,
                name: 'Essence of Orthodoxy',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 377,
                name: 'Interdisciplinary Mascot',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 378,
                name: 'Terror of Towashi',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 379,
                name: 'Orthion, Hero of Lavabrink',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 380,
                name: 'Surrak and Goreclaw',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 381,
                name: "Norn\\'s Inquisitor",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 382,
                name: 'Scrappy Bruiser',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 383,
                name: 'Kami of Whispered Hopes',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 384,
                name: 'Botanical Brawler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 385,
                name: 'Halo Forager',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 386,
                name: 'Ghalta and Mavren',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 387,
                name: 'Omnath, Locus of All',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,R,U,W',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'March of the Machine',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
