import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addMul1681802964787 implements MigrationInterface {
    shortName = 'MUL';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Anafenza, Kin-Tree Spirit',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 2,
                name: 'Daxos, Blessed by the Sun',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment,Creature',
                colors: 'W',
            },
            {
                cardNumber: 3,
                name: 'Elesh Norn, Grand Cenobite',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'Kenrith, the Returned King',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'Kwende, Pride of Femeref',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Sram, Senior Edificer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Thalia, Guardian of Thraben',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Baral, Chief of Compliance',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 9,
                name: 'Emry, Lurker of the Loch',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 10,
                name: 'Inga Rune-Eyes',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 11,
                name: 'Jin-Gitaxias, Core Augur',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 12,
                name: 'Tetsuko Umezawa, Fugitive',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 13,
                name: 'Ayara, First of Locthwain',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 14,
                name: "Horobi, Death's Wail",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 15,
                name: 'Seizan, Perverter of Truth',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 16,
                name: 'Sheoldred, Whispering One',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 17,
                name: 'Skithiryx, the Blight Dragon',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 18,
                name: 'Tymaret, Chosen from Death',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment,Creature',
                colors: 'B',
            },
            {
                cardNumber: 19,
                name: 'Yargle, Glutton of Urborg',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 20,
                name: 'Captain Lannery Storm',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 21,
                name: 'Ragavan, Nimble Pilferer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 22,
                name: 'Squee, the Immortal',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 23,
                name: 'Urabrask the Hidden',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 24,
                name: 'Valduk, Keeper of the Flame',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 25,
                name: 'Zada, Hedron Grinder',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 26,
                name: 'Fynn, the Fangbearer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 27,
                name: 'Goreclaw, Terror of Qal Sisma',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 28,
                name: 'Renata, Called to the Hunt',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment,Creature',
                colors: 'G',
            },
            {
                cardNumber: 29,
                name: 'Vorinclex, Voice of Hunger',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 30,
                name: 'Yedora, Grave Gardener',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 31,
                name: 'Aegar, the Freezing Flame',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 32,
                name: 'Arixmethes, Slumbering Isle',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 33,
                name: "Atraxa, Praetors' Voice",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U,W',
            },
            {
                cardNumber: 34,
                name: 'Atris, Oracle of Half-Truths',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 35,
                name: 'Aurelia, the Warleader',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 36,
                name: 'Brudiclad, Telchor Engineer',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 37,
                name: 'Dina, Soul Steeper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 38,
                name: 'Ezuri, Claw of Progress',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 39,
                name: 'Firesong and Sunspeaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 40,
                name: 'Firja, Judge of Valor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 41,
                name: 'Grimgrin, Corpse-Born',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 42,
                name: 'Gyruda, Doom of Depths',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 43,
                name: 'Imoti, Celebrant of Bounty',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 44,
                name: 'Jegantha, the Wellspring',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 45,
                name: 'Judith, the Scourge Diva',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 46,
                name: 'Juri, Master of the Revue',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 47,
                name: 'Kaheera, the Orphanguard',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 48,
                name: 'Keruga, the Macrosage',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 49,
                name: "Kroxa, Titan of Death's Hunger",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 50,
                name: 'Lathiel, the Bounteous Dawn',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 51,
                name: 'Lurrus of the Dream-Den',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 52,
                name: 'Lutri, the Spellchaser',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 53,
                name: 'Niv-Mizzet Reborn',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 54,
                name: 'Obosh, the Preypiercer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 55,
                name: 'Radha, Coalition Warlord',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 56,
                name: 'Raff, Weatherlight Stalwart',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 57,
                name: 'Reyav, Master Smith',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 58,
                name: "Rona, Sheoldred's Faithful",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 59,
                name: "Shanna, Sisay's Legacy",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 60,
                name: 'Taigam, Ojutai Master',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 61,
                name: 'Teysa Karlov',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 62,
                name: 'Umori, the Collector',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 63,
                name: 'Yarok, the Desecrated',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U',
            },
            {
                cardNumber: 64,
                name: 'Yorion, Sky Nomad',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 65,
                name: 'Zirda, the Dawnwaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 66,
                name: 'Anafenza, Kin-Tree Spirit',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 67,
                name: 'Daxos, Blessed by the Sun',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment,Creature',
                colors: 'W',
            },
            {
                cardNumber: 68,
                name: 'Elesh Norn, Grand Cenobite',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 69,
                name: 'Kenrith, the Returned King',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 70,
                name: 'Kwende, Pride of Femeref',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 71,
                name: 'Sram, Senior Edificer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 72,
                name: 'Thalia, Guardian of Thraben',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 73,
                name: 'Baral, Chief of Compliance',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Emry, Lurker of the Loch',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: 'Inga Rune-Eyes',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Jin-Gitaxias, Core Augur',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'Tetsuko Umezawa, Fugitive',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Ayara, First of Locthwain',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 79,
                name: "Horobi, Death's Wail",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 80,
                name: 'Seizan, Perverter of Truth',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 81,
                name: 'Sheoldred, Whispering One',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 82,
                name: 'Skithiryx, the Blight Dragon',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 83,
                name: 'Tymaret, Chosen from Death',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment,Creature',
                colors: 'B',
            },
            {
                cardNumber: 84,
                name: 'Yargle, Glutton of Urborg',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 85,
                name: 'Captain Lannery Storm',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 86,
                name: 'Ragavan, Nimble Pilferer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 87,
                name: 'Squee, the Immortal',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 88,
                name: 'Urabrask the Hidden',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 89,
                name: 'Valduk, Keeper of the Flame',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 90,
                name: 'Zada, Hedron Grinder',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 91,
                name: 'Fynn, the Fangbearer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 92,
                name: 'Goreclaw, Terror of Qal Sisma',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 93,
                name: 'Renata, Called to the Hunt',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment,Creature',
                colors: 'G',
            },
            {
                cardNumber: 94,
                name: 'Vorinclex, Voice of Hunger',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 95,
                name: 'Yedora, Grave Gardener',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 96,
                name: 'Aegar, the Freezing Flame',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 97,
                name: 'Arixmethes, Slumbering Isle',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 98,
                name: "Atraxa, Praetors' Voice",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U,W',
            },
            {
                cardNumber: 99,
                name: 'Atris, Oracle of Half-Truths',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 100,
                name: 'Aurelia, the Warleader',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 101,
                name: 'Brudiclad, Telchor Engineer',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 102,
                name: 'Dina, Soul Steeper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 103,
                name: 'Ezuri, Claw of Progress',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 104,
                name: 'Firesong and Sunspeaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 105,
                name: 'Firja, Judge of Valor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 106,
                name: 'Grimgrin, Corpse-Born',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 107,
                name: 'Gyruda, Doom of Depths',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 108,
                name: 'Imoti, Celebrant of Bounty',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 109,
                name: 'Jegantha, the Wellspring',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 110,
                name: 'Judith, the Scourge Diva',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 111,
                name: 'Juri, Master of the Revue',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 112,
                name: 'Kaheera, the Orphanguard',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 113,
                name: 'Keruga, the Macrosage',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 114,
                name: "Kroxa, Titan of Death's Hunger",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 115,
                name: 'Lathiel, the Bounteous Dawn',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 116,
                name: 'Lurrus of the Dream-Den',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 117,
                name: 'Lutri, the Spellchaser',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 118,
                name: 'Niv-Mizzet Reborn',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 119,
                name: 'Obosh, the Preypiercer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 120,
                name: 'Radha, Coalition Warlord',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 121,
                name: 'Raff, Weatherlight Stalwart',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 122,
                name: 'Reyav, Master Smith',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 123,
                name: "Rona, Sheoldred's Faithful",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 124,
                name: "Shanna, Sisay's Legacy",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 125,
                name: 'Taigam, Ojutai Master',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 126,
                name: 'Teysa Karlov',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 127,
                name: 'Umori, the Collector',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 128,
                name: 'Yarok, the Desecrated',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U',
            },
            {
                cardNumber: 129,
                name: 'Yorion, Sky Nomad',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 130,
                name: 'Zirda, the Dawnwaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 131,
                name: 'Anafenza, Kin-Tree Spirit',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 132,
                name: 'Daxos, Blessed by the Sun',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment,Creature',
                colors: 'W',
            },
            {
                cardNumber: 133,
                name: 'Elesh Norn, Grand Cenobite',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 134,
                name: 'Kenrith, the Returned King',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 135,
                name: 'Kwende, Pride of Femeref',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 136,
                name: 'Sram, Senior Edificer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 137,
                name: 'Thalia, Guardian of Thraben',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 138,
                name: 'Baral, Chief of Compliance',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 139,
                name: 'Emry, Lurker of the Loch',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 140,
                name: 'Inga Rune-Eyes',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 141,
                name: 'Jin-Gitaxias, Core Augur',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 142,
                name: 'Tetsuko Umezawa, Fugitive',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 143,
                name: 'Ayara, First of Locthwain',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 144,
                name: "Horobi, Death's Wail",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 145,
                name: 'Seizan, Perverter of Truth',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 146,
                name: 'Sheoldred, Whispering One',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 147,
                name: 'Skithiryx, the Blight Dragon',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 148,
                name: 'Tymaret, Chosen from Death',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment,Creature',
                colors: 'B',
            },
            {
                cardNumber: 149,
                name: 'Yargle, Glutton of Urborg',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 150,
                name: 'Captain Lannery Storm',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: 'Ragavan, Nimble Pilferer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Squee, the Immortal',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: 'Urabrask the Hidden',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: 'Valduk, Keeper of the Flame',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: 'Zada, Hedron Grinder',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Fynn, the Fangbearer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 157,
                name: 'Goreclaw, Terror of Qal Sisma',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 158,
                name: 'Renata, Called to the Hunt',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment,Creature',
                colors: 'G',
            },
            {
                cardNumber: 159,
                name: 'Vorinclex, Voice of Hunger',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 160,
                name: 'Yedora, Grave Gardener',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 161,
                name: 'Aegar, the Freezing Flame',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 162,
                name: 'Arixmethes, Slumbering Isle',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 163,
                name: "Atraxa, Praetors' Voice",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U,W',
            },
            {
                cardNumber: 164,
                name: 'Atris, Oracle of Half-Truths',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 165,
                name: 'Aurelia, the Warleader',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 166,
                name: 'Brudiclad, Telchor Engineer',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 167,
                name: 'Dina, Soul Steeper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 168,
                name: 'Ezuri, Claw of Progress',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 169,
                name: 'Firesong and Sunspeaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 170,
                name: 'Firja, Judge of Valor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 171,
                name: 'Grimgrin, Corpse-Born',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 172,
                name: 'Gyruda, Doom of Depths',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 173,
                name: 'Imoti, Celebrant of Bounty',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 174,
                name: 'Jegantha, the Wellspring',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 175,
                name: 'Judith, the Scourge Diva',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 176,
                name: 'Juri, Master of the Revue',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 177,
                name: 'Kaheera, the Orphanguard',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 178,
                name: 'Keruga, the Macrosage',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 179,
                name: "Kroxa, Titan of Death's Hunger",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 180,
                name: 'Lathiel, the Bounteous Dawn',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 181,
                name: 'Lurrus of the Dream-Den',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 182,
                name: 'Lutri, the Spellchaser',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 183,
                name: 'Niv-Mizzet Reborn',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 184,
                name: 'Obosh, the Preypiercer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 185,
                name: 'Radha, Coalition Warlord',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 186,
                name: 'Raff, Weatherlight Stalwart',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 187,
                name: 'Reyav, Master Smith',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 188,
                name: "Rona, Sheoldred's Faithful",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 189,
                name: "Shanna, Sisay's Legacy",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 190,
                name: 'Taigam, Ojutai Master',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 191,
                name: 'Teysa Karlov',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 192,
                name: 'Umori, the Collector',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 193,
                name: 'Yarok, the Desecrated',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U',
            },
            {
                cardNumber: 194,
                name: 'Yorion, Sky Nomad',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 195,
                name: 'Zirda, the Dawnwaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'Multiverse Legends',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
