import { MigrationInterface, QueryRunner } from "typeorm";
import { CardSet } from "../card/entity/card-set.entity";
import { CardVariantType } from "../card/entity/card-variant-type.enum";
import { Card } from "../card/entity/card.entity";
import { PossibleCardVariation } from "../card/entity/possible-card-variation.entity";
import { MigrationHelper } from "./helper/migration-helper";

export class addMat1684249130782 implements MigrationInterface {
  shortName = "MAT";
  public async up(queryRunner: QueryRunner): Promise<void> {
    const cardValues = [
      {
        cardNumber: 1,
        name: "Coppercoat Vanguard",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 2,
        name: "Deification",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 3,
        name: "Harnessed Snubhorn",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 4,
        name: "Metropolis Reformer",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 5,
        name: "Spark Rupture",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 6,
        name: "Tazri, Stalwart Survivor",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 7,
        name: "Filter Out",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "U",
      },
      {
        cardNumber: 8,
        name: "Tolarian Contempt",
        rarity: "U",
        layout: "normal",
        types: "Enchantment",
        colors: "U",
      },
      {
        cardNumber: 9,
        name: "Training Grounds",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "U",
      },
      {
        cardNumber: 10,
        name: "Vesuvan Drifter",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "U",
      },
      {
        cardNumber: 11,
        name: "Ayara\\'s Oathsworn",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 12,
        name: "Blot Out",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "B",
      },
      {
        cardNumber: 13,
        name: "Death-Rattle Oni",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 14,
        name: "Markov Baron",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 15,
        name: "Urborg Scavengers",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 16,
        name: "Arni Metalbrow",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 17,
        name: "Kolaghan Warmonger",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 18,
        name: "Plargg and Nassari",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 19,
        name: "Reckless Handling",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "R",
      },
      {
        cardNumber: 20,
        name: "Animist\\'s Might",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 21,
        name: "Leyline Immersion",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "G",
      },
      {
        cardNumber: 22,
        name: "Nissa, Resurgent Animist",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G",
      },
      {
        cardNumber: 23,
        name: "Open the Way",
        rarity: "R",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 24,
        name: "Tranquil Frillback",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G",
      },
      {
        cardNumber: 25,
        name: "Undercity Upheaval",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 26,
        name: "Calix, Guided by Fate",
        rarity: "M",
        layout: "normal",
        types: "Enchantment,Creature",
        colors: "G,W",
      },
      {
        cardNumber: 27,
        name: "Campus Renovation",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "R,W",
      },
      {
        cardNumber: 28,
        name: "Cosmic Rebirth",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "G,W",
      },
      {
        cardNumber: 29,
        name: "Danitha, New Benalia\\'s Light",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 30,
        name: "Feast of the Victorious Dead",
        rarity: "U",
        layout: "normal",
        types: "Enchantment",
        colors: "B,W",
      },
      {
        cardNumber: 31,
        name: "Gold-Forged Thopteryx",
        rarity: "U",
        layout: "normal",
        types: "Artifact,Creature",
        colors: "U,W",
      },
      {
        cardNumber: 32,
        name: "Jirina, Dauntless General",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,W",
      },
      {
        cardNumber: 33,
        name: "Jolrael, Voice of Zhalfir",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
      {
        cardNumber: 34,
        name: "The Kenriths\\' Royal Funeral",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "B,W",
      },
      {
        cardNumber: 35,
        name: "Kiora, Sovereign of the Deep",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
      {
        cardNumber: 36,
        name: "Nahiri, Forged in Fury",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 37,
        name: "Nahiri\\'s Resolve",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "R,W",
      },
      {
        cardNumber: 38,
        name: "Narset, Enlightened Exile",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U,W",
      },
      {
        cardNumber: 39,
        name: "Nashi, Moon\\'s Legacy",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,U",
      },
      {
        cardNumber: 40,
        name: "Niv-Mizzet, Supreme",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,R,U,W",
      },
      {
        cardNumber: 41,
        name: "Ob Nixilis, Captive Kingpin",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,R",
      },
      {
        cardNumber: 42,
        name: "Pia Nalaar, Consul of Revival",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 43,
        name: "Rebuild the City",
        rarity: "R",
        layout: "normal",
        types: "Sorcery",
        colors: "B,G,R",
      },
      {
        cardNumber: 44,
        name: "Rocco, Street Chef",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,R,W",
      },
      {
        cardNumber: 45,
        name: "Samut, Vizier of Naktamun",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,R",
      },
      {
        cardNumber: 46,
        name: "Sarkhan, Soul Aflame",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U",
      },
      {
        cardNumber: 47,
        name: "Sigarda, Font of Blessings",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 48,
        name: "Tyvar the Bellicose",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,G",
      },
      {
        cardNumber: 49,
        name: "Karn, Legacy Reforged",
        rarity: "M",
        layout: "normal",
        types: "Artifact,Creature",
        colors: "",
      },
      {
        cardNumber: 50,
        name: "Drannith Ruins",
        rarity: "R",
        layout: "normal",
        types: "Land",
        colors: "",
      },
      {
        cardNumber: 51,
        name: "Coppercoat Vanguard",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 52,
        name: "Deification",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 53,
        name: "Harnessed Snubhorn",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 54,
        name: "Metropolis Reformer",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 55,
        name: "Spark Rupture",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 56,
        name: "Tazri, Stalwart Survivor",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 57,
        name: "Filter Out",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "U",
      },
      {
        cardNumber: 58,
        name: "Tolarian Contempt",
        rarity: "U",
        layout: "normal",
        types: "Enchantment",
        colors: "U",
      },
      {
        cardNumber: 59,
        name: "Training Grounds",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "U",
      },
      {
        cardNumber: 60,
        name: "Vesuvan Drifter",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "U",
      },
      {
        cardNumber: 61,
        name: "Ayara\\'s Oathsworn",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 62,
        name: "Blot Out",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "B",
      },
      {
        cardNumber: 63,
        name: "Death-Rattle Oni",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 64,
        name: "Markov Baron",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 65,
        name: "Urborg Scavengers",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 66,
        name: "Arni Metalbrow",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 67,
        name: "Kolaghan Warmonger",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 68,
        name: "Plargg and Nassari",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 69,
        name: "Reckless Handling",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "R",
      },
      {
        cardNumber: 70,
        name: "Animist\\'s Might",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 71,
        name: "Leyline Immersion",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "G",
      },
      {
        cardNumber: 72,
        name: "Nissa, Resurgent Animist",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G",
      },
      {
        cardNumber: 73,
        name: "Open the Way",
        rarity: "R",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 74,
        name: "Tranquil Frillback",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G",
      },
      {
        cardNumber: 75,
        name: "Undercity Upheaval",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 76,
        name: "Calix, Guided by Fate",
        rarity: "M",
        layout: "normal",
        types: "Enchantment,Creature",
        colors: "G,W",
      },
      {
        cardNumber: 77,
        name: "Campus Renovation",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "R,W",
      },
      {
        cardNumber: 78,
        name: "Cosmic Rebirth",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "G,W",
      },
      {
        cardNumber: 79,
        name: "Danitha, New Benalia\\'s Light",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 80,
        name: "Feast of the Victorious Dead",
        rarity: "U",
        layout: "normal",
        types: "Enchantment",
        colors: "B,W",
      },
      {
        cardNumber: 81,
        name: "Gold-Forged Thopteryx",
        rarity: "U",
        layout: "normal",
        types: "Artifact,Creature",
        colors: "U,W",
      },
      {
        cardNumber: 82,
        name: "Jirina, Dauntless General",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,W",
      },
      {
        cardNumber: 83,
        name: "Jolrael, Voice of Zhalfir",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
      {
        cardNumber: 84,
        name: "The Kenriths\\' Royal Funeral",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "B,W",
      },
      {
        cardNumber: 85,
        name: "Kiora, Sovereign of the Deep",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
      {
        cardNumber: 86,
        name: "Nahiri, Forged in Fury",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 87,
        name: "Nahiri\\'s Resolve",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "R,W",
      },
      {
        cardNumber: 88,
        name: "Narset, Enlightened Exile",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U,W",
      },
      {
        cardNumber: 89,
        name: "Nashi, Moon\\'s Legacy",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,U",
      },
      {
        cardNumber: 90,
        name: "Niv-Mizzet, Supreme",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,R,U,W",
      },
      {
        cardNumber: 91,
        name: "Ob Nixilis, Captive Kingpin",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,R",
      },
      {
        cardNumber: 92,
        name: "Pia Nalaar, Consul of Revival",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 93,
        name: "Rebuild the City",
        rarity: "R",
        layout: "normal",
        types: "Sorcery",
        colors: "B,G,R",
      },
      {
        cardNumber: 94,
        name: "Rocco, Street Chef",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,R,W",
      },
      {
        cardNumber: 95,
        name: "Samut, Vizier of Naktamun",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,R",
      },
      {
        cardNumber: 96,
        name: "Sarkhan, Soul Aflame",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U",
      },
      {
        cardNumber: 97,
        name: "Sigarda, Font of Blessings",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 98,
        name: "Tyvar the Bellicose",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,G",
      },
      {
        cardNumber: 99,
        name: "Karn, Legacy Reforged",
        rarity: "M",
        layout: "normal",
        types: "Artifact,Creature",
        colors: "",
      },
      {
        cardNumber: 100,
        name: "Drannith Ruins",
        rarity: "R",
        layout: "normal",
        types: "Land",
        colors: "",
      },
      {
        cardNumber: 101,
        name: "Coppercoat Vanguard",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 102,
        name: "Deification",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 103,
        name: "Harnessed Snubhorn",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 104,
        name: "Metropolis Reformer",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 105,
        name: "Spark Rupture",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 106,
        name: "Tazri, Stalwart Survivor",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 107,
        name: "Filter Out",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "U",
      },
      {
        cardNumber: 108,
        name: "Tolarian Contempt",
        rarity: "U",
        layout: "normal",
        types: "Enchantment",
        colors: "U",
      },
      {
        cardNumber: 109,
        name: "Training Grounds",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "U",
      },
      {
        cardNumber: 110,
        name: "Vesuvan Drifter",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "U",
      },
      {
        cardNumber: 111,
        name: "Ayara\\'s Oathsworn",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 112,
        name: "Blot Out",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "B",
      },
      {
        cardNumber: 113,
        name: "Death-Rattle Oni",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 114,
        name: "Markov Baron",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 115,
        name: "Urborg Scavengers",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 116,
        name: "Arni Metalbrow",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 117,
        name: "Kolaghan Warmonger",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 118,
        name: "Plargg and Nassari",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 119,
        name: "Reckless Handling",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "R",
      },
      {
        cardNumber: 120,
        name: "Animist\\'s Might",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 121,
        name: "Leyline Immersion",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "G",
      },
      {
        cardNumber: 122,
        name: "Nissa, Resurgent Animist",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G",
      },
      {
        cardNumber: 123,
        name: "Open the Way",
        rarity: "R",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 124,
        name: "Tranquil Frillback",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G",
      },
      {
        cardNumber: 125,
        name: "Undercity Upheaval",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 126,
        name: "Calix, Guided by Fate",
        rarity: "M",
        layout: "normal",
        types: "Enchantment,Creature",
        colors: "G,W",
      },
      {
        cardNumber: 127,
        name: "Campus Renovation",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "R,W",
      },
      {
        cardNumber: 128,
        name: "Cosmic Rebirth",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "G,W",
      },
      {
        cardNumber: 129,
        name: "Danitha, New Benalia\\'s Light",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 130,
        name: "Feast of the Victorious Dead",
        rarity: "U",
        layout: "normal",
        types: "Enchantment",
        colors: "B,W",
      },
      {
        cardNumber: 131,
        name: "Gold-Forged Thopteryx",
        rarity: "U",
        layout: "normal",
        types: "Artifact,Creature",
        colors: "U,W",
      },
      {
        cardNumber: 132,
        name: "Jirina, Dauntless General",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,W",
      },
      {
        cardNumber: 133,
        name: "Jolrael, Voice of Zhalfir",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
      {
        cardNumber: 134,
        name: "The Kenriths\\' Royal Funeral",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "B,W",
      },
      {
        cardNumber: 135,
        name: "Kiora, Sovereign of the Deep",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
      {
        cardNumber: 136,
        name: "Nahiri, Forged in Fury",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 137,
        name: "Nahiri\\'s Resolve",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "R,W",
      },
      {
        cardNumber: 138,
        name: "Narset, Enlightened Exile",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U,W",
      },
      {
        cardNumber: 139,
        name: "Nashi, Moon\\'s Legacy",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,U",
      },
      {
        cardNumber: 140,
        name: "Niv-Mizzet, Supreme",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,R,U,W",
      },
      {
        cardNumber: 141,
        name: "Ob Nixilis, Captive Kingpin",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,R",
      },
      {
        cardNumber: 142,
        name: "Pia Nalaar, Consul of Revival",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 143,
        name: "Rebuild the City",
        rarity: "R",
        layout: "normal",
        types: "Sorcery",
        colors: "B,G,R",
      },
      {
        cardNumber: 144,
        name: "Rocco, Street Chef",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,R,W",
      },
      {
        cardNumber: 145,
        name: "Samut, Vizier of Naktamun",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,R",
      },
      {
        cardNumber: 146,
        name: "Sarkhan, Soul Aflame",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U",
      },
      {
        cardNumber: 147,
        name: "Sigarda, Font of Blessings",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 148,
        name: "Tyvar the Bellicose",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,G",
      },
      {
        cardNumber: 149,
        name: "Karn, Legacy Reforged",
        rarity: "M",
        layout: "normal",
        types: "Artifact,Creature",
        colors: "",
      },
      {
        cardNumber: 150,
        name: "Drannith Ruins",
        rarity: "R",
        layout: "normal",
        types: "Land",
        colors: "",
      },
      {
        cardNumber: 151,
        name: "Deification",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 152,
        name: "Metropolis Reformer",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 153,
        name: "Spark Rupture",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 154,
        name: "Tazri, Stalwart Survivor",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 155,
        name: "Training Grounds",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "U",
      },
      {
        cardNumber: 156,
        name: "Vesuvan Drifter",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "U",
      },
      {
        cardNumber: 157,
        name: "Ayara\\'s Oathsworn",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 158,
        name: "Urborg Scavengers",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 159,
        name: "Arni Metalbrow",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 160,
        name: "Plargg and Nassari",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 161,
        name: "Leyline Immersion",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "G",
      },
      {
        cardNumber: 162,
        name: "Nissa, Resurgent Animist",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G",
      },
      {
        cardNumber: 163,
        name: "Open the Way",
        rarity: "R",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 164,
        name: "Tranquil Frillback",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G",
      },
      {
        cardNumber: 165,
        name: "Calix, Guided by Fate",
        rarity: "M",
        layout: "normal",
        types: "Enchantment,Creature",
        colors: "G,W",
      },
      {
        cardNumber: 166,
        name: "Danitha, New Benalia\\'s Light",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 167,
        name: "Jirina, Dauntless General",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,W",
      },
      {
        cardNumber: 168,
        name: "Jolrael, Voice of Zhalfir",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
      {
        cardNumber: 169,
        name: "The Kenriths\\' Royal Funeral",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "B,W",
      },
      {
        cardNumber: 170,
        name: "Kiora, Sovereign of the Deep",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
      {
        cardNumber: 171,
        name: "Nahiri, Forged in Fury",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 172,
        name: "Nahiri\\'s Resolve",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "R,W",
      },
      {
        cardNumber: 173,
        name: "Narset, Enlightened Exile",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U,W",
      },
      {
        cardNumber: 174,
        name: "Nashi, Moon\\'s Legacy",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,U",
      },
      {
        cardNumber: 175,
        name: "Niv-Mizzet, Supreme",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,R,U,W",
      },
      {
        cardNumber: 176,
        name: "Ob Nixilis, Captive Kingpin",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,R",
      },
      {
        cardNumber: 177,
        name: "Pia Nalaar, Consul of Revival",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 178,
        name: "Rebuild the City",
        rarity: "R",
        layout: "normal",
        types: "Sorcery",
        colors: "B,G,R",
      },
      {
        cardNumber: 179,
        name: "Rocco, Street Chef",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,R,W",
      },
      {
        cardNumber: 180,
        name: "Samut, Vizier of Naktamun",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,R",
      },
      {
        cardNumber: 181,
        name: "Sarkhan, Soul Aflame",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U",
      },
      {
        cardNumber: 182,
        name: "Sigarda, Font of Blessings",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 183,
        name: "Tyvar the Bellicose",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,G",
      },
      {
        cardNumber: 184,
        name: "Karn, Legacy Reforged",
        rarity: "M",
        layout: "normal",
        types: "Artifact,Creature",
        colors: "",
      },
      {
        cardNumber: 185,
        name: "Drannith Ruins",
        rarity: "R",
        layout: "normal",
        types: "Land",
        colors: "",
      },
      {
        cardNumber: 186,
        name: "Coppercoat Vanguard",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 187,
        name: "Deification",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 188,
        name: "Harnessed Snubhorn",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 189,
        name: "Metropolis Reformer",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 190,
        name: "Tazri, Stalwart Survivor",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "W",
      },
      {
        cardNumber: 191,
        name: "Filter Out",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "U",
      },
      {
        cardNumber: 192,
        name: "Tolarian Contempt",
        rarity: "U",
        layout: "normal",
        types: "Enchantment",
        colors: "U",
      },
      {
        cardNumber: 193,
        name: "Training Grounds",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "U",
      },
      {
        cardNumber: 194,
        name: "Vesuvan Drifter",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "U",
      },
      {
        cardNumber: 195,
        name: "Ayara\\'s Oathsworn",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 196,
        name: "Blot Out",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "B",
      },
      {
        cardNumber: 197,
        name: "Death-Rattle Oni",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 198,
        name: "Markov Baron",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 199,
        name: "Urborg Scavengers",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B",
      },
      {
        cardNumber: 200,
        name: "Arni Metalbrow",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 201,
        name: "Kolaghan Warmonger",
        rarity: "U",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 202,
        name: "Plargg and Nassari",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R",
      },
      {
        cardNumber: 203,
        name: "Reckless Handling",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "R",
      },
      {
        cardNumber: 204,
        name: "Tranquil Frillback",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G",
      },
      {
        cardNumber: 205,
        name: "Undercity Upheaval",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "G",
      },
      {
        cardNumber: 206,
        name: "Calix, Guided by Fate",
        rarity: "M",
        layout: "normal",
        types: "Enchantment,Creature",
        colors: "G,W",
      },
      {
        cardNumber: 207,
        name: "Campus Renovation",
        rarity: "U",
        layout: "normal",
        types: "Sorcery",
        colors: "R,W",
      },
      {
        cardNumber: 208,
        name: "Cosmic Rebirth",
        rarity: "U",
        layout: "normal",
        types: "Instant",
        colors: "G,W",
      },
      {
        cardNumber: 209,
        name: "Danitha, New Benalia\\'s Light",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 210,
        name: "Feast of the Victorious Dead",
        rarity: "U",
        layout: "normal",
        types: "Enchantment",
        colors: "B,W",
      },
      {
        cardNumber: 211,
        name: "Gold-Forged Thopteryx",
        rarity: "U",
        layout: "normal",
        types: "Artifact,Creature",
        colors: "U,W",
      },
      {
        cardNumber: 212,
        name: "Jirina, Dauntless General",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,W",
      },
      {
        cardNumber: 213,
        name: "The Kenriths\\' Royal Funeral",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "B,W",
      },
      {
        cardNumber: 214,
        name: "Kiora, Sovereign of the Deep",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
      {
        cardNumber: 215,
        name: "Nahiri, Forged in Fury",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 216,
        name: "Nahiri\\'s Resolve",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "R,W",
      },
      {
        cardNumber: 217,
        name: "Narset, Enlightened Exile",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U,W",
      },
      {
        cardNumber: 218,
        name: "Nashi, Moon\\'s Legacy",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,U",
      },
      {
        cardNumber: 219,
        name: "Niv-Mizzet, Supreme",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "B,G,R,U,W",
      },
      {
        cardNumber: 220,
        name: "Ob Nixilis, Captive Kingpin",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,R",
      },
      {
        cardNumber: 221,
        name: "Pia Nalaar, Consul of Revival",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "R,W",
      },
      {
        cardNumber: 222,
        name: "Rebuild the City",
        rarity: "R",
        layout: "normal",
        types: "Sorcery",
        colors: "B,G,R",
      },
      {
        cardNumber: 223,
        name: "Rocco, Street Chef",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,R,W",
      },
      {
        cardNumber: 224,
        name: "Samut, Vizier of Naktamun",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "G,R",
      },
      {
        cardNumber: 225,
        name: "Sarkhan, Soul Aflame",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "R,U",
      },
      {
        cardNumber: 226,
        name: "Sigarda, Font of Blessings",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,W",
      },
      {
        cardNumber: 227,
        name: "Tyvar the Bellicose",
        rarity: "M",
        layout: "normal",
        types: "Creature",
        colors: "B,G",
      },
      {
        cardNumber: 228,
        name: "Drannith Ruins",
        rarity: "R",
        layout: "normal",
        types: "Land",
        colors: "",
      },
      {
        cardNumber: 229,
        name: "Spark Rupture",
        rarity: "R",
        layout: "normal",
        types: "Enchantment",
        colors: "W",
      },
      {
        cardNumber: 230,
        name: "Jolrael, Voice of Zhalfir",
        rarity: "R",
        layout: "normal",
        types: "Creature",
        colors: "G,U",
      },
    ];

    await MigrationHelper.cardSetUp(
      queryRunner,
      "March of the Machine: The Aftermath",
      this.shortName,
      cardValues,
      [
        `id`,
        `cardNumber`,
        `name`,
        `rarity`,
        `layout`,
        `cardSet`,
        `colors`,
        `types`,
      ]
    );

    const cards = await queryRunner.manager
      .createQueryBuilder<Card>("Card", "c")
      .select("c.id")
      .leftJoin(CardSet, "cs", "c.card_set_1 = cs.id")
      .where("cs.short_name = :shortName", { shortName: this.shortName })
      .getMany();

    const insertDefaultPossibleCards: PossibleCardVariation[] = [];
    cards.forEach((card) => {
      const defaultPossibleCard = queryRunner.manager
        .getRepository<PossibleCardVariation>(PossibleCardVariation)
        .create();
      defaultPossibleCard.card = card;
      defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
      defaultPossibleCard.hasNormal = true;
      defaultPossibleCard.hasFoil = true;
      insertDefaultPossibleCards.push(defaultPossibleCard);
    });

    await queryRunner.manager
      .getRepository<PossibleCardVariation>(PossibleCardVariation)
      .insert(insertDefaultPossibleCards);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    const deletablePossibleCardVariations = await queryRunner.manager
      .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, "pcv")
      .select(["pcv.id"])
      .innerJoin(Card, "c", "pcv.card_1 = c.id")
      .innerJoin(CardSet, "cs", "cs.id = c.card_set_1")
      .where(`cs.short_name = '${this.shortName}'`)
      .getMany();

    if (deletablePossibleCardVariations.length > 0) {
      await queryRunner.manager.delete<PossibleCardVariation>(
        PossibleCardVariation,
        deletablePossibleCardVariations
      );
    }

    await MigrationHelper.cardSetDown(queryRunner, this.shortName);
  }
}
