import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addWoe1693680778483 implements MigrationInterface {
    shortName = 'WOE';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Archon of the Wild Rose',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 2,
                name: "Archon's Glory",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 3,
                name: 'Armory Mice',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'Besotted Knight // Betroth the Beast',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'Break the Spell',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Charmed Clothier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Cheeky House-Mouse // Squeak By',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Cooped Up',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Cursed Courtier',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Discerning Financier',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Dutiful Griffin',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Eerie Interference',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Expel the Interlopers',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Frostbridge Guard',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Gallant Pie-Wielder',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Glass Casket',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Hopeful Vigil',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: "Kellan's Lightblades",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: 'Knight of Doves',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Moment of Valor',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: 'Moonshaker Cavalry',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Plunge into Winter',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'The Princess Takes Flight',
                rarity: 'U',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'Protective Parents',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Regal Bunnicorn',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Return Triumphant',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: 'Rimefur Reindeer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Savior of the Sleeping',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: 'Slumbering Keepguard',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Solitary Sanctuary',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Spellbook Vendor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Stockpiling Celebrant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: 'Stroke of Midnight',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: 'A Tale for the Ages',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: 'Three Blind Mice',
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: 'Tuinvale Guide',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Unassuming Sage',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Virtue of Loyalty // Ardenvale Fealty',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 39,
                name: 'Werefox Bodyguard',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 40,
                name: 'Aquatic Alchemist // Bubble Up',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 41,
                name: 'Archive Dragon',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 42,
                name: 'Asinine Antics',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 43,
                name: "Beluna's Gatekeeper // Entry Denied",
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 44,
                name: 'Bitter Chill',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 45,
                name: 'Chancellor of Tales',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 46,
                name: 'Diminisher Witch',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Disdainful Stroke',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Extraordinary Journey',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Farsight Ritual',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Freeze in Place',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: "Gadwick's First Duel",
                rarity: 'U',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: 'Galvanic Giant // Storm Reading',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Horned Loch-Whale // Lagoon Breach',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Ice Out',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: 'Icewrought Sentry',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'Ingenious Prodigy',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Into the Fae Court',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: "Johann's Stopgap",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Living Lectern',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Merfolk Coralsmith',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: 'Misleading Motes',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Mocking Sprite',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: "Obyra's Attendants // Desperate Parry",
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'Picklock Prankster // Free the Fae',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: 'Quick Study',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: 'Sleep-Cursed Faerie',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Sleight of Hand',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: 'Snaremaster Sprite',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Spell Stutter',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Splashy Spellcaster',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: 'Stormkeld Prowler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'Succumb to the Cold',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 73,
                name: "Talion's Messenger",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Tenacious Tomeseeker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: 'Vantress Transmuter // Croaking Curse',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Virtue of Knowledge // Vantress Visions',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'Water Wings',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Ashiok, Wicked Manipulator',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B',
            },
            {
                cardNumber: 79,
                name: "Ashiok's Reaper",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 80,
                name: 'Back for Seconds',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 81,
                name: 'Barrow Naughty',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 82,
                name: 'Beseech the Mirror',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 83,
                name: 'Candy Grapple',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 84,
                name: 'Conceited Witch // Price of Beauty',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 85,
                name: 'Dream Spoilers',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 86,
                name: 'Ego Drain',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 87,
                name: 'The End',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 88,
                name: "Eriette's Whisper",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 89,
                name: 'Faerie Dreamthief',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 90,
                name: 'Faerie Fencing',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: 'Feed the Cauldron',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: 'Fell Horseman // Deathly Ride',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Gumdrop Poisoner // Tempt with Treats',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'High Fae Negotiator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Hopeless Nightmare',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: "Lich-Knights' Conquest",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: 'Lord Skitter, Sewer King',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: "Lord Skitter's Blessing",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: "Lord Skitter's Butcher",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Mintstrosity',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Not Dead After All',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: "Rankle's Prank",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Rat Out',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: "Rowan's Grim Search",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Scream Puff',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'Shatter the Oath',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 107,
                name: 'Specter of Mortality',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 108,
                name: 'Spiteful Hexmage',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 109,
                name: 'Stingblade Assassin',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 110,
                name: 'Sugar Rush',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 111,
                name: 'Sweettooth Witch',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 112,
                name: 'Taken by Nightmares',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 113,
                name: 'Tangled Colony',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 114,
                name: 'Twisted Sewer-Witch',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 115,
                name: 'Virtue of Persistence // Locthwain Scorn',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 116,
                name: 'Voracious Vermin',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 117,
                name: 'Warehouse Tabby',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 118,
                name: 'Wicked Visitor',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 119,
                name: "The Witch's Vanity",
                rarity: 'U',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 120,
                name: 'Belligerent of the Ball',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 121,
                name: 'Bellowing Bruiser // Beat a Path',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 122,
                name: 'Bespoke Battlegarb',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 123,
                name: 'Boundary Lands Ranger',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 124,
                name: 'Charming Scoundrel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 125,
                name: 'Cut In',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 126,
                name: 'Edgewall Pack',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 127,
                name: 'Embereth Veteran',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 128,
                name: 'Flick a Coin',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 129,
                name: 'Food Fight',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 130,
                name: 'Frantic Firebolt',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 131,
                name: 'Gnawing Crescendo',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 132,
                name: 'Goddric, Cloaked Reveler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 133,
                name: "Grabby Giant // That's Mine",
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 134,
                name: 'Grand Ball Guest',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 135,
                name: 'Harried Spearguard',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 136,
                name: 'Hearth Elemental // Stoke Genius',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 137,
                name: 'Imodane, the Pyrohammer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 138,
                name: 'Kindled Heroism',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 139,
                name: 'Korvold and the Noble Thief',
                rarity: 'U',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 140,
                name: 'Merry Bards',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 141,
                name: 'Minecart Daredevil // Ride the Rails',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 142,
                name: 'Monstrous Rage',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 143,
                name: 'Raging Battle Mouse',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 144,
                name: 'Ratcatcher Trainee // Pest Problem',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 145,
                name: 'Realm-Scorcher Hellkite',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 146,
                name: 'Redcap Gutter-Dweller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 147,
                name: 'Redcap Thief',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 148,
                name: 'Rotisserie Elemental',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 149,
                name: 'Skewer Slinger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 150,
                name: 'Song of Totentanz',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: 'Stonesplitter Bolt',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Tattered Ratter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: 'Torch the Tower',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: 'Twisted Fealty',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: 'Two-Headed Hunter // Twice the Rage',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Unruly Catapult',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 157,
                name: 'Virtue of Courage // Embereth Blaze',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 158,
                name: "Witch's Mark",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 159,
                name: 'Witchstalker Frenzy',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 160,
                name: "Agatha's Champion",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 161,
                name: 'Beanstalk Wurm // Plant Beans',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 162,
                name: 'Bestial Bloodline',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 163,
                name: 'Blossoming Tortoise',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 164,
                name: 'Bramble Familiar // Fetch Quest',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 165,
                name: 'Brave the Wilds',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 166,
                name: 'Commune with Nature',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 167,
                name: 'Curse of the Werefox',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 168,
                name: 'Elvish Archivist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 169,
                name: 'Feral Encounter',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 170,
                name: 'Ferocious Werefox // Guard Change',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 171,
                name: 'Graceful Takedown',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 172,
                name: 'Gruff Triplets',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 173,
                name: 'Hamlet Glutton',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 174,
                name: 'Hollow Scavenger // Bakery Raid',
                rarity: 'C',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 175,
                name: 'Howling Galefang',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 176,
                name: "The Huntsman's Redemption",
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 177,
                name: 'Leaping Ambush',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 178,
                name: "Night of the Sweets' Revenge",
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 179,
                name: 'Redtooth Genealogist',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 180,
                name: 'Redtooth Vanguard',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 181,
                name: 'Return from the Wilds',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 182,
                name: 'Rootrider Faun',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 183,
                name: 'Royal Treatment',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 184,
                name: 'Sentinel of Lost Lore',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 185,
                name: 'Skybeast Tracker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: 'Spider Food',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Stormkeld Vanguard // Bear Down',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Tanglespan Lookout',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Territorial Witchstalker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: 'Thunderous Debut',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Titanic Growth',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 192,
                name: 'Toadstool Admirer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 193,
                name: 'Tough Cookie',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'G',
            },
            {
                cardNumber: 194,
                name: 'Troublemaker Ouphe',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 195,
                name: 'Up the Beanstalk',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 196,
                name: 'Verdant Outrider',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 197,
                name: 'Virtue of Strength // Garenbrig Growth',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 198,
                name: 'Welcome to Sweettooth',
                rarity: 'U',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 199,
                name: 'Agatha of the Vile Cauldron',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 200,
                name: "The Apprentice's Folly",
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'R,U',
            },
            {
                cardNumber: 201,
                name: 'Ash, Party Crasher',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 202,
                name: 'Eriette of the Charmed Apple',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 203,
                name: 'Faunsbane Troll',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 204,
                name: 'The Goose Mother',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 205,
                name: 'Greta, Sweettooth Scourge',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 206,
                name: 'Hylda of the Icy Crown',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 207,
                name: 'Johann, Apprentice Sorcerer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 208,
                name: 'Likeness Looter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 209,
                name: 'Neva, Stalked by Nightmares',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 210,
                name: 'Obyra, Dreaming Duelist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 211,
                name: 'Rowan, Scion of War',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 212,
                name: 'Ruby, Daring Tracker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 213,
                name: 'Sharae of Numbing Depths',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 214,
                name: 'Syr Armont, the Redeemer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 215,
                name: 'Talion, the Kindly Lord',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 216,
                name: 'Totentanz, Swarm Piper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 217,
                name: 'Troyan, Gutsy Explorer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 218,
                name: 'Will, Scion of Peace',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 219,
                name: 'Yenna, Redtooth Regent',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 220,
                name: 'Beluna Grandsquall // Seek Thrills',
                rarity: 'M',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U,R,G',
            },
            {
                cardNumber: 221,
                name: 'Callous Sell-Sword // Burn Together',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 222,
                name: "Cruel Somnophage // Can't Wake Up",
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 223,
                name: 'Decadent Dragon // Expensive Taste',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 224,
                name: 'Devouring Sugarmaw // Have for Dinner',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 225,
                name: "Elusive Otter // Grove's Bounty",
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 226,
                name: 'Frolicking Familiar // Blow Off Steam',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 227,
                name: 'Gingerbread Hunter // Puny Snack',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 228,
                name: 'Heartflame Duelist // Heartflame Slash',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 229,
                name: "Imodane's Recruiter // Train Troops",
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 230,
                name: 'Kellan, the Fae-Blooded // Birthright Boon',
                rarity: 'M',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 231,
                name: 'Mosswood Dreadknight // Dread Whispers',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 232,
                name: 'Picnic Ruiner // Stolen Goodies',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 233,
                name: 'Pollen-Shield Hare // Hare Raising',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 234,
                name: 'Questing Druid // Seek the Beast',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 235,
                name: 'Scalding Viper // Steam Clean',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 236,
                name: 'Shrouded Shepherd // Cleave Shadows',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 237,
                name: 'Spellscorn Coven // Take It Back',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 238,
                name: 'Tempest Hart // Scan the Clouds',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 239,
                name: 'Threadbind Clique // Rip the Seams',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 240,
                name: 'Twining Twins // Swift Spiral',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 241,
                name: 'Woodland Acolyte // Mend the Wilds',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 242,
                name: "Agatha's Soul Cauldron",
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 243,
                name: 'Candy Trail',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 244,
                name: "Collector's Vault",
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 245,
                name: "Eriette's Tempting Apple",
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 246,
                name: 'Gingerbrute',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 247,
                name: "Hylda's Crown of Winter",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 248,
                name: 'The Irencrag',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 249,
                name: 'Prophetic Prism',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 250,
                name: 'Scarecrow Guide',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 251,
                name: 'Soul-Guide Lantern',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 252,
                name: 'Syr Ginger, the Meal Ender',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 253,
                name: 'Three Bowls of Porridge',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 254,
                name: 'Crystal Grotto',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 255,
                name: 'Edgewall Inn',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 256,
                name: 'Evolving Wilds',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 257,
                name: 'Restless Bivouac',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 258,
                name: 'Restless Cottage',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 259,
                name: 'Restless Fortress',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Restless Spire',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'Restless Vinestalk',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 263,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 264,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 266,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Virtue of Loyalty // Ardenvale Fealty',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 278,
                name: 'Horned Loch-Whale // Lagoon Breach',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 279,
                name: 'Virtue of Knowledge // Vantress Visions',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 280,
                name: 'Gumdrop Poisoner // Tempt with Treats',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 281,
                name: 'Virtue of Persistence // Locthwain Scorn',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 282,
                name: 'Virtue of Courage // Embereth Blaze',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 283,
                name: 'Bramble Familiar // Fetch Quest',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 284,
                name: 'Virtue of Strength // Garenbrig Growth',
                rarity: 'M',
                layout: 'adventure',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 285,
                name: 'Beluna Grandsquall // Seek Thrills',
                rarity: 'M',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U,R,G',
            },
            {
                cardNumber: 286,
                name: "Cruel Somnophage // Can't Wake Up",
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 287,
                name: 'Decadent Dragon // Expensive Taste',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 288,
                name: 'Devouring Sugarmaw // Have for Dinner',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 289,
                name: "Elusive Otter // Grove's Bounty",
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 290,
                name: 'Heartflame Duelist // Heartflame Slash',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 291,
                name: 'Kellan, the Fae-Blooded // Birthright Boon',
                rarity: 'M',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 292,
                name: 'Mosswood Dreadknight // Dread Whispers',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 293,
                name: 'Pollen-Shield Hare // Hare Raising',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 294,
                name: 'Questing Druid // Seek the Beast',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 295,
                name: 'Scalding Viper // Steam Clean',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 296,
                name: 'Twining Twins // Swift Spiral',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 297,
                name: 'Ashiok, Wicked Manipulator',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B',
            },
            {
                cardNumber: 298,
                name: 'Kellan, the Fae-Blooded // Birthright Boon',
                rarity: 'M',
                layout: 'adventure',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 299,
                name: 'Eriette of the Charmed Apple',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 300,
                name: 'Rowan, Scion of War',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 301,
                name: 'Talion, the Kindly Lord',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 302,
                name: 'Will, Scion of Peace',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 303,
                name: 'Restless Bivouac',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 304,
                name: 'Restless Cottage',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 305,
                name: 'Restless Fortress',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 306,
                name: 'Restless Spire',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 307,
                name: 'Restless Vinestalk',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 308,
                name: 'Food Coma',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 309,
                name: 'Lady of Laughter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 310,
                name: 'Pests of Honor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 311,
                name: 'Faerie Slumber Party',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 312,
                name: 'Rowdy Research',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 313,
                name: 'Storyteller Pixie',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 314,
                name: 'Experimental Confectioner',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 315,
                name: 'Malevolent Witchkite',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 316,
                name: 'Old Flitterfang',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 317,
                name: 'Become Brutes',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 318,
                name: 'Charging Hooligan',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 319,
                name: 'Ogre Chitterlord',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 320,
                name: 'Intrepid Trufflesnout // Go Hog Wild',
                rarity: 'U',
                layout: 'adventure',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 321,
                name: 'Provisions Merchant',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 322,
                name: 'Wildwood Mentor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 323,
                name: 'Archon of the Wild Rose',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 324,
                name: 'Expel the Interlopers',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 325,
                name: 'Moonshaker Cavalry',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 326,
                name: 'Regal Bunnicorn',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 327,
                name: 'Spellbook Vendor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 328,
                name: 'A Tale for the Ages',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 329,
                name: 'Werefox Bodyguard',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 330,
                name: 'Asinine Antics',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 331,
                name: 'Extraordinary Journey',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 332,
                name: 'Farsight Ritual',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 333,
                name: 'Ingenious Prodigy',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 334,
                name: 'Sleep-Cursed Faerie',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 335,
                name: "Talion's Messenger",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 336,
                name: 'Beseech the Mirror',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 337,
                name: 'The End',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 338,
                name: "Lich-Knights' Conquest",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 339,
                name: 'Lord Skitter, Sewer King',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 340,
                name: "Lord Skitter's Blessing",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 341,
                name: "Rankle's Prank",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 342,
                name: 'Specter of Mortality',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 343,
                name: 'Spiteful Hexmage',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 344,
                name: 'Tangled Colony',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 345,
                name: 'Charming Scoundrel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 346,
                name: 'Food Fight',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 347,
                name: 'Goddric, Cloaked Reveler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 348,
                name: 'Imodane, the Pyrohammer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 349,
                name: 'Raging Battle Mouse',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 350,
                name: 'Realm-Scorcher Hellkite',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 351,
                name: 'Redcap Gutter-Dweller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 352,
                name: 'Rotisserie Elemental',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 353,
                name: 'Song of Totentanz',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 354,
                name: 'Blossoming Tortoise',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 355,
                name: 'Elvish Archivist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 356,
                name: 'Feral Encounter',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 357,
                name: 'Gruff Triplets',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 358,
                name: 'Sentinel of Lost Lore',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 359,
                name: 'Thunderous Debut',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 360,
                name: 'Agatha of the Vile Cauldron',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 361,
                name: 'Faunsbane Troll',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 362,
                name: 'The Goose Mother',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 363,
                name: 'Hylda of the Icy Crown',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 364,
                name: 'Likeness Looter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 365,
                name: 'Yenna, Redtooth Regent',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 366,
                name: "Agatha's Soul Cauldron",
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 367,
                name: "Hylda's Crown of Winter",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 368,
                name: 'The Irencrag',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 369,
                name: 'Syr Ginger, the Meal Ender',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 370,
                name: 'Lady of Laughter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 371,
                name: 'Faerie Slumber Party',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 372,
                name: 'Malevolent Witchkite',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 373,
                name: 'Ogre Chitterlord',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 374,
                name: 'Wildwood Mentor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 375,
                name: 'Stroke of Midnight',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 376,
                name: 'Sleight of Hand',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 377,
                name: 'Faerie Dreamthief',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 378,
                name: 'Torch the Tower',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 379,
                name: 'Tanglespan Lookout',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 380,
                name: "Lich-Knights' Conquest",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 381,
                name: 'Expel the Interlopers',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'Wilds of Eldraine',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
