import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addLci1699810202037 implements MigrationInterface {
    shortName = 'LCI';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: "Abuelo's Awakening",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 2,
                name: 'Acrobatic Leap',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 3,
                name: 'Adaptive Gemguard',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'Attentive Sunscribe',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'Bat Colony',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Clay-Fired Bricks // Cosmium Kiln',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Cosmium Blast',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Dauntless Dismantler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Deconstruction Hammer',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Dusk Rose Reliquary',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Envoy of Okinec Ahau',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Fabrication Foundry',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Family Reunion',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Get Lost',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Glorifier of Suffering',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Guardian of the Great Door',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Helping Hand',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Ironpaw Aspirant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: "Kinjalli's Dawnrunner",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: "Kutzil's Flanker",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: 'Malamet War Scribe',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Market Gnome',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'Might of the Ancestors',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: "Miner's Guidewing",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Mischievous Pup',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Ojer Taq, Deepest Foundation // Temple of Civilization',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: 'Oltec Archaeologists',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Oltec Cloud Guard',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: 'Oteclan Landmark // Oteclan Levitator',
                rarity: 'C',
                layout: 'transform',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Petrify',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Quicksand Whirlpool',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Resplendent Angel',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: 'Ruin-Lurker Bat',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: 'Sanguine Evangelist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: 'Soaring Sandwing',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: 'Spring-Loaded Sawblades // Bladewheel Chariot',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Thousand Moons Crackshot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Thousand Moons Infantry',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 39,
                name: 'Thousand Moons Smithy // Barracks of the Thousand',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 40,
                name: "Tinker's Tote",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 41,
                name: 'Unstable Glyphbridge // Sandswirl Wanderglyph',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 42,
                name: 'Vanguard of the Rose',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 43,
                name: 'Warden of the Inner Sky',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 44,
                name: 'Akal Pakal, First Among Equals',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 45,
                name: 'Ancestral Reminiscence',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 46,
                name: 'Brackish Blunder',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Braided Net // Braided Quipu',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Chart a Course',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Cogwork Wrestler',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Confounding Riddle',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: 'Council of Echoes',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: 'Deeproot Pilgrimage',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Didact Echo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Eaten by Piranhas',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: 'The Enigma Jewel // Locus of Enlightenment',
                rarity: 'M',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'The Everflowing Well // The Myriad Pools',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Frilled Cave-Wurm',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: 'Hermitic Nautilus',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Hurl into History',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Inverted Iceberg // Iceberg Titan',
                rarity: 'C',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: 'Kitesail Larcenist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Lodestone Needle // Guidestone Compass',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: 'Malcolm, Alluring Scoundrel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'Marauding Brinefang',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: 'Merfolk Cave-Diver',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: 'Oaken Siren',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Ojer Pakpatiq, Deepest Epoch // Temple of Cyclical Time',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: 'Orazca Puzzle-Door',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Out of Air',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Pirate Hat',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: "Relic's Roar",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'River Herald Scout',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 73,
                name: 'Sage of Days',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Self-Reflection',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: 'Shipwreck Sentry',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Sinuous Benthisaur',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'Song of Stupefaction',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Spyglass Siren',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 79,
                name: 'Staunch Crewmate',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 80,
                name: 'Subterranean Schooner',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 81,
                name: "Tishana's Tidebinder",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 82,
                name: 'Unlucky Drop',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 83,
                name: 'Waterlogged Hulk // Watertight Gondola',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 84,
                name: 'Waterwind Scout',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 85,
                name: 'Waylaying Pirates',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 86,
                name: 'Zoetic Glyph',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 87,
                name: 'Abyssal Gorestalker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 88,
                name: 'Aclazotz, Deepest Betrayal // Temple of the Dead',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 89,
                name: 'Acolyte of Aclazotz',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 90,
                name: 'Another Chance',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: 'Bitter Triumph',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: 'Bloodletter of Aclazotz',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Bloodthorn Flail',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'Bringer of the Last Gift',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Broodrage Mycoid',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Canonized in Blood',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: 'Chupacabra Echo',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'Corpses of the Lost',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Dead Weight',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Deathcap Marionette',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Deep Goblin Skulltaker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Deep-Cavern Bat',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Defossilize',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: 'Echo of Dusk',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Fanatical Offering',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'Fungal Fortitude',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 107,
                name: 'Gargantuan Leech',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 108,
                name: "Grasping Shadows // Shadows' Lair",
                rarity: 'U',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 109,
                name: 'Greedy Freebooter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 110,
                name: 'Join the Dead',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 111,
                name: 'Malicious Eclipse',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 112,
                name: 'Mephitic Draught',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 113,
                name: 'Preacher of the Schism',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 114,
                name: 'Primordial Gnawer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 115,
                name: "Queen's Bay Paladin",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 116,
                name: 'Rampaging Spiketail',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 117,
                name: 'Ray of Ruin',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 118,
                name: 'Screaming Phantom',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 119,
                name: 'Skullcap Snail',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 120,
                name: 'Soulcoil Viper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 121,
                name: 'Souls of the Lost',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 122,
                name: 'Stalactite Stalker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 123,
                name: 'Starving Revenant',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 124,
                name: 'Stinging Cave Crawler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 125,
                name: 'Synapse Necromage',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 126,
                name: "Tarrian's Journal // The Tomb of Aclazotz",
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 127,
                name: 'Terror Tide',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 128,
                name: 'Tithing Blade // Consuming Sepulcher',
                rarity: 'C',
                layout: 'transform',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 129,
                name: 'Visage of Dread // Dread Osseosaur',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 130,
                name: "Vito's Inquisitor",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 131,
                name: 'Abrade',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 132,
                name: "Ancestors' Aid",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 133,
                name: 'Belligerent Yearling',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 134,
                name: 'Bonehoard Dracosaur',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 135,
                name: "Brass's Tunnel-Grinder // Tecutlan, the Searing Rift",
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 136,
                name: 'Brazen Blademaster',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 137,
                name: 'Breeches, Eager Pillager',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 138,
                name: 'Burning Sun Cavalry',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 139,
                name: 'Calamitous Cave-In',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 140,
                name: 'Child of the Volcano',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 141,
                name: "Curator of Sun's Creation",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 142,
                name: 'Daring Discovery',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 143,
                name: 'Diamond Pick-Axe',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 144,
                name: 'Dinotomaton',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 145,
                name: 'Dire Flail // Dire Blunderbuss',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 146,
                name: 'Dowsing Device // Geode Grotto',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 147,
                name: "Dreadmaw's Ire",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 148,
                name: 'Enterprising Scallywag',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 149,
                name: "Etali's Favor",
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 150,
                name: 'Geological Appraiser',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: 'Goblin Tomb Raider',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Goldfury Strider',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: 'Hit the Mother Lode',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: 'Hotfoot Gnome',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: "Idol of the Deep King // Sovereign's Macuahuitl",
                rarity: 'C',
                layout: 'transform',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Inti, Seneschal of the Sun',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 157,
                name: 'Magmatic Galleon',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 158,
                name: 'Ojer Axonil, Deepest Might // Temple of Power',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 159,
                name: 'Panicked Altisaur',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 160,
                name: 'Plundering Pirate',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 161,
                name: 'Poetic Ingenuity',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 162,
                name: 'Rampaging Ceratops',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 163,
                name: 'Rumbling Rockslide',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 164,
                name: "Saheeli's Lattice // Mastercraft Raptor",
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 165,
                name: 'Scytheclaw Raptor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 166,
                name: 'Seismic Monstrosaur',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 167,
                name: 'Sunfire Torch',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 168,
                name: 'Sunshot Militia',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 169,
                name: 'Tectonic Hazard',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 170,
                name: 'Triumphant Chomp',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 171,
                name: 'Trumpeting Carnosaur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 172,
                name: 'Volatile Wanderglyph',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 173,
                name: "Zoyowa's Justice",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 174,
                name: 'Armored Kincaller',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 175,
                name: 'Basking Capybara',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 176,
                name: 'Bedrock Tortoise',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 177,
                name: 'Cavern Stomper',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 178,
                name: 'Cenote Scout',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 179,
                name: 'Coati Scavenger',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 180,
                name: 'Colossadactyl',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 181,
                name: 'Cosmium Confluence',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 182,
                name: 'Disturbed Slumber',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 183,
                name: 'Earthshaker Dreadmaw',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 184,
                name: "Explorer's Cache",
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 185,
                name: 'Ghalta, Stampede Tyrant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: 'Glimpse the Core',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Glowcap Lantern',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Growing Rites of Itlimoc // Itlimoc, Cradle of the Sun',
                rarity: 'R',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Huatli, Poet of Unity // Roar of the Fifth People',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: "Huatli's Final Strike",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Hulking Raptor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 192,
                name: 'In the Presence of Ages',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 193,
                name: 'Intrepid Paleontologist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 194,
                name: "Ixalli's Lorekeeper",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 195,
                name: 'Jade Seedstones // Jadeheart Attendant',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 196,
                name: 'Jadelight Spelunker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 197,
                name: "Kaslem's Stonetree // Kaslem's Strider",
                rarity: 'C',
                layout: 'transform',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 198,
                name: 'Malamet Battle Glyph',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 199,
                name: 'Malamet Brawler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 200,
                name: 'Malamet Scythe',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 201,
                name: 'Malamet Veteran',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 202,
                name: 'Mineshaft Spider',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 203,
                name: 'Nurturing Bristleback',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 204,
                name: 'Ojer Kaslem, Deepest Growth // Temple of Cultivation',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 205,
                name: 'Over the Edge',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 206,
                name: 'Pathfinding Axejaw',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 207,
                name: 'Poison Dart Frog',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 208,
                name: 'Pugnacious Hammerskull',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 209,
                name: 'River Herald Guide',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 210,
                name: 'Seeker of Sunlight',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 211,
                name: 'Sentinel of the Nameless City',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 212,
                name: 'The Skullspore Nexus',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 213,
                name: 'Spelunking',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 214,
                name: 'Staggering Size',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 215,
                name: 'Tendril of the Mycotyrant',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 216,
                name: 'Thrashing Brontodon',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 217,
                name: 'Twists and Turns // Mycoid Maze',
                rarity: 'U',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 218,
                name: 'Walk with the Ancestors',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 219,
                name: 'Abuelo, Ancestral Echo',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 220,
                name: 'Akawalli, the Seething Tower',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 221,
                name: 'Amalia Benavides Aguirre',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 222,
                name: 'The Ancient One',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 223,
                name: 'Anim Pakal, Thousandth Moon',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 224,
                name: 'Bartolomé del Presidio',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 225,
                name: 'The Belligerent',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R,U',
            },
            {
                cardNumber: 226,
                name: 'Caparocti Sunborn',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 227,
                name: 'Captain Storm, Cosmium Raider',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 228,
                name: 'Deepfathom Echo',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 229,
                name: "Gishath, Sun's Avatar",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,W',
            },
            {
                cardNumber: 230,
                name: 'Itzquinth, Firstborn of Gishath',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 231,
                name: 'Kellan, Daring Traveler // Journey On',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 232,
                name: 'Kutzil, Malamet Exemplar',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 233,
                name: "Master's Guide-Mural // Master's Manufactory",
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U,W',
            },
            {
                cardNumber: 234,
                name: 'Molten Collapse',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 235,
                name: 'The Mycotyrant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 236,
                name: 'Nicanzil, Current Conductor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 237,
                name: "Palani's Hatcher",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 238,
                name: 'Quintorius Kand',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R,W',
            },
            {
                cardNumber: 239,
                name: "Saheeli, the Sun's Brilliance",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 240,
                name: 'Sovereign Okinec Ahau',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 241,
                name: 'Squirming Emergence',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 242,
                name: 'Uchbenbak, the Great Mistake',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 243,
                name: 'Vito, Fanatic of Aclazotz',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 244,
                name: 'Wail of the Forgotten',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,U',
            },
            {
                cardNumber: 245,
                name: 'Zoyowa Lava-Tongue',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 246,
                name: 'Buried Treasure',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 247,
                name: 'Careening Mine Cart',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 248,
                name: "Cartographer's Companion",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 249,
                name: 'Chimil, the Inner Sun',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 250,
                name: 'Compass Gnome',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 251,
                name: 'Contested Game Ball',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 252,
                name: 'Digsite Conservator',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 253,
                name: 'Disruptor Wanderglyph',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 254,
                name: 'Hoverstone Pilgrim',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 255,
                name: "Hunter's Blowgun",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 256,
                name: 'Matzalantli, the Great Door // The Core',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 257,
                name: 'The Millennium Calendar',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 258,
                name: 'Roaming Throne',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 259,
                name: 'Runaway Boulder',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Scampering Surveyor',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'Sorcerous Spyglass',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'Sunbird Standard // Sunbird Effigy',
                rarity: 'U',
                layout: 'transform',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 263,
                name: "Swashbuckler's Whip",
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 264,
                name: "Tarrian's Soulcleaver",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Threefold Thunderhulk',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 266,
                name: 'Throne of the Grim Captain // The Grim Captain',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Treasure Map // Treasure Cove',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Captivating Cave',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Cavern of Souls',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Cavernous Maw',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Echoing Deeps',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Forgotten Monument',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Hidden Cataract',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'Hidden Courtyard',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Hidden Necropolis',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Hidden Nursery',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Hidden Volcano',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Pit of Offerings',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 279,
                name: 'Promising Vein',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 280,
                name: 'Restless Anchorage',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 281,
                name: 'Restless Prairie',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Restless Reef',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 283,
                name: 'Restless Ridgeline',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 284,
                name: 'Restless Vents',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 285,
                name: 'Sunken Citadel',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 286,
                name: 'Volatile Fault',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 287,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 288,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 289,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 290,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 291,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 292,
                name: 'Akal Pakal, First Among Equals',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 293,
                name: 'Malcolm, Alluring Scoundrel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 294,
                name: 'Breeches, Eager Pillager',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 295,
                name: 'Inti, Seneschal of the Sun',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 296,
                name: 'Huatli, Poet of Unity // Roar of the Fifth People',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 297,
                name: 'Abuelo, Ancestral Echo',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 298,
                name: 'Akawalli, the Seething Tower',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 299,
                name: 'Amalia Benavides Aguirre',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 300,
                name: 'Anim Pakal, Thousandth Moon',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 301,
                name: 'Bartolomé del Presidio',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 302,
                name: 'Caparocti Sunborn',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 303,
                name: 'Captain Storm, Cosmium Raider',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 304,
                name: 'Kutzil, Malamet Exemplar',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 305,
                name: 'The Mycotyrant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 306,
                name: 'Nicanzil, Current Conductor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 307,
                name: 'Quintorius Kand',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R,W',
            },
            {
                cardNumber: 308,
                name: "Saheeli, the Sun's Brilliance",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 309,
                name: 'Sovereign Okinec Ahau',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 310,
                name: 'Uchbenbak, the Great Mistake',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 311,
                name: 'Vito, Fanatic of Aclazotz',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 312,
                name: 'Zoyowa Lava-Tongue',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 313,
                name: 'Throne of the Grim Captain // The Grim Captain',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 314,
                name: 'Ojer Taq, Deepest Foundation // Temple of Civilization',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 315,
                name: 'Ojer Pakpatiq, Deepest Epoch // Temple of Cyclical Time',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 316,
                name: 'Aclazotz, Deepest Betrayal // Temple of the Dead',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 317,
                name: 'Ojer Axonil, Deepest Might // Temple of Power',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 318,
                name: 'Ojer Kaslem, Deepest Growth // Temple of Cultivation',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 319,
                name: 'The Ancient One',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 320,
                name: 'Belligerent Yearling',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 321,
                name: 'Bonehoard Dracosaur',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 322,
                name: 'Rampaging Ceratops',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 323,
                name: 'Scytheclaw Raptor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 324,
                name: 'Trumpeting Carnosaur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 325,
                name: 'Earthshaker Dreadmaw',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 326,
                name: 'Ghalta, Stampede Tyrant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 327,
                name: 'Hulking Raptor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 328,
                name: 'Pugnacious Hammerskull',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 329,
                name: 'Thrashing Brontodon',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 330,
                name: "Gishath, Sun's Avatar",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,W',
            },
            {
                cardNumber: 331,
                name: 'Itzquinth, Firstborn of Gishath',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 332,
                name: "Palani's Hatcher",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 333,
                name: 'Get Lost',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 334,
                name: 'Resplendent Angel',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 335,
                name: "Tishana's Tidebinder",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 336,
                name: 'Bloodletter of Aclazotz',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 337,
                name: 'Bringer of the Last Gift',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 338,
                name: 'Starving Revenant',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 339,
                name: 'Huatli, Poet of Unity // Roar of the Fifth People',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 340,
                name: 'The Skullspore Nexus',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 341,
                name: 'Kellan, Daring Traveler // Journey On',
                rarity: 'R',
                layout: 'adventure',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 342,
                name: 'Molten Collapse',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 343,
                name: 'Wail of the Forgotten',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,U',
            },
            {
                cardNumber: 344,
                name: 'Roaming Throne',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 345,
                name: 'Cavern of Souls',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 346,
                name: 'Echoing Deeps',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 347,
                name: 'Restless Anchorage',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 348,
                name: 'Restless Prairie',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 349,
                name: 'Restless Reef',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 350,
                name: 'Restless Ridgeline',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 351,
                name: 'Restless Vents',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 352,
                name: 'Quintorius Kand',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R,W',
            },
            {
                cardNumber: 353,
                name: "Abuelo's Awakening",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 354,
                name: 'Fabrication Foundry',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 355,
                name: "Kutzil's Flanker",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 356,
                name: 'Sanguine Evangelist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 357,
                name: 'Thousand Moons Smithy // Barracks of the Thousand',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 358,
                name: 'Unstable Glyphbridge // Sandswirl Wanderglyph',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 359,
                name: 'Warden of the Inner Sky',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 360,
                name: 'Braided Net // Braided Quipu',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 361,
                name: 'Deeproot Pilgrimage',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 362,
                name: 'The Enigma Jewel // Locus of Enlightenment',
                rarity: 'M',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 363,
                name: 'The Everflowing Well // The Myriad Pools',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 364,
                name: 'Kitesail Larcenist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 365,
                name: 'Subterranean Schooner',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 366,
                name: 'Corpses of the Lost',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 367,
                name: 'Preacher of the Schism',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 368,
                name: "Queen's Bay Paladin",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 369,
                name: 'Souls of the Lost',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 370,
                name: 'Stalactite Stalker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 371,
                name: "Tarrian's Journal // The Tomb of Aclazotz",
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 372,
                name: 'Terror Tide',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 373,
                name: "Brass's Tunnel-Grinder // Tecutlan, the Searing Rift",
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 374,
                name: 'Dire Flail // Dire Blunderbuss',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 375,
                name: 'Hit the Mother Lode',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 376,
                name: 'Magmatic Galleon',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 377,
                name: 'Poetic Ingenuity',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 378,
                name: 'Bedrock Tortoise',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 379,
                name: 'Cosmium Confluence',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 380,
                name: 'Growing Rites of Itlimoc // Itlimoc, Cradle of the Sun',
                rarity: 'R',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 381,
                name: 'Intrepid Paleontologist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 382,
                name: 'Jadelight Spelunker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 383,
                name: 'Sentinel of the Nameless City',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 384,
                name: 'The Belligerent',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R,U',
            },
            {
                cardNumber: 385,
                name: 'Deepfathom Echo',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 386,
                name: 'Squirming Emergence',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 387,
                name: 'Matzalantli, the Great Door // The Core',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 388,
                name: 'The Millennium Calendar',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 389,
                name: "Tarrian's Soulcleaver",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 390,
                name: 'Threefold Thunderhulk',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 391,
                name: 'Treasure Map // Treasure Cove',
                rarity: 'R',
                layout: 'transform',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 392,
                name: 'Sunken Citadel',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 393,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 394,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 395,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 396,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 397,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 398,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 399,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 400,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 401,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 402,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 403,
                name: 'Jadelight Spelunker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 404,
                name: 'Hit the Mother Lode',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 405,
                name: 'Spyglass Siren',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 406,
                name: 'Deep-Cavern Bat',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 407,
                name: 'Geological Appraiser',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 408,
                name: 'Cenote Scout',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 409,
                name: 'Bartolomé del Presidio',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 410,
                name: 'Cavern of Souls',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'The Lost Caverns of Ixalan',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
