import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addBlb1721572106554 implements MigrationInterface {
    shortName = 'BLB';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Banishing Light',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 2,
                name: 'Beza, the Bounding Spring',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 3,
                name: 'Brave-Kin Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'Brightblade Stoat',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: "Builder's Talent",
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: "Caretaker's Talent",
                rarity: 'R',
                layout: 'class',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Carrot Cake',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Crumb and Get It',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: "Dawn's Truce",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Dewdrop Cure',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Driftgloom Coyote',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Essence Channeler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Feather of Flight',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Flowerfoot Swordmaster',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Harvestrite Host',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Hop to It',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Intrepid Rabbit',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Jackdaw Savior',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: 'Jolly Gerbils',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Lifecreed Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: "Mabel's Mettle",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Mouse Trapper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'Nettle Guard',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'Parting Gust',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Pileated Provisioner',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Rabbit Response',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: 'Repel Calamity',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Salvation Swan',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: 'Season of the Burrow',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Seasoned Warrenguard',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Shrike Force',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Sonar Strike',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: 'Star Charter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: 'Starfall Invocation',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: 'Thistledown Players',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: 'Valley Questcaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Warren Elder',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Warren Warleader',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 39,
                name: 'Wax-Wane Witness',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 40,
                name: 'Whiskervale Forerunner',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 41,
                name: 'Azure Beastbinder',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 42,
                name: 'Bellowing Crier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 43,
                name: 'Calamitous Tide',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 44,
                name: 'Daring Waverider',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 45,
                name: 'Dazzling Denial',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 46,
                name: 'Dire Downdraft',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Dour Port-Mage',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Eddymurk Crab',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Eluge, the Shoreless Sea',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Finch Formation',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: "Gossip's Talent",
                rarity: 'U',
                layout: 'class',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: 'Into the Flood Maw',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Kitnap',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Kitsa, Otterball Elite',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: 'Knightfisher',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'Lightshell Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Long River Lurker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: "Long River's Pull",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Mind Spiral',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Mindwhisker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: 'Mockingbird',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Nightwhorl Hermit',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: 'Otterball Antics',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'Pearl of Wisdom',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: 'Plumecreed Escort',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: 'Portent of Calamity',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Run Away Together',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: 'Season of Weaving',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Shore Up',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Shoreline Looter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: 'Skyskipper Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'Spellgyre',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 73,
                name: 'Splash Lasher',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Splash Portal',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: "Stormchaser's Talent",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Sugar Coat',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'Thought Shucker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Thundertrap Trainer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 79,
                name: 'Valley Floodcaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 80,
                name: 'Waterspout Warden',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 81,
                name: 'Wishing Well',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 82,
                name: 'Agate-Blade Assassin',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 83,
                name: "Bandit's Talent",
                rarity: 'U',
                layout: 'class',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 84,
                name: 'Bonebind Orator',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 85,
                name: 'Bonecache Overseer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 86,
                name: 'Coiling Rebirth',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 87,
                name: 'Consumed by Greed',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 88,
                name: "Cruelclaw's Heist",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 89,
                name: 'Daggerfang Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 90,
                name: 'Darkstar Augur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: 'Diresight',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: 'Downwind Ambusher',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Early Winter',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'Feed the Cycle',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Fell',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Glidedive Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: "Hazel's Nocturne",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'Huskburster Swarm',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Iridescent Vinelasher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Maha, Its Feathers Night',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Moonstone Harbinger',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Nocturnal Hunger',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Osteomancer Adept',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: 'Persistent Marshstalker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Psychic Whorl',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'Ravine Raider',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 107,
                name: 'Rottenmouth Viper',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 108,
                name: 'Ruthless Negotiation',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 109,
                name: 'Savor',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 110,
                name: 'Scales of Shale',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 111,
                name: "Scavenger's Talent",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 112,
                name: 'Season of Loss',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 113,
                name: 'Sinister Monolith',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 114,
                name: 'Stargaze',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 115,
                name: 'Starlit Soothsayer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 116,
                name: 'Starscape Cleric',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 117,
                name: 'Thornplate Intimidator',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 118,
                name: 'Thought-Stalker Warlock',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 119,
                name: 'Valley Rotcaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 120,
                name: 'Wick, the Whorled Mind',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 121,
                name: "Wick's Patrol",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 122,
                name: 'Agate Assault',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 123,
                name: "Alania's Pathmaker",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 124,
                name: "Artist's Talent",
                rarity: 'R',
                layout: 'class',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 125,
                name: "Blacksmith's Talent",
                rarity: 'U',
                layout: 'class',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 126,
                name: 'Blooming Blast',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 127,
                name: 'Brambleguard Captain',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 128,
                name: 'Brazen Collector',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 129,
                name: 'Byway Barterer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 130,
                name: 'Conduct Electricity',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 131,
                name: 'Coruscation Mage',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 132,
                name: "Dragonhawk, Fate's Tempest",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 133,
                name: 'Emberheart Challenger',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 134,
                name: 'Festival of Embers',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 135,
                name: 'Flamecache Gecko',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 136,
                name: 'Frilled Sparkshooter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 137,
                name: 'Harnesser of Storms',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 138,
                name: 'Heartfire Hero',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 139,
                name: 'Hearthborn Battler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 140,
                name: 'Hired Claw',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 141,
                name: "Hoarder's Overflow",
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 142,
                name: 'Kindlespark Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 143,
                name: 'Manifold Mouse',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 144,
                name: 'Might of the Meek',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 145,
                name: 'Playful Shove',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 146,
                name: 'Quaketusk Boar',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 147,
                name: 'Rabid Gnaw',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 148,
                name: 'Raccoon Rallier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 149,
                name: 'Reptilian Recruiter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 150,
                name: 'Roughshod Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: "Sazacap's Brew",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Season of the Bold',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: 'Steampath Charger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: 'Stormsplitter',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: 'Sunspine Lynx',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Take Out the Trash',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 157,
                name: 'Teapot Slinger',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 158,
                name: 'Valley Flamecaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 159,
                name: 'Valley Rally',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 160,
                name: 'War Squeak',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 161,
                name: 'Whiskerquill Scribe',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 162,
                name: 'Wildfire Howl',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 163,
                name: 'Bakersbane Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 164,
                name: 'Bark-Knuckle Boxer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 165,
                name: 'Brambleguard Veteran',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 166,
                name: 'Bushy Bodyguard',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 167,
                name: 'Cache Grab',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 168,
                name: 'Clifftop Lookout',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 169,
                name: 'Curious Forager',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 170,
                name: 'Druid of the Spade',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 171,
                name: 'Fecund Greenshell',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 172,
                name: 'For the Common Good',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 173,
                name: 'Galewind Moose',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 174,
                name: 'Hazardroot Herbalist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 175,
                name: 'Heaped Harvest',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 176,
                name: 'High Stride',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 177,
                name: 'Hivespine Wolverine',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 178,
                name: 'Honored Dreyleader',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 179,
                name: "Hunter's Talent",
                rarity: 'U',
                layout: 'class',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 180,
                name: "Innkeeper's Talent",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 181,
                name: 'Keen-Eyed Curator',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 182,
                name: 'Longstalk Brawl',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 183,
                name: 'Lumra, Bellow of the Woods',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 184,
                name: 'Mistbreath Elder',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 185,
                name: 'Overprotect',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: 'Pawpatch Formation',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Pawpatch Recruit',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Peerless Recycling',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Polliwallop',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: 'Rust-Shield Rampager',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Scrapshooter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 192,
                name: 'Season of Gathering',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 193,
                name: 'Stickytongue Sentinel',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 194,
                name: 'Stocking the Pantry',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 195,
                name: 'Sunshower Druid',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 196,
                name: 'Tender Wildguide',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 197,
                name: 'Thornvault Forager',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 198,
                name: 'Three Tree Rootweaver',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 199,
                name: 'Three Tree Scribe',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 200,
                name: 'Treeguard Duo',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 201,
                name: 'Treetop Sentries',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 202,
                name: 'Valley Mightcaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 203,
                name: 'Wear Down',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 204,
                name: 'Alania, Divergent Storm',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 205,
                name: 'Baylen, the Haymaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,W',
            },
            {
                cardNumber: 206,
                name: 'Burrowguard Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 207,
                name: 'Camellia, the Seedmiser',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 208,
                name: 'Cindering Cutthroat',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 209,
                name: 'Clement, the Worrywort',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 210,
                name: 'Corpseberry Cultivator',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 211,
                name: 'Dreamdew Entrancer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 212,
                name: 'Finneas, Ace Archer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 213,
                name: 'Fireglass Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 214,
                name: 'Gev, Scaled Scorch',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 215,
                name: "Glarb, Calamity's Augur",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U',
            },
            {
                cardNumber: 216,
                name: 'Head of the Homestead',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 217,
                name: 'Helga, Skittish Seer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U,W',
            },
            {
                cardNumber: 218,
                name: 'Hugs, Grisly Guardian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 219,
                name: 'The Infamous Cruelclaw',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 220,
                name: 'Junkblade Bruiser',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 221,
                name: 'Kastral, the Windcrested',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 222,
                name: 'Lilysplash Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 223,
                name: 'Lunar Convocation',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B,W',
            },
            {
                cardNumber: 224,
                name: 'Mabel, Heir to Cragflame',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 225,
                name: 'Mind Drill Assailant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 226,
                name: 'Moonrise Cleric',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 227,
                name: 'Muerra, Trash Tactician',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 228,
                name: 'Plumecreed Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 229,
                name: 'Pond Prophet',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 230,
                name: 'Ral, Crackling Wit',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R,U',
            },
            {
                cardNumber: 231,
                name: 'Seedglaive Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 232,
                name: 'Seedpod Squire',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 233,
                name: 'Starseer Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 234,
                name: 'Stormcatch Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 235,
                name: 'Tempest Angler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 236,
                name: 'Tidecaller Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 237,
                name: 'Veteran Guardmouse',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 238,
                name: 'Vinereap Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 239,
                name: 'Vren, the Relentless',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 240,
                name: 'Wandertale Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 241,
                name: 'Ygra, Eater of All',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 242,
                name: 'Zoraline, Cosmos Caller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 243,
                name: 'Barkform Harvester',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 244,
                name: "Bumbleflower's Sharepot",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 245,
                name: 'Fountainport Bell',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 246,
                name: 'Heirloom Epic',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 247,
                name: 'Patchwork Banner',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 248,
                name: 'Short Bow',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 249,
                name: 'Starforged Sword',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 250,
                name: 'Tangle Tumbler',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 251,
                name: 'Three Tree Mascot',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 252,
                name: 'Fabled Passage',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 253,
                name: 'Fountainport',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 254,
                name: 'Hidden Grotto',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 255,
                name: 'Lilypad Village',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 256,
                name: 'Lupinflower Village',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 257,
                name: 'Mudflat Village',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 258,
                name: 'Oakhollow Village',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 259,
                name: 'Rockface Village',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Three Tree City',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'Uncharted Haven',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 263,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 264,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 266,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 279,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 280,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 281,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Season of the Burrow',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 283,
                name: 'Season of Weaving',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 284,
                name: 'Season of Loss',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 285,
                name: 'Season of the Bold',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 286,
                name: 'Season of Gathering',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 287,
                name: 'Beza, the Bounding Spring',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 288,
                name: 'Eluge, the Shoreless Sea',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 289,
                name: 'Maha, Its Feathers Night',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 290,
                name: 'Rottenmouth Viper',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 291,
                name: "Dragonhawk, Fate's Tempest",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 292,
                name: 'Sunspine Lynx',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 293,
                name: 'Lumra, Bellow of the Woods',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 294,
                name: 'Ygra, Eater of All',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 295,
                name: "Dawn's Truce",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 296,
                name: 'Jackdaw Savior',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 297,
                name: 'Salvation Swan',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 298,
                name: 'Starfall Invocation',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 299,
                name: 'Valley Questcaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 300,
                name: 'Warren Warleader',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 301,
                name: 'Whiskervale Forerunner',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 302,
                name: 'Azure Beastbinder',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 303,
                name: 'Dour Port-Mage',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 304,
                name: 'Kitsa, Otterball Elite',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 305,
                name: 'Mockingbird',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 306,
                name: 'Portent of Calamity',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 307,
                name: 'Thundertrap Trainer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 308,
                name: 'Valley Floodcaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 309,
                name: 'Coiling Rebirth',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 310,
                name: "Cruelclaw's Heist",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 311,
                name: 'Darkstar Augur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 312,
                name: 'Osteomancer Adept',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 313,
                name: 'Valley Rotcaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 314,
                name: 'Wick, the Whorled Mind',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 315,
                name: 'Emberheart Challenger',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 316,
                name: 'Festival of Embers',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 317,
                name: 'Hired Claw',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 318,
                name: 'Manifold Mouse',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 319,
                name: 'Stormsplitter',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 320,
                name: 'Valley Flamecaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 321,
                name: 'For the Common Good',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 322,
                name: 'Keen-Eyed Curator',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 323,
                name: 'Mistbreath Elder',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 324,
                name: 'Scrapshooter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 325,
                name: 'Tender Wildguide',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 326,
                name: 'Valley Mightcaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 327,
                name: 'Alania, Divergent Storm',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 328,
                name: 'Camellia, the Seedmiser',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 329,
                name: 'Clement, the Worrywort',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 330,
                name: 'Finneas, Ace Archer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 331,
                name: "Glarb, Calamity's Augur",
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U',
            },
            {
                cardNumber: 332,
                name: 'Helga, Skittish Seer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U,W',
            },
            {
                cardNumber: 333,
                name: 'Hugs, Grisly Guardian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 334,
                name: 'The Infamous Cruelclaw',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 335,
                name: 'Kastral, the Windcrested',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 336,
                name: 'Mabel, Heir to Cragflame',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 337,
                name: 'Three Tree City',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 338,
                name: 'Three Tree City',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 339,
                name: 'Three Tree City',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 340,
                name: 'Three Tree City',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 341,
                name: 'Ral, Crackling Wit',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R,U',
            },
            {
                cardNumber: 342,
                name: 'Lumra, Bellow of the Woods',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 343,
                name: 'Lumra, Bellow of the Woods',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 344,
                name: 'Alania, Divergent Storm',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 345,
                name: 'Baylen, the Haymaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,W',
            },
            {
                cardNumber: 346,
                name: 'Camellia, the Seedmiser',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 347,
                name: 'Clement, the Worrywort',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 348,
                name: 'Finneas, Ace Archer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 349,
                name: 'Gev, Scaled Scorch',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 350,
                name: 'Kastral, the Windcrested',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 351,
                name: 'Mabel, Heir to Cragflame',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 352,
                name: 'Muerra, Trash Tactician',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 353,
                name: 'Ral, Crackling Wit',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'R,U',
            },
            {
                cardNumber: 354,
                name: 'Vren, the Relentless',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 355,
                name: 'Zoraline, Cosmos Caller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 356,
                name: 'Essence Channeler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 357,
                name: 'Kitnap',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 358,
                name: 'Wishing Well',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 359,
                name: 'Iridescent Vinelasher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 360,
                name: 'Byway Barterer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 361,
                name: 'Hearthborn Battler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 362,
                name: 'Fecund Greenshell',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 363,
                name: 'Pawpatch Recruit',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 364,
                name: 'Thornvault Forager',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 365,
                name: 'Dreamdew Entrancer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 366,
                name: 'Lunar Convocation',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B,W',
            },
            {
                cardNumber: 367,
                name: 'Fabled Passage',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 368,
                name: 'Fountainport',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 369,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 370,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 371,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 372,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 373,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 374,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 375,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 376,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 377,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 378,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 379,
                name: 'Bria, Riptide Rogue',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 380,
                name: 'Byrke, Long Ear of the Law',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 381,
                name: 'Hop to It',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 382,
                name: 'Shoreline Looter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 383,
                name: 'Fell',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 384,
                name: 'Wear Down',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 385,
                name: 'Stormcatch Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 386,
                name: 'Thundertrap Trainer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 387,
                name: 'Serra Redeemer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 388,
                name: 'Charmed Sleep',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 389,
                name: 'Mind Spring',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 390,
                name: 'Thieving Otter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 391,
                name: 'Flame Lash',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 392,
                name: 'Colossification',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 393,
                name: 'Giant Growth',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 394,
                name: 'Rabid Bite',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 395,
                name: 'Sword of Vengeance',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 396,
                name: 'Blossoming Sands',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 397,
                name: 'Swiftwater Cliffs',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
        ];

        await MigrationHelper.cardSetUp(queryRunner, 'Bloomburrow', this.shortName, cardValues, [
            `id`,
            `cardNumber`,
            `name`,
            `rarity`,
            `layout`,
            `cardSet`,
            `colors`,
            `types`,
        ]);

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
