import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addEoe1753164600861 implements MigrationInterface {
    shortName = 'EOE';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Anticausal Vestige',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 2,
                name: 'Tezzeret, Cruel Captain',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: '',
            },
            {
                cardNumber: 3,
                name: 'All-Fates Stalker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'Astelli Reclaimer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'Auxiliary Boosters',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Banishing Light',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Beyond the Quiet',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Brightspear Zealot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Cosmogrand Zenith',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Dawnstrike Vanguard',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Dockworker Drone',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Dual-Sun Adepts',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Dual-Sun Technique',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Emergency Eject',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Exalted Sunborn',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Exosuit Savior',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Flight-Deck Coordinator',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Focus Fire',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: 'Haliya, Guided by Light',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Hardlight Containment',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: 'Honor',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Honored Knight-Captain',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'Knight Luminary',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'Lightstall Inquisitor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Lumen-Class Frigate',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Luxknight Breacher',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: 'Pinnacle Starcage',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Pulsar Squadron Ace',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: 'Radiant Strike',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Rayblade Trooper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Reroute Systems',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Rescue Skiff',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: 'Scout for Survivors',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: 'Seam Rip',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: 'The Seriema',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: "Squire's Lightblade",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Starfield Shepherd',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Starfighter Pilot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 39,
                name: 'Starport Security',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'W',
            },
            {
                cardNumber: 40,
                name: 'Sunstar Chaplain',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 41,
                name: 'Sunstar Expansionist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 42,
                name: 'Sunstar Lightsmith',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 43,
                name: 'Wedgelight Rammer',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 44,
                name: 'Weftblade Enhancer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 45,
                name: 'Zealous Display',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 46,
                name: 'Annul',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Atomic Microsizer',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Cerebral Download',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Cloudsculpt Technician',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Codecracker Hound',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: 'Consult the Star Charts',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: 'Cryogen Relic',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Cryoshatter',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Desculpting Blast',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: 'Divert Disaster',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'Emissary Escort',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Gigastorm Titan',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: 'Illvoi Galeblade',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Illvoi Infiltrator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Illvoi Light Jammer',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: 'Illvoi Operative',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Lost in Space',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: 'Mechan Assembler',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'Mechan Navigator',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: 'Mechan Shieldmate',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: 'Mechanozoa',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Mental Modulation',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: "Mm'menon, the Right Hand",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Moonlit Meditation',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Mouth of the Storm',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: 'Nanoform Sentinel',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'Quantum Riddler',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 73,
                name: 'Scour for Scrap',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Selfcraft Mechan',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: 'Sinister Cryologist',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Specimen Freighter',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'Starbreach Whale',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Starfield Vocalist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 79,
                name: 'Starwinder',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 80,
                name: 'Steelswarm Operator',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 81,
                name: 'Synthesizer Labship',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 82,
                name: 'Tractor Beam',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 83,
                name: 'Unravel',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 84,
                name: 'Uthros Psionicist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 85,
                name: 'Uthros Scanship',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 86,
                name: 'Weftwalking',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 87,
                name: 'Alpharael, Stonechosen',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 88,
                name: "Archenemy's Charm",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 89,
                name: 'Beamsaw Prospector',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 90,
                name: 'Blade of the Swarm',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: 'Chorale of the Void',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: 'Comet Crawler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Dark Endurance',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'Decode Transmissions',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Depressurize',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Dubious Delicacy',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: 'Elegy Acolyte',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'Embrace Oblivion',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Entropic Battlecruiser',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: "Faller's Faithful",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Fell Gravship',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Gravblade Heavy',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Gravkill',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: 'Gravpack Monoist',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Hullcarver',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'Hylderblade',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 107,
                name: 'Hymn of the Faller',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 108,
                name: 'Insatiable Skittermaw',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 109,
                name: 'Lightless Evangel',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 110,
                name: 'Monoist Circuit-Feeder',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'B',
            },
            {
                cardNumber: 111,
                name: 'Monoist Sentry',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'B',
            },
            {
                cardNumber: 112,
                name: 'Perigee Beckoner',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 113,
                name: 'Requiem Monolith',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 114,
                name: 'Scrounge for Eternity',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 115,
                name: 'Sothera, the Supervoid',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 116,
                name: 'Sunset Saboteur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 117,
                name: 'Susurian Dirgecraft',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 118,
                name: 'Susurian Voidborn',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 119,
                name: 'Swarm Culler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 120,
                name: 'Temporal Intervention',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 121,
                name: 'Timeline Culler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 122,
                name: 'Tragic Trajectory',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 123,
                name: 'Umbral Collar Zealot',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 124,
                name: 'Virus Beetle',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'B',
            },
            {
                cardNumber: 125,
                name: 'Voidforged Titan',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'B',
            },
            {
                cardNumber: 126,
                name: 'Vote Out',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 127,
                name: 'Xu-Ifit, Osteoharmonist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 128,
                name: 'Zero Point Ballad',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 129,
                name: 'Bombard',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 130,
                name: 'Cut Propulsion',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 131,
                name: 'Debris Field Crusher',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 132,
                name: 'Devastating Onslaught',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 133,
                name: 'Drill Too Deep',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 134,
                name: 'Frontline War-Rager',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 135,
                name: 'Full Bore',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 136,
                name: 'Galvanizing Sawship',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 137,
                name: 'Invasive Maneuvers',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 138,
                name: 'Kav Landseeker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 139,
                name: 'Kavaron Harrier',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 140,
                name: 'Kavaron Skywarden',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 141,
                name: 'Kavaron Turbodrone',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 142,
                name: 'Lithobraking',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 143,
                name: 'Melded Moxite',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 144,
                name: 'Memorial Team Leader',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 145,
                name: 'Memorial Vault',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 146,
                name: 'Molecular Modifier',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 147,
                name: 'Nebula Dragon',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 148,
                name: 'Nova Hellkite',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 149,
                name: 'Orbital Plunge',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 150,
                name: 'Oreplate Pangolin',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: 'Pain for All',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Plasma Bolt',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: 'Possibility Technician',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: 'Red Tiger Mechan',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: 'Remnant Elemental',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Rig for War',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 157,
                name: 'Roving Actuator',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 158,
                name: 'Ruinous Rampage',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 159,
                name: 'Rust Harvester',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 160,
                name: 'Slagdrill Scrapper',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 161,
                name: 'Systems Override',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 162,
                name: 'Tannuk, Steadfast Second',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 163,
                name: 'Terminal Velocity',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 164,
                name: 'Terrapact Intimidator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 165,
                name: 'Territorial Bruntar',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 166,
                name: 'Vaultguard Trooper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 167,
                name: 'Warmaker Gunship',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 168,
                name: 'Weapons Manufacturing',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 169,
                name: 'Weftstalker Ardent',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 170,
                name: 'Zookeeper Mechan',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 171,
                name: 'Atmospheric Greenhouse',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 172,
                name: 'Bioengineered Future',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 173,
                name: 'Biosynthic Burst',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 174,
                name: 'Blooming Stinger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 175,
                name: 'Broodguard Elite',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 176,
                name: 'Close Encounter',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 177,
                name: 'Diplomatic Relations',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 178,
                name: 'Drix Fatemaker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 179,
                name: 'Edge Rover',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'G',
            },
            {
                cardNumber: 180,
                name: 'Eumidian Terrabotanist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 181,
                name: 'Eusocial Engineering',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 182,
                name: 'Famished Worldsire',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 183,
                name: 'Frenzied Baloth',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 184,
                name: 'Fungal Colossus',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 185,
                name: 'Galactic Wayfarer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: 'Gene Pollinator',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Germinating Wurm',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Glacier Godmaw',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Harmonious Grovestrider',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: 'Hemosymbic Mite',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Icecave Crasher',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 192,
                name: 'Icetill Explorer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 193,
                name: 'Intrepid Tenderfoot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 194,
                name: 'Larval Scoutlander',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 195,
                name: 'Lashwhip Predator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 196,
                name: 'Loading Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 197,
                name: 'Meltstrider Eulogist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 198,
                name: "Meltstrider's Gear",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 199,
                name: "Meltstrider's Resolve",
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 200,
                name: 'Mightform Harmonizer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 201,
                name: 'Ouroboroid',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 202,
                name: 'Pull Through the Weft',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 203,
                name: "Sami's Curiosity",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 204,
                name: 'Seedship Agrarian',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 205,
                name: 'Seedship Impact',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 206,
                name: 'Shattered Wings',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 207,
                name: 'Skystinger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 208,
                name: 'Sledge-Class Seedship',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 209,
                name: 'Tapestry Warden',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'G',
            },
            {
                cardNumber: 210,
                name: 'Terrasymbiosis',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 211,
                name: 'Thawbringer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 212,
                name: 'Alpharael, Dreaming Acolyte',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 213,
                name: 'Biomechan Engineer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 214,
                name: 'Biotech Specialist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 215,
                name: 'Cosmogoyf',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 216,
                name: 'Dyadrine, Synthesis Amalgam',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 217,
                name: 'Genemorph Imago',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 218,
                name: 'Haliya, Ascendant Cadet',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 219,
                name: 'Infinite Guideline Station',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 220,
                name: 'Interceptor Mechan',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 221,
                name: "Mm'menon, Uthros Exile",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 222,
                name: 'Mutinous Massacre',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 223,
                name: 'Pinnacle Emissary',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 224,
                name: 'Ragost, Deft Gastronaut',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 225,
                name: "Sami, Ship's Engineer",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 226,
                name: 'Sami, Wildcat Captain',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 227,
                name: 'Seedship Broodtender',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 228,
                name: 'Singularity Rupture',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,U',
            },
            {
                cardNumber: 229,
                name: 'Space-Time Anomaly',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U,W',
            },
            {
                cardNumber: 230,
                name: 'Station Monitor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 231,
                name: 'Syr Vondam, Sunstar Exemplar',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 232,
                name: 'Syr Vondam, the Lucent',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 233,
                name: 'Tannuk, Memorial Ensign',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 234,
                name: 'All-Fates Scroll',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 235,
                name: 'Bygone Colossus',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 236,
                name: 'Chrome Companion',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 237,
                name: 'Dauntless Scrapbot',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 238,
                name: 'Dawnsire, Sunstar Dreadnought',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 239,
                name: 'The Dominion Bracelet',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 240,
                name: 'The Endstone',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 241,
                name: 'The Eternity Elevator',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 242,
                name: 'Extinguisher Battleship',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 243,
                name: 'Nutrient Block',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 244,
                name: 'Pinnacle Kill-Ship',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 245,
                name: 'Survey Mechan',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 246,
                name: 'Thaumaton Torpedo',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 247,
                name: 'Thrumming Hivepool',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 248,
                name: 'Virulent Silencer',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 249,
                name: 'Wurmwall Sweeper',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 250,
                name: 'Adagia, Windswept Bastion',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 251,
                name: 'Breeding Pool',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 252,
                name: 'Command Bridge',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 253,
                name: 'Evendo, Waking Haven',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 254,
                name: 'Godless Shrine',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 255,
                name: 'Kavaron, Memorial World',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 256,
                name: 'Sacred Foundry',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 257,
                name: 'Secluded Starforge',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 258,
                name: 'Stomping Ground',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 259,
                name: 'Susur Secundi, Void Altar',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Uthros, Titanic Godcore',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'Watery Grave',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 263,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 264,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 266,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Adagia, Windswept Bastion',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Breeding Pool',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 279,
                name: 'Evendo, Waking Haven',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 280,
                name: 'Godless Shrine',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 281,
                name: 'Kavaron, Memorial World',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Sacred Foundry',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 283,
                name: 'Stomping Ground',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 284,
                name: 'Susur Secundi, Void Altar',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 285,
                name: 'Uthros, Titanic Godcore',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 286,
                name: 'Watery Grave',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 287,
                name: 'Tezzeret, Cruel Captain',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: '',
            },
            {
                cardNumber: 288,
                name: 'Astelli Reclaimer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 289,
                name: 'Haliya, Guided by Light',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 290,
                name: "Mm'menon, the Right Hand",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 291,
                name: 'Starwinder',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 292,
                name: 'Alpharael, Stonechosen',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 293,
                name: 'Elegy Acolyte',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 294,
                name: 'Xu-Ifit, Osteoharmonist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 295,
                name: 'Possibility Technician',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 296,
                name: 'Tannuk, Steadfast Second',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 297,
                name: 'Mightform Harmonizer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 298,
                name: 'Dyadrine, Synthesis Amalgam',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 299,
                name: 'Genemorph Imago',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 300,
                name: 'Ragost, Deft Gastronaut',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 301,
                name: 'Sami, Wildcat Captain',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 302,
                name: 'Syr Vondam, Sunstar Exemplar',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 303,
                name: 'Beyond the Quiet',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 304,
                name: 'Cosmogrand Zenith',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 305,
                name: 'Quantum Riddler',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 306,
                name: 'Starwinder',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 307,
                name: "Archenemy's Charm",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 308,
                name: 'Devastating Onslaught',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 309,
                name: 'Nova Hellkite',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 310,
                name: 'Rust Harvester',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 311,
                name: 'Weapons Manufacturing',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 312,
                name: 'Terrasymbiosis',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 313,
                name: 'Cosmogoyf',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 314,
                name: 'Mutinous Massacre',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 315,
                name: 'Space-Time Anomaly',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U,W',
            },
            {
                cardNumber: 316,
                name: 'Secluded Starforge',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 317,
                name: 'Anticausal Vestige',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 318,
                name: 'Exalted Sunborn',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 319,
                name: 'Hardlight Containment',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 320,
                name: 'Lightstall Inquisitor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 321,
                name: 'Lumen-Class Frigate',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 322,
                name: 'Pinnacle Starcage',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 323,
                name: 'The Seriema',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 324,
                name: 'Sunstar Chaplain',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 325,
                name: 'Consult the Star Charts',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 326,
                name: 'Emissary Escort',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 327,
                name: 'Moonlit Meditation',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 328,
                name: 'Starfield Vocalist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 329,
                name: 'Synthesizer Labship',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 330,
                name: 'Weftwalking',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 331,
                name: 'Chorale of the Void',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 332,
                name: 'Entropic Battlecruiser',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 333,
                name: 'Requiem Monolith',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 334,
                name: 'Sunset Saboteur',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 335,
                name: 'Zero Point Ballad',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 336,
                name: 'Memorial Vault',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 337,
                name: 'Pain for All',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 338,
                name: 'Terminal Velocity',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 339,
                name: 'Warmaker Gunship',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 340,
                name: 'Bioengineered Future',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 341,
                name: 'Famished Worldsire',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 342,
                name: 'Frenzied Baloth',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 343,
                name: 'Icetill Explorer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 344,
                name: 'Loading Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 345,
                name: 'Ouroboroid',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 346,
                name: 'Sledge-Class Seedship',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 347,
                name: 'Biotech Specialist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 348,
                name: 'Infinite Guideline Station',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 349,
                name: 'Pinnacle Emissary',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 350,
                name: 'Singularity Rupture',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,U',
            },
            {
                cardNumber: 351,
                name: 'Dawnsire, Sunstar Dreadnought',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 352,
                name: 'The Dominion Bracelet',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 353,
                name: 'The Endstone',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 354,
                name: 'The Eternity Elevator',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 355,
                name: 'Extinguisher Battleship',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 356,
                name: 'Thrumming Hivepool',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 357,
                name: 'Anticausal Vestige',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 358,
                name: 'Exalted Sunborn',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 359,
                name: 'Starfield Vocalist',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 360,
                name: 'Sothera, the Supervoid',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 361,
                name: 'Devastating Onslaught',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 362,
                name: 'Icetill Explorer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 363,
                name: 'Mutinous Massacre',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 364,
                name: 'The Dominion Bracelet',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 365,
                name: 'The Endstone',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 366,
                name: 'Secluded Starforge',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 367,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 368,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 369,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 370,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 371,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 372,
                name: 'Adagia, Windswept Bastion',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 373,
                name: 'Breeding Pool',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 374,
                name: 'Evendo, Waking Haven',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 375,
                name: 'Godless Shrine',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 376,
                name: 'Kavaron, Memorial World',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 377,
                name: 'Sacred Foundry',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 378,
                name: 'Stomping Ground',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 379,
                name: 'Susur Secundi, Void Altar',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 380,
                name: 'Uthros, Titanic Godcore',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 381,
                name: 'Watery Grave',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 382,
                name: 'Sothera, the Supervoid',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 383,
                name: 'Anticausal Vestige',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 384,
                name: 'Exalted Sunborn',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 385,
                name: 'Starfield Vocalist',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 386,
                name: 'Sothera, the Supervoid',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 387,
                name: 'Devastating Onslaught',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 388,
                name: 'Icetill Explorer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 389,
                name: 'Mutinous Massacre',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 390,
                name: 'The Dominion Bracelet',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 391,
                name: 'The Endstone',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 392,
                name: 'Secluded Starforge',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 393,
                name: 'Starfield Shepherd',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 394,
                name: 'Annul',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 395,
                name: 'Umbral Collar Zealot',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 396,
                name: 'Kavaron Harrier',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R',
            },
            {
                cardNumber: 397,
                name: 'Pull Through the Weft',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 398,
                name: 'Singularity Rupture',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,U',
            },
            {
                cardNumber: 399,
                name: 'Emissary Escort',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'Edge of Eternities',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
