import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addEos1753167298767 implements MigrationInterface {
    shortName = 'EOS';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Ancient Tomb',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 2,
                name: 'Blast Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 3,
                name: 'Blinkmoth Nexus',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 4,
                name: "Bonders' Enclave",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 5,
                name: 'Cascading Cataracts',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 6,
                name: 'Cathedral of War',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 7,
                name: 'Celestial Colonnade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 8,
                name: 'Contested War Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 9,
                name: 'Creeping Tar Pit',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 10,
                name: 'Crystal Quarry',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 11,
                name: 'Deserted Temple',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 12,
                name: 'Dust Bowl',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 13,
                name: 'Echoing Deeps',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 14,
                name: 'Eldrazi Temple',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 15,
                name: 'Endless Sands',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 16,
                name: 'Gemstone Caverns',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 17,
                name: 'Grove of the Burnwillows',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 18,
                name: 'High Market',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 19,
                name: 'Hissing Quagmire',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 20,
                name: 'Inkmoth Nexus',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 21,
                name: "Inventors' Fair",
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 22,
                name: 'Lavaclaw Reaches',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 23,
                name: 'Lotus Field',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 24,
                name: 'Lumbering Falls',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 25,
                name: 'Mana Confluence',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 26,
                name: 'Meteor Crater',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 27,
                name: 'Mirrorpool',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 28,
                name: 'Mutavault',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 29,
                name: 'Mystifying Maze',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 30,
                name: 'Needle Spires',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 31,
                name: 'Nesting Grounds',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 32,
                name: 'Petrified Field',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 33,
                name: 'Plaza of Heroes',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 34,
                name: 'Power Depot',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Land',
                colors: '',
            },
            {
                cardNumber: 35,
                name: 'Raging Ravine',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 36,
                name: 'Reflecting Pool',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 37,
                name: 'Scavenger Grounds',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 38,
                name: 'Shambling Vent',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 39,
                name: 'Stirring Wildwood',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 40,
                name: 'Strip Mine',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 41,
                name: 'Sunken Citadel',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 42,
                name: 'Swarmyard',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 43,
                name: 'Terrain Generator',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 44,
                name: "Thespian's Stage",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 45,
                name: 'Wandering Fumarole',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 46,
                name: 'Ancient Tomb',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 47,
                name: 'Blast Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 48,
                name: 'Blinkmoth Nexus',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 49,
                name: "Bonders' Enclave",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 50,
                name: 'Cascading Cataracts',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 51,
                name: 'Cathedral of War',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 52,
                name: 'Celestial Colonnade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 53,
                name: 'Contested War Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 54,
                name: 'Creeping Tar Pit',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 55,
                name: 'Crystal Quarry',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 56,
                name: 'Deserted Temple',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 57,
                name: 'Dust Bowl',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 58,
                name: 'Echoing Deeps',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 59,
                name: 'Eldrazi Temple',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 60,
                name: 'Endless Sands',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 61,
                name: 'Gemstone Caverns',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 62,
                name: 'Grove of the Burnwillows',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 63,
                name: 'High Market',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 64,
                name: 'Hissing Quagmire',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 65,
                name: 'Inkmoth Nexus',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 66,
                name: "Inventors' Fair",
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 67,
                name: 'Lavaclaw Reaches',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 68,
                name: 'Lotus Field',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 69,
                name: 'Lumbering Falls',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 70,
                name: 'Mana Confluence',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 71,
                name: 'Meteor Crater',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 72,
                name: 'Mirrorpool',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 73,
                name: 'Mutavault',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 74,
                name: 'Mystifying Maze',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 75,
                name: 'Needle Spires',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 76,
                name: 'Nesting Grounds',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 77,
                name: 'Petrified Field',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 78,
                name: 'Plaza of Heroes',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 79,
                name: 'Power Depot',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Land',
                colors: '',
            },
            {
                cardNumber: 80,
                name: 'Raging Ravine',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 81,
                name: 'Reflecting Pool',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 82,
                name: 'Scavenger Grounds',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 83,
                name: 'Shambling Vent',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 84,
                name: 'Stirring Wildwood',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 85,
                name: 'Strip Mine',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 86,
                name: 'Sunken Citadel',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 87,
                name: 'Swarmyard',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 88,
                name: 'Terrain Generator',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 89,
                name: "Thespian's Stage",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 90,
                name: 'Wandering Fumarole',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 91,
                name: 'Ancient Tomb',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 92,
                name: 'Blast Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 93,
                name: 'Blinkmoth Nexus',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 94,
                name: "Bonders' Enclave",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 95,
                name: 'Cascading Cataracts',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 96,
                name: 'Cathedral of War',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 97,
                name: 'Celestial Colonnade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 98,
                name: 'Contested War Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 99,
                name: 'Creeping Tar Pit',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 100,
                name: 'Crystal Quarry',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 101,
                name: 'Deserted Temple',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 102,
                name: 'Dust Bowl',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 103,
                name: 'Echoing Deeps',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 104,
                name: 'Eldrazi Temple',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 105,
                name: 'Endless Sands',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 106,
                name: 'Gemstone Caverns',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 107,
                name: 'Grove of the Burnwillows',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 108,
                name: 'High Market',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 109,
                name: 'Hissing Quagmire',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 110,
                name: 'Inkmoth Nexus',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 111,
                name: "Inventors' Fair",
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 112,
                name: 'Lavaclaw Reaches',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 113,
                name: 'Lotus Field',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 114,
                name: 'Lumbering Falls',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 115,
                name: 'Mana Confluence',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 116,
                name: 'Meteor Crater',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 117,
                name: 'Mirrorpool',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 118,
                name: 'Mutavault',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 119,
                name: 'Mystifying Maze',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 120,
                name: 'Needle Spires',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 121,
                name: 'Nesting Grounds',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 122,
                name: 'Petrified Field',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 123,
                name: 'Plaza of Heroes',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 124,
                name: 'Power Depot',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Land',
                colors: '',
            },
            {
                cardNumber: 125,
                name: 'Raging Ravine',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 126,
                name: 'Reflecting Pool',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 127,
                name: 'Scavenger Grounds',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 128,
                name: 'Shambling Vent',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 129,
                name: 'Stirring Wildwood',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 130,
                name: 'Strip Mine',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 131,
                name: 'Sunken Citadel',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 132,
                name: 'Swarmyard',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 133,
                name: 'Terrain Generator',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 134,
                name: "Thespian's Stage",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 135,
                name: 'Wandering Fumarole',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 136,
                name: 'Ancient Tomb',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 137,
                name: 'Blast Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 138,
                name: 'Blinkmoth Nexus',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 139,
                name: "Bonders' Enclave",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 140,
                name: 'Cascading Cataracts',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 141,
                name: 'Cathedral of War',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 142,
                name: 'Celestial Colonnade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 143,
                name: 'Contested War Zone',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 144,
                name: 'Creeping Tar Pit',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 145,
                name: 'Crystal Quarry',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 146,
                name: 'Deserted Temple',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 147,
                name: 'Dust Bowl',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 148,
                name: 'Echoing Deeps',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 149,
                name: 'Eldrazi Temple',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 150,
                name: 'Endless Sands',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 151,
                name: 'Gemstone Caverns',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 152,
                name: 'Grove of the Burnwillows',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 153,
                name: 'High Market',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 154,
                name: 'Hissing Quagmire',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 155,
                name: 'Inkmoth Nexus',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 156,
                name: "Inventors' Fair",
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 157,
                name: 'Lavaclaw Reaches',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 158,
                name: 'Lotus Field',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 159,
                name: 'Lumbering Falls',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 160,
                name: 'Mana Confluence',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 161,
                name: 'Meteor Crater',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 162,
                name: 'Mirrorpool',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 163,
                name: 'Mutavault',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 164,
                name: 'Mystifying Maze',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 165,
                name: 'Needle Spires',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 166,
                name: 'Nesting Grounds',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 167,
                name: 'Petrified Field',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 168,
                name: 'Plaza of Heroes',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 169,
                name: 'Power Depot',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Land',
                colors: '',
            },
            {
                cardNumber: 170,
                name: 'Raging Ravine',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 171,
                name: 'Reflecting Pool',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 172,
                name: 'Scavenger Grounds',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 173,
                name: 'Shambling Vent',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 174,
                name: 'Stirring Wildwood',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 175,
                name: 'Strip Mine',
                rarity: 'M',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 176,
                name: 'Sunken Citadel',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 177,
                name: 'Swarmyard',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 178,
                name: 'Terrain Generator',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 179,
                name: "Thespian's Stage",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 180,
                name: 'Wandering Fumarole',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'Edge of Eternities: Stellar Sights',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
