import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addSpm1757904458879 implements MigrationInterface {
    shortName = 'SPM';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Anti-Venom, Horrifying Healer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 2,
                name: 'Arachne, Psionic Weaver',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 3,
                name: 'Aunt May',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'City Pigeon',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'Costume Closet',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Daily Bugle Reporters',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Flash Thompson, Spider-Fan',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Friendly Neighborhood',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Origin of Spider-Man',
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Peter Parker // Amazing Spider-Man',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Rent Is Due',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Selfless Police Captain',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Silver Sable, Mercenary Leader',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Spectacular Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Spectacular Tactics',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Spider-Man, Web-Slinger',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Spider-UK',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Starling, Aerial Ally',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: 'Sudden Strike',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Thwip!',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: 'Web Up',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Web-Shooters',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'Wild Pack Squad',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'With Great Power...',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Amazing Acrobatics',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 26,
                name: 'Beetle, Legacy Criminal',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 27,
                name: 'Chameleon, Master of Disguise',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 28,
                name: 'The Clone Saga',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 29,
                name: 'Doc Ock, Sinister Scientist',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 30,
                name: "Doc Ock's Henchmen",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 31,
                name: 'Flying Octobot',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U',
            },
            {
                cardNumber: 32,
                name: 'Hide on the Ceiling',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 33,
                name: 'Hydro-Man, Fluid Felon',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 34,
                name: 'Impostor Syndrome',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 35,
                name: 'Lady Octopus, Inspired Inventor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 36,
                name: 'Madame Web, Clairvoyant',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 37,
                name: 'Mysterio, Master of Illusion',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 38,
                name: "Mysterio's Phantasm",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 39,
                name: 'Norman Osborn // Green Goblin',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 40,
                name: 'Oscorp Research Team',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 41,
                name: 'Robotics Mastery',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 42,
                name: 'School Daze',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 43,
                name: 'Secret Identity',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 44,
                name: 'Spider-Byte, Web Warden',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 45,
                name: 'Spider-Man No More',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 46,
                name: 'Spider-Sense',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Unstable Experiment',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Whoosh!',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Agent Venom',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 50,
                name: 'Alien Symbiosis',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 51,
                name: 'Behold the Sinister Six!',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 52,
                name: 'Black Cat, Cunning Thief',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 53,
                name: 'Common Crook',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 54,
                name: 'The Death of Gwen Stacy',
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 55,
                name: 'Eddie Brock // Venom, Lethal Protector',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 56,
                name: 'Gwenom, Remorseless',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 57,
                name: 'Inner Demons Gangsters',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 58,
                name: 'Merciless Enforcers',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 59,
                name: 'Morlun, Devourer of Spiders',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 60,
                name: 'Parker Luck',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 61,
                name: 'Prison Break',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 62,
                name: 'Risky Research',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 63,
                name: "Sandman's Quicksand",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 64,
                name: 'Scorpion, Seething Striker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 65,
                name: "Scorpion's Sting",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 66,
                name: 'The Soul Stone',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 67,
                name: 'Spider-Man Noir',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 68,
                name: "The Spot's Portal",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 69,
                name: 'Swarm, Being of Bees',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 70,
                name: 'Tombstone, Career Criminal',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 71,
                name: 'Venom, Evil Unleashed',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 72,
                name: 'Venomized Cat',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 73,
                name: "Venom's Hunger",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 74,
                name: 'Villainous Wrath',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 75,
                name: 'Angry Rabble',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 76,
                name: 'Electro, Assaulting Battery',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 77,
                name: "Electro's Bolt",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 78,
                name: 'Gwen Stacy // Ghost-Spider',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 79,
                name: "Heroes' Hangout",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 80,
                name: 'Hobgoblin, Mantled Marauder',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 81,
                name: 'J. Jonah Jameson',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 82,
                name: 'Masked Meower',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 83,
                name: 'Maximum Carnage',
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 84,
                name: 'Molten Man, Inferno Incarnate',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 85,
                name: 'Raging Goblinoids',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 86,
                name: 'Romantic Rendezvous',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 87,
                name: 'Shadow of the Goblin',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 88,
                name: 'Shock',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 89,
                name: 'Shocker, Unshakable',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 90,
                name: 'Spider-Gwen, Free Spirit',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 91,
                name: 'Spider-Islanders',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 92,
                name: 'Spider-Punk',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 93,
                name: 'Spider-Verse',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 94,
                name: 'Spinneret and Spiderling',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 95,
                name: 'Stegron the Dinosaur Man',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 96,
                name: 'Superior Foes of Spider-Man',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 97,
                name: 'Taxi Driver',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 98,
                name: 'Wisecrack',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 99,
                name: 'Damage Control Crew',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 100,
                name: 'Ezekiel Sims, Spider-Totem',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 101,
                name: 'Grow Extra Arms',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 102,
                name: 'Guy in the Chair',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 103,
                name: 'Kapow!',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 104,
                name: "Kraven's Cats",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 105,
                name: "Kraven's Last Hunt",
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 106,
                name: "Lizard, Connors's Curse",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 107,
                name: 'Lurking Lizards',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 108,
                name: 'Miles Morales // Ultimate Spider-Man',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 109,
                name: 'Pictures of Spider-Man',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'G',
            },
            {
                cardNumber: 110,
                name: 'Professional Wrestler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 111,
                name: 'Radioactive Spider',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 112,
                name: 'Sandman, Shifting Scoundrel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 113,
                name: 'Scout the City',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 114,
                name: 'Spider-Ham, Peter Porker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 115,
                name: 'Spider-Man, Brooklyn Visionary',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 116,
                name: 'Spider-Rex, Daring Dino',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 117,
                name: 'Spiders-Man, Heroic Horde',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 118,
                name: 'Strength of Will',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 119,
                name: 'Supportive Parents',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 120,
                name: 'Terrific Team-Up',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 121,
                name: 'Wall Crawl',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 122,
                name: 'Web of Life and Destiny',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 123,
                name: 'Araña, Heart of the Spider',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 124,
                name: 'Biorganic Carapace',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U,W',
            },
            {
                cardNumber: 125,
                name: 'Carnage, Crimson Chaos',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 126,
                name: 'Cheering Crowd',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 127,
                name: 'Cosmic Spider-Man',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 128,
                name: 'Doctor Octopus, Master Planner',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 129,
                name: 'Gallant Citizen',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 130,
                name: 'Green Goblin, Revenant',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 131,
                name: 'Jackal, Genius Geneticist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 132,
                name: 'Kraven, Proud Predator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 133,
                name: 'Kraven the Hunter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 134,
                name: 'Mary Jane Watson',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 135,
                name: 'Mister Negative',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 136,
                name: 'Mob Lookout',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 137,
                name: 'Morbius the Living Vampire',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 138,
                name: 'Prowler, Clawed Thief',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 139,
                name: 'Pumpkin Bombardment',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 140,
                name: 'Rhino, Barreling Brute',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 141,
                name: "Rhino's Rampage",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,R',
            },
            {
                cardNumber: 142,
                name: 'Scarlet Spider, Ben Reilly',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 143,
                name: 'Scarlet Spider, Kaine',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 144,
                name: 'Shriek, Treblemaker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 145,
                name: 'Silk, Web Weaver',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 146,
                name: 'Skyward Spider',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 147,
                name: 'SP//dr, Piloted by Peni',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 148,
                name: 'Spider Manifestation',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 149,
                name: 'Spider-Girl, Legacy Hero',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 150,
                name: 'Spider-Man 2099',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 151,
                name: 'Spider-Man India',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 152,
                name: 'Spider-Woman, Stunning Savior',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 153,
                name: 'The Spot, Living Portal',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 154,
                name: 'Sun-Spider, Nimble Webber',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 155,
                name: 'Superior Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 156,
                name: 'Symbiote Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 157,
                name: 'Ultimate Green Goblin',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 158,
                name: 'Vulture, Scheming Scavenger',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 159,
                name: 'Web-Warriors',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 160,
                name: 'Wraith, Vicious Vigilante',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 161,
                name: 'Bagel and Schmear',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 162,
                name: "Doc Ock's Tentacles",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 163,
                name: 'Eerie Gravestone',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 164,
                name: 'Hot Dog Cart',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 165,
                name: 'Interdimensional Web Watch',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 166,
                name: 'Iron Spider, Stark Upgrade',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 167,
                name: 'Living Brain, Mechanical Marvel',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 168,
                name: 'Mechanical Mobster',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 169,
                name: 'News Helicopter',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 170,
                name: 'Passenger Ferry',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 171,
                name: "Peter Parker's Camera",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 172,
                name: 'Rocket-Powered Goblin Glider',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 173,
                name: 'Spider-Bot',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 174,
                name: 'Spider-Mobile',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 175,
                name: 'Spider-Slayer, Hatred Honed',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 176,
                name: 'Spider-Suit',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 177,
                name: 'Steel Wrecking Ball',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 178,
                name: 'Subway Train',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 179,
                name: 'Daily Bugle Building',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 180,
                name: 'Multiversal Passage',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 181,
                name: 'Ominous Asylum',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 182,
                name: 'Oscorp Industries',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 183,
                name: 'Savage Mansion',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 184,
                name: 'Sinister Hideout',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 185,
                name: 'Suburban Sanctuary',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 186,
                name: 'University Campus',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 187,
                name: 'Urban Retreat',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 188,
                name: 'Vibrant Cityscape',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 189,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 190,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 191,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 192,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 193,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 194,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 195,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 196,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 197,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 198,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 199,
                name: 'SP//dr, Piloted by Peni',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 200,
                name: 'Miles Morales // Ultimate Spider-Man',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 201,
                name: 'Spider-Ham, Peter Porker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 202,
                name: 'Gwen Stacy // Ghost-Spider',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 203,
                name: 'Web-Warriors',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 204,
                name: 'Spider-Man Noir',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 205,
                name: 'Spider-Man 2099',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 206,
                name: 'Multiversal Passage',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 207,
                name: 'Spider-Punk',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 208,
                name: 'Peter Parker // Amazing Spider-Man',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 209,
                name: 'Gwen Stacy // Ghost-Spider',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 210,
                name: 'Spider-Punk',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 211,
                name: 'Miles Morales // Ultimate Spider-Man',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 212,
                name: 'Radioactive Spider',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 213,
                name: 'Araña, Heart of the Spider',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 214,
                name: 'Scarlet Spider, Ben Reilly',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 215,
                name: 'Silk, Web Weaver',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 216,
                name: 'Spider-Man 2099',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 217,
                name: 'Symbiote Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 218,
                name: 'Origin of Spider-Man',
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 219,
                name: 'The Clone Saga',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 220,
                name: 'Norman Osborn // Green Goblin',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 221,
                name: 'Behold the Sinister Six!',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 222,
                name: 'Black Cat, Cunning Thief',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 223,
                name: 'The Death of Gwen Stacy',
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 224,
                name: 'Eddie Brock // Venom, Lethal Protector',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 225,
                name: 'Maximum Carnage',
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 226,
                name: "Kraven's Last Hunt",
                rarity: 'R',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 227,
                name: 'Carnage, Crimson Chaos',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 228,
                name: 'Doctor Octopus, Master Planner',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 229,
                name: 'Mary Jane Watson',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 230,
                name: 'Spider-Woman, Stunning Savior',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 231,
                name: 'The Spot, Living Portal',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 232,
                name: 'Peter Parker // Amazing Spider-Man',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 233,
                name: 'Eddie Brock // Venom, Lethal Protector',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 234,
                name: 'Miles Morales // Ultimate Spider-Man',
                rarity: 'M',
                layout: 'modal_dfc',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 235,
                name: 'Spectacular Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 236,
                name: 'Spectacular Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 237,
                name: 'Spectacular Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 238,
                name: 'Spectacular Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 239,
                name: 'Spectacular Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 240,
                name: 'Spectacular Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 241,
                name: 'Spectacular Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 242,
                name: 'The Soul Stone',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 243,
                name: 'The Soul Stone',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 244,
                name: 'Anti-Venom, Horrifying Healer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 245,
                name: 'Arachne, Psionic Weaver',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 246,
                name: 'Friendly Neighborhood',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 247,
                name: 'Rent Is Due',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 248,
                name: 'With Great Power...',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 249,
                name: 'Hide on the Ceiling',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 250,
                name: 'Hydro-Man, Fluid Felon',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 251,
                name: 'Impostor Syndrome',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 252,
                name: 'Lady Octopus, Inspired Inventor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 253,
                name: 'Mysterio, Master of Illusion',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 254,
                name: 'Spider-Sense',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 255,
                name: 'Agent Venom',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 256,
                name: 'Gwenom, Remorseless',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 257,
                name: 'Morlun, Devourer of Spiders',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 258,
                name: 'Parker Luck',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 259,
                name: 'Villainous Wrath',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 260,
                name: 'Electro, Assaulting Battery',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 261,
                name: 'J. Jonah Jameson',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 262,
                name: 'Shadow of the Goblin',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 263,
                name: 'Spider-Verse',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 264,
                name: 'Spinneret and Spiderling',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 265,
                name: "Lizard, Connors's Curse",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 266,
                name: 'Sandman, Shifting Scoundrel',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 267,
                name: 'Strength of Will',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 268,
                name: 'Web of Life and Destiny',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 269,
                name: 'Biorganic Carapace',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U,W',
            },
            {
                cardNumber: 270,
                name: 'Cheering Crowd',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 271,
                name: 'Cosmic Spider-Man',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,R,U,W',
            },
            {
                cardNumber: 272,
                name: 'Jackal, Genius Geneticist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 273,
                name: 'Kraven the Hunter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 274,
                name: 'Mister Negative',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 275,
                name: 'Superior Spider-Man',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 276,
                name: 'Ultimate Green Goblin',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 277,
                name: "Doc Ock's Tentacles",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Interdimensional Web Watch',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 279,
                name: 'Iron Spider, Stark Upgrade',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 280,
                name: "Peter Parker's Camera",
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 281,
                name: 'Rocket-Powered Goblin Glider',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Oscorp Industries',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 283,
                name: 'Urban Retreat',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 284,
                name: 'Spider-Sense',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 285,
                name: 'Radioactive Spider',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 286,
                name: 'Gwenom, Remorseless',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            "Marvel's Spider-Man",
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
