import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addTla1762674043496 implements MigrationInterface {
    shortName = 'TLA';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: "Aang's Journey",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: '',
            },
            {
                cardNumber: 2,
                name: 'Energybending',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: '',
            },
            {
                cardNumber: 3,
                name: "Zuko's Exile",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: '',
            },
            {
                cardNumber: 4,
                name: 'Aang, the Last Airbender',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: "Aang's Iceberg",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Airbender Ascension',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: "Airbender's Reversal",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Airbending Lesson',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Appa, Loyal Sky Bison',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Appa, Steadfast Guardian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Avatar Enthusiasts',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: "Avatar's Wrath",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Compassionate Healer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Curious Farm Animals',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Destined Confrontation',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Earth Kingdom Jailer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Earth Kingdom Protectors',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Enter the Avatar State',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: 'Fancy Footwork',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Gather the White Lotus',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: 'Glider Kids',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Glider Staff',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'Hakoda, Selfless Commander',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'Invasion Reinforcements',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: "Jeong Jeong's Deserters",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Kyoshi Warriors',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: 'The Legend of Yangchen // Avatar Yangchen',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Master Piandao',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: 'Momo, Friendly Flier',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Momo, Playful Pet',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Path to Redemption',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Rabaroo Troop',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: 'Razor Rings',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: "Sandbenders' Storm",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: 'South Pole Voyager',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: 'Southern Air Temple',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Suki, Courageous Rescuer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Team Avatar',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 39,
                name: 'United Front',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 40,
                name: 'Vengeful Villagers',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 41,
                name: 'Water Tribe Captain',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 42,
                name: 'Water Tribe Rallier',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 43,
                name: 'Yip Yip!',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 44,
                name: 'Accumulate Wisdom',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 45,
                name: 'Benevolent River Spirit',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 46,
                name: 'Boomerang Basics',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Crashing Wave',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Ember Island Production',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'First-Time Flyer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Flexible Waterbender',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: 'Forecasting Fortune Teller',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: 'Geyser Leaper',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Giant Koi',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Gran-Gran',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: 'Honest Work',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'Iguana Parrot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Invasion Submersible',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: "It'll Quench Ya!",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Katara, Bending Prodigy',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Knowledge Seeker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: 'The Legend of Kuruk // Avatar Kuruk',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Lost Days',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: 'Master Pakku',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'The Mechanist, Aerial Artisan',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: 'North Pole Patrol',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: 'Octopus Form',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Otter-Penguin',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: 'Rowdy Snowballers',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Secret of Bloodbending',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Serpent of the Pass',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: "Sokka's Haiku",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'The Spirit Oasis',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 73,
                name: 'Spirit Water Revival',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Teo, Spirited Glider',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: 'Tiger-Seal',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Ty Lee, Chi Blocker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'The Unagi of Kyoshi Island',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Wan Shi Tong, Librarian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 79,
                name: 'Waterbender Ascension',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 80,
                name: 'Waterbending Lesson',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 81,
                name: 'Waterbending Scroll',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 82,
                name: 'Watery Grasp',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 83,
                name: 'Yue, the Moon Spirit',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 84,
                name: 'Azula Always Lies',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 85,
                name: 'Azula, On the Hunt',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 86,
                name: 'Beetle-Headed Merchants',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 87,
                name: 'Boiling Rock Rioter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 88,
                name: 'Buzzard-Wasp Colony',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 89,
                name: 'Callous Inspector',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 90,
                name: 'Canyon Crawler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: 'Cat-Gator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: 'Corrupt Court Official',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Dai Li Indoctrination',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'Day of Black Sun',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Deadly Precision',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Epic Downfall',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: 'Fatal Fissure',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'The Fire Nation Drill',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Fire Nation Engineer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Fire Navy Trebuchet',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Foggy Swamp Hunters',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Foggy Swamp Visions',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Heartless Act',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: 'Hog-Monkey',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Joo Dee, One of Many',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'June, Bounty Hunter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 107,
                name: 'Koh, the Face Stealer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 108,
                name: 'Lo and Li, Twin Tutors',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 109,
                name: 'Mai, Scornful Striker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 110,
                name: 'Merchant of Many Hats',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 111,
                name: 'Northern Air Temple',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 112,
                name: 'Obsessive Pursuit',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 113,
                name: "Ozai's Cruelty",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 114,
                name: 'Phoenix Fleet Airship',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 115,
                name: 'Pirate Peddlers',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 116,
                name: 'Raven Eagle',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 117,
                name: 'The Rise of Sozin // Fire Lord Sozin',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 118,
                name: 'Ruinous Waterbending',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 119,
                name: 'Sold Out',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 120,
                name: 'Swampsnare Trap',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 121,
                name: 'Tundra Tank',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 122,
                name: 'Wolfbat',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 123,
                name: "Zuko's Conviction",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 124,
                name: 'Boar-q-pine',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 125,
                name: 'Bumi Bash',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 126,
                name: 'The Cave of Two Lovers',
                rarity: 'U',
                layout: 'saga',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 127,
                name: 'Combustion Man',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 128,
                name: 'Combustion Technique',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 129,
                name: 'Crescent Island Temple',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 130,
                name: 'Cunning Maneuver',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 131,
                name: "Deserter's Disciple",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 132,
                name: 'Fated Firepower',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 133,
                name: 'Fire Nation Attacks',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 134,
                name: 'Fire Nation Cadets',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 135,
                name: 'Fire Nation Raider',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 136,
                name: 'Fire Sages',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 137,
                name: 'Firebender Ascension',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 138,
                name: 'Firebending Lesson',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 139,
                name: 'Firebending Student',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 140,
                name: 'How to Start a Riot',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 141,
                name: "Iroh's Demonstration",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 142,
                name: 'Jeong Jeong, the Deserter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 143,
                name: "Jet's Brainwashing",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 144,
                name: 'The Last Agni Kai',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 145,
                name: 'The Legend of Roku // Avatar Roku',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 146,
                name: 'Lightning Strike',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 147,
                name: 'Mai, Jaded Edge',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 148,
                name: 'Mongoose Lizard',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 149,
                name: 'Price of Freedom',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 150,
                name: 'Ran and Shaw',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: 'Redirect Lightning',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Rough Rhino Cavalry',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: 'Solstice Revelations',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: "Sozin's Comet",
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: 'Tiger-Dillo',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Treetop Freedom Fighters',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 157,
                name: 'Twin Blades',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 158,
                name: 'Ty Lee, Artful Acrobat',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 159,
                name: 'War Balloon',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 160,
                name: 'Wartime Protestors',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 161,
                name: 'Yuyan Archers',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 162,
                name: 'Zhao, the Moon Slayer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 163,
                name: 'Zuko, Exiled Prince',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 164,
                name: 'Allies at Last',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 165,
                name: 'Avatar Destiny',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 166,
                name: 'Badgermole',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 167,
                name: 'Badgermole Cub',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 168,
                name: 'The Boulder, Ready to Rumble',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 169,
                name: 'Bumi, King of Three Trials',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 170,
                name: 'Cycle of Renewal',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 171,
                name: 'Diligent Zookeeper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 172,
                name: 'The Earth King',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 173,
                name: 'Earth Kingdom General',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 174,
                name: 'Earth Rumble',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 175,
                name: 'Earthbender Ascension',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 176,
                name: 'Earthbending Lesson',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 177,
                name: 'Earthen Ally',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 178,
                name: 'Elemental Teachings',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 179,
                name: "Flopsie, Bumi's Buddy",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 180,
                name: 'Foggy Swamp Vinebender',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 181,
                name: 'Great Divide Guide',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 182,
                name: 'Haru, Hidden Talent',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 183,
                name: 'Invasion Tactics',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 184,
                name: 'Kyoshi Island Plaza',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 185,
                name: 'Leaves from the Vine',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: 'The Legend of Kyoshi // Avatar Kyoshi',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Origin of Metalbending',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Ostrich-Horse',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Pillar Launch',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: 'Raucous Audience',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Rebellious Captives',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 192,
                name: 'Rockalanche',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 193,
                name: 'Rocky Rebuke',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 194,
                name: 'Saber-Tooth Moose-Lion',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 195,
                name: 'Seismic Sense',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 196,
                name: 'Shared Roots',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 197,
                name: 'Sparring Dummy',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'G',
            },
            {
                cardNumber: 198,
                name: 'Toph, the Blind Bandit',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 199,
                name: 'True Ancestry',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 200,
                name: 'Turtle-Duck',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 201,
                name: 'Unlucky Cabbage Merchant',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 202,
                name: 'Walltop Sentries',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 203,
                name: 'Aang, at the Crossroads // Aang, Destined Savior',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,U,W',
            },
            {
                cardNumber: 204,
                name: "Aang, Swift Savior // Aang and La, Ocean's Fury",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 205,
                name: 'Abandon Attachments',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 206,
                name: 'Air Nomad Legacy',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U,W',
            },
            {
                cardNumber: 207,
                name: 'Avatar Aang // Aang, Master of Elements',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,R,U,W',
            },
            {
                cardNumber: 208,
                name: 'Azula, Cunning Usurper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 209,
                name: "Beifong's Bounty Hunters",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 210,
                name: 'Bitter Work',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G,R',
            },
            {
                cardNumber: 211,
                name: 'Bumi, Unleashed',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 212,
                name: 'Cat-Owl',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 213,
                name: 'Cruel Administrator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 214,
                name: 'Dai Li Agents',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 215,
                name: 'Dragonfly Swarm',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 216,
                name: 'Earth Kingdom Soldier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 217,
                name: "Earth King's Lieutenant",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 218,
                name: 'Earth Rumble Wrestlers',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 219,
                name: 'Earth Village Ruffians',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 220,
                name: 'Fire Lord Azula',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R,U',
            },
            {
                cardNumber: 221,
                name: 'Fire Lord Zuko',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R,W',
            },
            {
                cardNumber: 222,
                name: 'Foggy Swamp Spirit Keeper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 223,
                name: 'Guru Pathik',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 224,
                name: 'Hama, the Bloodbender',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 225,
                name: 'Hei Bai, Spirit of Balance',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 226,
                name: 'Hermitic Herbalist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 227,
                name: 'Iroh, Grand Lotus',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,U',
            },
            {
                cardNumber: 228,
                name: 'Iroh, Tea Master',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 229,
                name: 'Jet, Freedom Fighter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 230,
                name: 'Katara, the Fearless',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U,W',
            },
            {
                cardNumber: 231,
                name: "Katara, Water Tribe's Hope",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 232,
                name: 'The Lion-Turtle',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 233,
                name: 'Long Feng, Grand Secretariat',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 234,
                name: 'Messenger Hawk',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 235,
                name: 'Ozai, the Phoenix King',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 236,
                name: 'Platypus-Bear',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 237,
                name: 'Pretending Poxbearers',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 238,
                name: 'Professor Zei, Anthropologist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 239,
                name: 'Sandbender Scavengers',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 240,
                name: 'Sokka, Bold Boomeranger',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 241,
                name: 'Sokka, Lateral Strategist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 242,
                name: 'Sokka, Tenacious Tactician',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U,W',
            },
            {
                cardNumber: 243,
                name: 'Suki, Kyoshi Warrior',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 244,
                name: 'Sun Warriors',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 245,
                name: 'Tolls of War',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B,W',
            },
            {
                cardNumber: 246,
                name: 'Toph, Hardheaded Teacher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 247,
                name: 'Toph, the First Metalbender',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,W',
            },
            {
                cardNumber: 248,
                name: 'Uncle Iroh',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 249,
                name: 'Vindictive Warden',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 250,
                name: 'Wandering Musicians',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 251,
                name: 'White Lotus Reinforcements',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 252,
                name: 'Zhao, Ruthless Admiral',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 253,
                name: 'Zuko, Conflicted',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 254,
                name: 'Barrels of Blasting Jelly',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 255,
                name: "Bender's Waterskin",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 256,
                name: 'Fire Nation Warship',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 257,
                name: 'Kyoshi Battle Fan',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 258,
                name: 'Meteor Sword',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 259,
                name: 'Planetarium of Wan Shi Tong',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Trusty Boomerang',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'The Walls of Ba Sing Se',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'White Lotus Tile',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 263,
                name: 'Abandoned Air Temple',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 264,
                name: "Agna Qel'a",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Airship Engine Room',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 266,
                name: 'Ba Sing Se',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Boiling Rock Prison',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Fire Nation Palace',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Foggy Bottom Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Jasmine Dragon Tea Shop',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Kyoshi Village',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Meditation Pools',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Misty Palms Oasis',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'North Pole Gates',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Omashu City',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Realm of Koh',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Rumble Arena',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Secret Tunnel',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 279,
                name: "Serpent's Pass",
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 280,
                name: 'Sun-Blessed Peak',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 281,
                name: 'White Lotus Hideout',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 283,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 284,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 285,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 286,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 287,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 288,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 289,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 290,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 291,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 292,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 293,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 294,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 295,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 296,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 297,
                name: 'Fated Firepower',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 298,
                name: "Aang, Swift Savior // Aang and La, Ocean's Fury",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 299,
                name: 'Fire Nation Attacks',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 300,
                name: 'Crashing Wave',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 301,
                name: 'Combustion Technique',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 302,
                name: 'Zuko, Conflicted',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 303,
                name: 'Azula, Cunning Usurper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 304,
                name: 'Aang, at the Crossroads // Aang, Destined Savior',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,U,W',
            },
            {
                cardNumber: 305,
                name: 'Katara, the Fearless',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U,W',
            },
            {
                cardNumber: 306,
                name: 'Dai Li Agents',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 307,
                name: 'Earthbender Ascension',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 308,
                name: 'Avatar Aang // Aang, Master of Elements',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,R,U,W',
            },
            {
                cardNumber: 309,
                name: "Sozin's Comet",
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 310,
                name: 'Waterbender Ascension',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 311,
                name: 'Ozai, the Phoenix King',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 312,
                name: 'Firebender Ascension',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 313,
                name: 'Fire Lord Azula',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R,U',
            },
            {
                cardNumber: 314,
                name: 'The Last Agni Kai',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 315,
                name: 'Fire Lord Zuko',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R,W',
            },
            {
                cardNumber: 316,
                name: 'Appa, Steadfast Guardian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 317,
                name: 'Momo, Friendly Flier',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 318,
                name: 'Tiger-Seal',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 319,
                name: 'The Unagi of Kyoshi Island',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 320,
                name: 'Wan Shi Tong, Librarian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 321,
                name: 'The Fire Nation Drill',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 322,
                name: 'Koh, the Face Stealer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 323,
                name: 'Phoenix Fleet Airship',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 324,
                name: 'Raven Eagle',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 325,
                name: 'Ran and Shaw',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 326,
                name: 'Badgermole Cub',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 327,
                name: 'Diligent Zookeeper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 328,
                name: 'The Lion-Turtle',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 329,
                name: 'The Walls of Ba Sing Se',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 330,
                name: 'White Lotus Tile',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 331,
                name: 'United Front',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 332,
                name: "Sozin's Comet",
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 333,
                name: 'Avatar Destiny',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 334,
                name: 'Fire Lord Azula',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R,U',
            },
            {
                cardNumber: 335,
                name: 'Ozai, the Phoenix King',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 336,
                name: "Aang's Iceberg",
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 337,
                name: 'Secret of Bloodbending',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 338,
                name: 'Yue, the Moon Spirit',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 339,
                name: 'Foggy Swamp Visions',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 340,
                name: 'Obsessive Pursuit',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 341,
                name: 'Fated Firepower',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 342,
                name: 'Firebending Student',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 343,
                name: 'Redirect Lightning',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 344,
                name: 'The Earth King',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 345,
                name: 'Great Divide Guide',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 346,
                name: 'Aang, at the Crossroads // Aang, Destined Savior',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,U,W',
            },
            {
                cardNumber: 347,
                name: "Aang, Swift Savior // Aang and La, Ocean's Fury",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 348,
                name: 'Bumi, Unleashed',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 349,
                name: 'Iroh, Grand Lotus',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,U',
            },
            {
                cardNumber: 350,
                name: 'Katara, the Fearless',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U,W',
            },
            {
                cardNumber: 351,
                name: "Katara, Water Tribe's Hope",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 352,
                name: 'Sokka, Tenacious Tactician',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U,W',
            },
            {
                cardNumber: 353,
                name: 'Toph, the First Metalbender',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,W',
            },
            {
                cardNumber: 354,
                name: 'The Legend of Yangchen // Avatar Yangchen',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 355,
                name: 'The Legend of Kuruk // Avatar Kuruk',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 356,
                name: 'The Rise of Sozin // Fire Lord Sozin',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 357,
                name: 'The Legend of Roku // Avatar Roku',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 358,
                name: 'The Legend of Kyoshi // Avatar Kyoshi',
                rarity: 'M',
                layout: 'transform',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 359,
                name: "Aang, Swift Savior // Aang and La, Ocean's Fury",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 360,
                name: 'Fire Lord Zuko',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R,W',
            },
            {
                cardNumber: 361,
                name: 'Katara, the Fearless',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U,W',
            },
            {
                cardNumber: 362,
                name: 'Toph, the First Metalbender',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R,W',
            },
            {
                cardNumber: 363,
                name: 'Avatar Aang // Aang, Master of Elements',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'G,R,U,W',
            },
            {
                cardNumber: 364,
                name: 'Airbender Ascension',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 365,
                name: "Avatar's Wrath",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 366,
                name: 'Hakoda, Selfless Commander',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 367,
                name: 'South Pole Voyager',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 368,
                name: 'Suki, Courageous Rescuer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 369,
                name: 'The Mechanist, Aerial Artisan',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 370,
                name: 'Spirit Water Revival',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 371,
                name: 'Ty Lee, Chi Blocker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 372,
                name: 'Boiling Rock Rioter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 373,
                name: 'Day of Black Sun',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 374,
                name: 'Mai, Scornful Striker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 375,
                name: 'Wartime Protestors',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 376,
                name: 'Zhao, the Moon Slayer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 377,
                name: 'Earthen Ally',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 378,
                name: 'Elemental Teachings',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 379,
                name: "Beifong's Bounty Hunters",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 380,
                name: "Earth King's Lieutenant",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 381,
                name: 'Iroh, Tea Master',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 382,
                name: 'Sandbender Scavengers',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 383,
                name: 'Sokka, Bold Boomeranger',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 384,
                name: 'Toph, Hardheaded Teacher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 385,
                name: 'Planetarium of Wan Shi Tong',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 386,
                name: 'Abandoned Air Temple',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 387,
                name: "Agna Qel'a",
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 388,
                name: 'Ba Sing Se',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 389,
                name: 'Fire Nation Palace',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 390,
                name: 'Jasmine Dragon Tea Shop',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 391,
                name: 'Realm of Koh',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 392,
                name: 'Secret Tunnel',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 393,
                name: 'Firebending Student',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 394,
                name: 'Momo, Friendly Flier',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'Avatar: The Last Airbender',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
