import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addEcl1768151422890 implements MigrationInterface {
    shortName = 'ECL';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'Changeling Wayfinder',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 2,
                name: 'Rooftop Percher',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 3,
                name: 'Adept Watershaper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'Ajani, Outland Chaperone',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'Appeal to Eirdu',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Bark of Doran',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: "Brigid, Clachan's Heart // Brigid, Doun's Mind",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Burdened Stoneback',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Champion of the Clachan',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Clachan Festival',
                rarity: 'U',
                layout: 'normal',
                types: 'Kindred,Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Crib Swap',
                rarity: 'U',
                layout: 'normal',
                types: 'Kindred,Instant',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Curious Colossus',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Eirdu, Carrier of Dawn // Isilu, Carrier of Twilight',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Encumbered Reejerey',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: "Evershrike's Gift",
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Flock Impostor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Gallant Fowlknight',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Goldmeadow Nomad',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: 'Keep Out',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Kinbinding',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: 'Kinsbaile Aspirant',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Kinscaer Sentry',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'Kithkeeper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'Liminal Hold',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Meanders Guide',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Moonlit Lamenter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: "Morningtide's Light",
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Personify',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: 'Protective Response',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Pyrrhic Strike',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Reluctant Dounguard',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Rhys, the Evermore',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: "Riverguard's Reflexes",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: 'Shore Lurker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: 'Slumbering Walker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: 'Spiral into Solitude',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Sun-Dappled Celebrant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Thoughtweft Imbuer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 39,
                name: 'Timid Shieldbearer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 40,
                name: 'Tributary Vaulter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 41,
                name: 'Wanderbrine Preacher',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 42,
                name: 'Wanderbrine Trapper',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 43,
                name: 'Winnowing',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 44,
                name: "Aquitect's Defenses",
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 45,
                name: 'Blossombind',
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 46,
                name: 'Champions of the Shoal',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Disruptor of Currents',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Flitterwing Nuisance',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Glamer Gifter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Glamermite',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: 'Glen Elendra Guardian',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: "Glen Elendra's Answer",
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Gravelgill Scoundrel',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Harmonized Crescendo',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: 'Illusion Spinners',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'Kulrath Mystic',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Loch Mare',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: 'Lofty Dreams',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Mirrorform',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Noggle the Mind',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: 'Oko, Lorwyn Liege // Oko, Shadowmoor Scion',
                rarity: 'M',
                layout: 'transform',
                types: 'Planeswalker',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Omni-Changeling',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: 'Pestered Wellguard',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'Rime Chill',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: 'Rimefire Torque',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: 'Rimekin Recluse',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Run Away Together',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: 'Shinestriker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Silvergill Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Silvergill Peddler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: 'Spell Snare',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'Stratosoarer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 73,
                name: 'Summit Sentinel',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 74,
                name: 'Sunderflock',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 75,
                name: 'Swat Away',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 76,
                name: 'Sygg, Wanderwine Wisdom // Sygg, Wanderbrine Shield',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 77,
                name: 'Tanufel Rimespeaker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 78,
                name: 'Temporal Cleansing',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 79,
                name: 'Thirst for Identity',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 80,
                name: 'Unexpected Assistance',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 81,
                name: 'Unwelcome Sprite',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 82,
                name: 'Wanderwine Distracter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 83,
                name: 'Wanderwine Farewell',
                rarity: 'U',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 84,
                name: 'Wild Unraveling',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 85,
                name: "Auntie's Sentence",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 86,
                name: 'Barbed Bloodletter',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B',
            },
            {
                cardNumber: 87,
                name: 'Bile-Vial Boggart',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 88,
                name: 'Bitterbloom Bearer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 89,
                name: 'Blight Rot',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 90,
                name: 'Blighted Blackthorn',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: 'Bloodline Bidding',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: 'Boggart Mischief',
                rarity: 'U',
                layout: 'normal',
                types: 'Kindred,Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Boggart Prankster',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: "Bogslither's Embrace",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Champion of the Weird',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Creakwood Safewright',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: 'Darkness Descends',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'Dawnhand Dissident',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Dawnhand Eulogist',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Dose of Dawnglow',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Dream Seizer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Gloom Ripper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Gnarlbark Elm',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: 'Graveshifter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Grub, Storied Matriarch // Grub, Notorious Auntie',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'Gutsplitter Gang',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 107,
                name: 'Heirloom Auntie',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 108,
                name: 'Iron-Shield Elf',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 109,
                name: 'Moonglove Extractor',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 110,
                name: 'Moonshadow',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 111,
                name: 'Mornsong Aria',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 112,
                name: 'Mudbutton Cursetosser',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 113,
                name: 'Nameless Inversion',
                rarity: 'U',
                layout: 'normal',
                types: 'Kindred,Instant',
                colors: 'B',
            },
            {
                cardNumber: 114,
                name: 'Nightmare Sower',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 115,
                name: 'Perfect Intimidation',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 116,
                name: 'Requiting Hex',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 117,
                name: 'Retched Wretch',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 118,
                name: 'Scarblade Scout',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 119,
                name: "Scarblade's Malice",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 120,
                name: 'Shimmercreep',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 121,
                name: 'Taster of Wares',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 122,
                name: 'Twilight Diviner',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 123,
                name: 'Unbury',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 124,
                name: 'Ashling, Rekindled // Ashling, Rimebound',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 125,
                name: 'Boldwyr Aggressor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 126,
                name: 'Boneclub Berserker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 127,
                name: 'Boulder Dash',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 128,
                name: 'Brambleback Brute',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 129,
                name: 'Burning Curiosity',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 130,
                name: 'Champion of the Path',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 131,
                name: 'Cinder Strike',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 132,
                name: 'Collective Inferno',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 133,
                name: 'Elder Auntie',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 134,
                name: 'End-Blaze Epiphany',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 135,
                name: 'Enraged Flamecaster',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 136,
                name: 'Explosive Prodigy',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 137,
                name: 'Feed the Flames',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 138,
                name: 'Flame-Chain Mauler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 139,
                name: 'Flamebraider',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 140,
                name: 'Flamekin Gildweaver',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 141,
                name: 'Giantfall',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 142,
                name: 'Goatnap',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 143,
                name: 'Goliath Daydreamer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 144,
                name: 'Gristle Glutton',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 145,
                name: 'Hexing Squelcher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 146,
                name: 'Impolite Entrance',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 147,
                name: 'Kindle the Inner Flame',
                rarity: 'U',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 148,
                name: 'Kulrath Zealot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 149,
                name: 'Lasting Tarfire',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 150,
                name: 'Lavaleaper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 151,
                name: 'Meek Attack',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 152,
                name: 'Reckless Ransacking',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 153,
                name: 'Scuzzback Scrounger',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 154,
                name: 'Sear',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 155,
                name: 'Sizzling Changeling',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 156,
                name: 'Soul Immolation',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 157,
                name: 'Soulbright Seeker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 158,
                name: 'Sourbread Auntie',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 159,
                name: 'Spinerock Tyrant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 160,
                name: 'Squawkroaster',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 161,
                name: 'Sting-Slinger',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 162,
                name: 'Tweeze',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 163,
                name: 'Warren Torchmaster',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 164,
                name: 'Assert Perfection',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 165,
                name: 'Aurora Awakener',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 166,
                name: 'Bloom Tender',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 167,
                name: 'Blossoming Defense',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 168,
                name: 'Bristlebane Battler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 169,
                name: 'Bristlebane Outrider',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 170,
                name: 'Celestial Reunion',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 171,
                name: 'Champions of the Perfect',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 172,
                name: 'Chomping Changeling',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 173,
                name: 'Crossroads Watcher',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 174,
                name: "Dawn's Light Archer",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 175,
                name: 'Dundoolin Weaver',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 176,
                name: 'Formidable Speaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 177,
                name: "Gilt-Leaf's Embrace",
                rarity: 'C',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 178,
                name: 'Great Forest Druid',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 179,
                name: 'Luminollusk',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 180,
                name: 'Lys Alana Dignitary',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 181,
                name: 'Lys Alana Informant',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 182,
                name: 'Midnight Tilling',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 183,
                name: 'Mistmeadow Council',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 184,
                name: 'Moon-Vigil Adherents',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 185,
                name: "Morcant's Eyes",
                rarity: 'U',
                layout: 'normal',
                types: 'Kindred,Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: 'Mutable Explorer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Pitiless Fists',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Prismabasher',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Prismatic Undercurrents',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: 'Pummeler for Hire',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Safewright Cavalry',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 192,
                name: 'Sapling Nursery',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 193,
                name: 'Selfless Safewright',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 194,
                name: 'Shimmerwilds Growth',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 195,
                name: 'Spry and Mighty',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 196,
                name: 'Surly Farrier',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 197,
                name: 'Tend the Sprigs',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 198,
                name: 'Thoughtweft Charge',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 199,
                name: 'Trystan, Callous Cultivator // Trystan, Penitent Culler',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 200,
                name: 'Unforgiving Aim',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 201,
                name: 'Vinebred Brawler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 202,
                name: 'Virulent Emissary',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 203,
                name: 'Wildvine Pummeler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 204,
                name: 'Abigale, Eloquent First-Year',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 205,
                name: "Ashling's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 206,
                name: 'Boggart Cursecrafter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 207,
                name: 'Bre of Clan Stoutarm',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 208,
                name: "Brigid's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'G,W',
            },
            {
                cardNumber: 209,
                name: 'Catharsis',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 210,
                name: 'Chaos Spewer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 211,
                name: 'Chitinous Graspling',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 212,
                name: 'Deceit',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 213,
                name: 'Deepchannel Duelist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 214,
                name: 'Deepway Navigator',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 215,
                name: 'Doran, Besieged by Time',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,W',
            },
            {
                cardNumber: 216,
                name: 'Dream Harvest',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,U',
            },
            {
                cardNumber: 217,
                name: 'Eclipsed Boggart',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 218,
                name: 'Eclipsed Elf',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 219,
                name: 'Eclipsed Flamekin',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 220,
                name: 'Eclipsed Kithkin',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 221,
                name: 'Eclipsed Merrow',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 222,
                name: 'Emptiness',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 223,
                name: 'Feisty Spikeling',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 224,
                name: 'Figure of Fable',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 225,
                name: 'Flaring Cinder',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 226,
                name: 'Gangly Stompling',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 227,
                name: 'Glister Bairn',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 228,
                name: "Grub's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 229,
                name: 'High Perfect Morcant',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 230,
                name: 'Hovel Hurler',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 231,
                name: 'Kirol, Attentive First-Year',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 232,
                name: 'Lluwen, Imperfect Naturalist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 233,
                name: 'Maralen, Fae Ascendant',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U',
            },
            {
                cardNumber: 234,
                name: 'Merrow Skyswimmer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 235,
                name: 'Mischievous Sneakling',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 236,
                name: "Morcant's Loyalist",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 237,
                name: 'Noggle Robber',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 238,
                name: 'Prideful Feastling',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 239,
                name: 'Raiding Schemes',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G,R',
            },
            {
                cardNumber: 240,
                name: 'Reaping Willow',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 241,
                name: 'Sanar, Innovative First-Year',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 242,
                name: 'Shadow Urchin',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 243,
                name: 'Stoic Grove-Guide',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 244,
                name: "Sygg's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'U,W',
            },
            {
                cardNumber: 245,
                name: 'Tam, Mindful First-Year',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 246,
                name: 'Thoughtweft Lieutenant',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 247,
                name: "Trystan's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 248,
                name: 'Twinflame Travelers',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 249,
                name: 'Vibrance',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 250,
                name: 'Voracious Tome-Skimmer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 251,
                name: 'Wary Farmer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 252,
                name: 'Wistfulness',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 253,
                name: 'Chronicle of Victory',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 254,
                name: 'Dawn-Blessed Pennant',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 255,
                name: 'Firdoch Core',
                rarity: 'C',
                layout: 'normal',
                types: 'Kindred,Artifact',
                colors: '',
            },
            {
                cardNumber: 256,
                name: 'Foraging Wickermaw',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 257,
                name: 'Gathering Stone',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 258,
                name: 'Mirrormind Crown',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 259,
                name: "Puca's Eye",
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Springleaf Drum',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'Stalactite Dagger',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'Blood Crypt',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 263,
                name: 'Eclipsed Realms',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 264,
                name: 'Evolving Wilds',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Hallowed Fountain',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 266,
                name: 'Overgrown Tomb',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Steam Vents',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Temple Garden',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 279,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 280,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 281,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 283,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 284,
                name: 'Ajani, Outland Chaperone',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'W',
            },
            {
                cardNumber: 285,
                name: "Brigid, Clachan's Heart // Brigid, Doun's Mind",
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 286,
                name: 'Eirdu, Carrier of Dawn // Isilu, Carrier of Twilight',
                rarity: 'M',
                layout: 'transform',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 287,
                name: 'Oko, Lorwyn Liege // Oko, Shadowmoor Scion',
                rarity: 'M',
                layout: 'transform',
                types: 'Planeswalker',
                colors: 'U',
            },
            {
                cardNumber: 288,
                name: 'Sygg, Wanderwine Wisdom // Sygg, Wanderbrine Shield',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 289,
                name: 'Grub, Storied Matriarch // Grub, Notorious Auntie',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 290,
                name: 'Ashling, Rekindled // Ashling, Rimebound',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 291,
                name: 'Trystan, Callous Cultivator // Trystan, Penitent Culler',
                rarity: 'R',
                layout: 'transform',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 292,
                name: 'Catharsis',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 293,
                name: 'Deceit',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,U',
            },
            {
                cardNumber: 294,
                name: 'Emptiness',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 295,
                name: 'Vibrance',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,R',
            },
            {
                cardNumber: 296,
                name: 'Wistfulness',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 297,
                name: 'Adept Watershaper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 298,
                name: 'Curious Colossus',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 299,
                name: 'Kinbinding',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 300,
                name: 'Kinscaer Sentry',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 301,
                name: "Morningtide's Light",
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 302,
                name: 'Slumbering Walker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 303,
                name: 'Disruptor of Currents',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 304,
                name: 'Flitterwing Nuisance',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 305,
                name: 'Glen Elendra Guardian',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 306,
                name: "Glen Elendra's Answer",
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 307,
                name: 'Loch Mare',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 308,
                name: 'Mirrorform',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 309,
                name: 'Sunderflock',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 310,
                name: 'Bitterbloom Bearer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 311,
                name: 'Dawnhand Dissident',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 312,
                name: 'Gloom Ripper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 313,
                name: 'Moonshadow',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 314,
                name: 'Taster of Wares',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 315,
                name: 'Twilight Diviner',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 316,
                name: 'Goliath Daydreamer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 317,
                name: 'Hexing Squelcher',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 318,
                name: 'Lavaleaper',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 319,
                name: 'Meek Attack',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 320,
                name: 'Scuzzback Scrounger',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 321,
                name: 'Soul Immolation',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 322,
                name: 'Spinerock Tyrant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 323,
                name: 'Aurora Awakener',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 324,
                name: 'Bloom Tender',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 325,
                name: 'Bristlebane Battler',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 326,
                name: 'Celestial Reunion',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 327,
                name: 'Mutable Explorer',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 328,
                name: 'Sapling Nursery',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 329,
                name: 'Spry and Mighty',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 330,
                name: "Ashling's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 331,
                name: 'Boggart Cursecrafter',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 332,
                name: "Brigid's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'G,W',
            },
            {
                cardNumber: 333,
                name: 'Deepchannel Duelist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 334,
                name: 'Doran, Besieged by Time',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,W',
            },
            {
                cardNumber: 335,
                name: 'Eclipsed Boggart',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 336,
                name: 'Eclipsed Elf',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 337,
                name: 'Eclipsed Flamekin',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 338,
                name: 'Eclipsed Kithkin',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 339,
                name: 'Eclipsed Merrow',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 340,
                name: "Grub's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'B,R',
            },
            {
                cardNumber: 341,
                name: "Morcant's Loyalist",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 342,
                name: "Sygg's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'U,W',
            },
            {
                cardNumber: 343,
                name: 'Thoughtweft Lieutenant',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 344,
                name: "Trystan's Command",
                rarity: 'R',
                layout: 'normal',
                types: 'Kindred,Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 345,
                name: 'Twinflame Travelers',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 346,
                name: 'Chronicle of Victory',
                rarity: 'M',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 347,
                name: 'Hallowed Fountain // Hallowed Fountain',
                rarity: 'R',
                layout: 'reversible_card',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 348,
                name: 'Steam Vents // Steam Vents',
                rarity: 'R',
                layout: 'reversible_card',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 349,
                name: 'Blood Crypt // Blood Crypt',
                rarity: 'R',
                layout: 'reversible_card',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 350,
                name: 'Overgrown Tomb // Overgrown Tomb',
                rarity: 'R',
                layout: 'reversible_card',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 351,
                name: 'Temple Garden // Temple Garden',
                rarity: 'R',
                layout: 'reversible_card',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 352,
                name: 'Bitterbloom Bearer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 353,
                name: 'Champion of the Clachan',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 354,
                name: 'Rhys, the Evermore',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 355,
                name: 'Winnowing',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 356,
                name: 'Champions of the Shoal',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 357,
                name: 'Harmonized Crescendo',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 358,
                name: 'Rimefire Torque',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'U',
            },
            {
                cardNumber: 359,
                name: 'Bloodline Bidding',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 360,
                name: 'Champion of the Weird',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 361,
                name: 'Mornsong Aria',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'B',
            },
            {
                cardNumber: 362,
                name: 'Champion of the Path',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 363,
                name: 'Collective Inferno',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 364,
                name: 'End-Blaze Epiphany',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 365,
                name: 'Champions of the Perfect',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 366,
                name: 'Formidable Speaker',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 367,
                name: 'Selfless Safewright',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 368,
                name: 'Abigale, Eloquent First-Year',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 369,
                name: 'Bre of Clan Stoutarm',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 370,
                name: 'Deepway Navigator',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U,W',
            },
            {
                cardNumber: 371,
                name: 'Dream Harvest',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,U',
            },
            {
                cardNumber: 372,
                name: 'Figure of Fable',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,W',
            },
            {
                cardNumber: 373,
                name: 'High Perfect Morcant',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 374,
                name: 'Kirol, Attentive First-Year',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 375,
                name: 'Lluwen, Imperfect Naturalist',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 376,
                name: 'Maralen, Fae Ascendant',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G,U',
            },
            {
                cardNumber: 377,
                name: 'Raiding Schemes',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G,R',
            },
            {
                cardNumber: 378,
                name: 'Sanar, Innovative First-Year',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 379,
                name: 'Shadow Urchin',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,R',
            },
            {
                cardNumber: 380,
                name: 'Tam, Mindful First-Year',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 381,
                name: 'Mirrormind Crown',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 382,
                name: 'Winnowing',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 383,
                name: 'Glen Elendra Guardian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 384,
                name: 'Harmonized Crescendo',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 385,
                name: 'Bloodline Bidding',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 386,
                name: 'Moonshadow',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 387,
                name: 'Collective Inferno',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 388,
                name: 'Meek Attack',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 389,
                name: 'Spinerock Tyrant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 390,
                name: 'Bloom Tender',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 391,
                name: 'Selfless Safewright',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 392,
                name: 'Winnowing',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 393,
                name: 'Glen Elendra Guardian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 394,
                name: 'Harmonized Crescendo',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 395,
                name: 'Bloodline Bidding',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 396,
                name: 'Moonshadow',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 397,
                name: 'Collective Inferno',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 398,
                name: 'Meek Attack',
                rarity: 'M',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 399,
                name: 'Spinerock Tyrant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 400,
                name: 'Bloom Tender',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 401,
                name: 'Selfless Safewright',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 402,
                name: 'Personify',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 403,
                name: 'Silvergill Mentor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 404,
                name: 'Iron-Shield Elf',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 405,
                name: 'Sear',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 406,
                name: 'Virulent Emissary',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 407,
                name: 'Kinbinding',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 408,
                name: 'Harmonized Crescendo',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'Lorwyn Eclipsed',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
