import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addSos1776021697230 implements MigrationInterface {
    shortName = 'SOS';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: 'The Dawning Archaic',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 2,
                name: 'Rancorous Archaic',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 3,
                name: 'Sundering Archaic',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 4,
                name: 'Together as One',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: '',
            },
            {
                cardNumber: 5,
                name: 'Transcendent Archaic',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 6,
                name: "Ajani's Response",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Antiquities on the Loose',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Ascendant Dustspeaker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Daydream',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Dig Site Inventory',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Eager Glyphmage',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Elite Interceptor // Rejoinder',
                rarity: 'C',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Emeritus of Truce // Swords to Plowshares',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 14,
                name: 'Ennis, Debate Moderator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 15,
                name: 'Erode',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 16,
                name: 'Graduation Day',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 17,
                name: 'Group Project',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 18,
                name: 'Harsh Annotation',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 19,
                name: "Honorbound Page // Forum's Favor",
                rarity: 'C',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 20,
                name: 'Informed Inkwright',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 21,
                name: 'Inkshape Demonstrator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 22,
                name: 'Interjection',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 23,
                name: 'Joined Researchers // Secret Rendezvous',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 24,
                name: 'Owlin Historian',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 25,
                name: 'Practiced Offense',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 26,
                name: 'Primary Research',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'W',
            },
            {
                cardNumber: 27,
                name: 'Quill-Blade Laureate // Twofold Intent',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 28,
                name: 'Rapier Wit',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 29,
                name: 'Rehearsed Debater',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 30,
                name: 'Restoration Seminar',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 31,
                name: 'Shattered Acolyte',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 32,
                name: 'Soaring Stoneglider',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 33,
                name: 'Spiritcall Enthusiast // Scrollboost',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 34,
                name: 'Stand Up for Yourself',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 35,
                name: 'Stirring Hopesinger',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 36,
                name: 'Stone Docent',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 37,
                name: 'Summoned Dromedary',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 38,
                name: 'Banishing Betrayal',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 39,
                name: 'Brush Off',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 40,
                name: 'Campus Composer // Aqueous Aria',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 41,
                name: 'Chase Inspiration',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 42,
                name: 'Deluge Virtuoso',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 43,
                name: 'Divergent Equation',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 44,
                name: 'Echocasting Symposium',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 45,
                name: 'Emeritus of Ideation // Ancestral Recall',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 46,
                name: 'Encouraging Aviator // Jump',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 47,
                name: 'Essence Scatter',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 48,
                name: 'Exhibition Tidecaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 49,
                name: 'Flow State',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 50,
                name: 'Fractal Anomaly',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 51,
                name: 'Fractalize',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 52,
                name: 'Harmonized Trio // Brainstorm',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 53,
                name: 'Homesickness',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 54,
                name: 'Hydro-Channeler',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 55,
                name: "Jadzi, Steward of Fate // Oracle's Gift",
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 56,
                name: 'Landscape Painter // Vibrant Idea',
                rarity: 'C',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 57,
                name: 'Mana Sculpt',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 58,
                name: 'Mathemagics',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 59,
                name: 'Matterbending Mage',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 60,
                name: 'Muse Seeker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 61,
                name: "Muse's Encouragement",
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 62,
                name: 'Orysa, Tide Choreographer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 63,
                name: 'Pensive Professor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 64,
                name: 'Procrastinate',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 65,
                name: 'Quick Study',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 66,
                name: 'Run Behind',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 67,
                name: 'Skycoach Conductor // All Aboard',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 68,
                name: 'Spellbook Seeker // Careful Study',
                rarity: 'C',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 69,
                name: 'Tester of the Tangential',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 70,
                name: 'Textbook Tabulator',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 71,
                name: 'Wisdom of Ages',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 72,
                name: 'Adventurous Eater // Have a Bite',
                rarity: 'C',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 73,
                name: 'Arcane Omens',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 74,
                name: 'Arnyn, Deathbloom Botanist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 75,
                name: 'Burrog Banemaker',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 76,
                name: 'Cheerful Osteomancer // Raise Dead',
                rarity: 'C',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 77,
                name: 'Cost of Brilliance',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 78,
                name: 'Decorum Dissertation',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 79,
                name: 'Dissection Practice',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 80,
                name: 'Emeritus of Woe // Demonic Tutor',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 81,
                name: 'End of the Hunt',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 82,
                name: 'Eternal Student',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 83,
                name: 'Foolish Fate',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 84,
                name: 'Forum Necroscribe',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 85,
                name: 'Grave Researcher // Reanimate',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 86,
                name: 'Last Gasp',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 87,
                name: 'Lecturing Scornmage',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 88,
                name: 'Leech Collector // Bloodletting',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 89,
                name: 'Masterful Flourish',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 90,
                name: 'Melancholic Poet',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: "Moseo, Vein's New Dean",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: "Poisoner's Apprentice",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Postmortem Professor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'Pox Plague',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Pull from the Grave',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Rabid Attack',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: 'Ral Zarek, Guest Lecturer',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'Scathing Shadelock // Venomous Words',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Scheming Silvertongue // Sign in Blood',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Send in the Pest',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Sneering Shadewriter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Tragedy Feaster',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 103,
                name: 'Ulna Alley Shopkeep',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 104,
                name: 'Wander Off',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 105,
                name: 'Withering Curse',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 106,
                name: 'Ancestral Anger',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 107,
                name: "Archaic's Agony",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 108,
                name: 'Artistic Process',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 109,
                name: 'Blazing Firesinger // Seething Song',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 110,
                name: 'Charging Strifeknight',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 111,
                name: 'Choreographed Sparks',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 112,
                name: 'Duel Tactics',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 113,
                name: 'Emeritus of Conflict // Lightning Bolt',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 114,
                name: 'Expressive Firedancer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 115,
                name: 'Flashback',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 116,
                name: 'Garrison Excavator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 117,
                name: 'Goblin Glasswright // Craft with Pride',
                rarity: 'C',
                layout: 'prepare',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 118,
                name: 'Heated Argument',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 119,
                name: 'Impractical Joke',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 120,
                name: 'Improvisation Capstone',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 121,
                name: 'Living History',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'R',
            },
            {
                cardNumber: 122,
                name: 'Maelstrom Artisan // Rocket Volley',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 123,
                name: 'Magmablood Archaic',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 124,
                name: 'Mica, Reader of Ruins',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 125,
                name: 'Molten-Core Maestro',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 126,
                name: 'Pigment Wrangler // Striking Palette',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 127,
                name: 'Rearing Embermare',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 128,
                name: 'Rubble Rouser',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 129,
                name: 'Seize the Spoils',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 130,
                name: 'Steal the Show',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 131,
                name: 'Strife Scholar // Awaken the Ages',
                rarity: 'C',
                layout: 'prepare',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 132,
                name: 'Tablet of Discovery',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R',
            },
            {
                cardNumber: 133,
                name: 'Tackle Artist',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 134,
                name: 'Thunderdrum Soloist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 135,
                name: 'Tome Blast',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 136,
                name: 'Unsubtle Mockery',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 137,
                name: 'Zealous Lorecaster',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 138,
                name: 'Aberrant Manawurm',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 139,
                name: 'Additive Evolution',
                rarity: 'U',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 140,
                name: 'Ambitious Augmenter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 141,
                name: 'Burrog Barrage',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 142,
                name: 'Chelonian Tackle',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 143,
                name: 'Comforting Counsel',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 144,
                name: 'Efflorescence',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 145,
                name: 'Emeritus of Abundance // Regrowth',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 146,
                name: 'Emil, Vastlands Roamer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 147,
                name: 'Environmental Scientist',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 148,
                name: 'Follow the Lumarets',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 149,
                name: 'Germination Practicum',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 150,
                name: 'Glorious Decay',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 151,
                name: 'Hungry Graffalon',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 152,
                name: 'Infirmary Healer // Stream of Life',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 153,
                name: "Lumaret's Favor",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 154,
                name: 'Mindful Biomancer',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 155,
                name: 'Noxious Newt',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 156,
                name: "Oracle's Restoration",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 157,
                name: 'Pestbrood Sloth',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 158,
                name: 'Planar Engineering',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 159,
                name: "Shopkeeper's Bane",
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 160,
                name: 'Slumbering Trudge',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 161,
                name: 'Snarl Song',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 162,
                name: 'Studious First-Year // Rampant Growth',
                rarity: 'C',
                layout: 'prepare',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 163,
                name: 'Tenured Concocter',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 164,
                name: 'Thornfist Striker',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 165,
                name: 'Topiary Lecturer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 166,
                name: 'Vastlands Scavenger // Bind to Life',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 167,
                name: 'Wild Hypothesis',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 168,
                name: 'Wildgrowth Archaic',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 169,
                name: "Zimone's Experiment",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 170,
                name: 'Abigale, Poet Laureate // Heroic Stanza',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W,B',
            },
            {
                cardNumber: 171,
                name: 'Abstract Paintmage',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 172,
                name: 'Applied Geometry',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 173,
                name: 'Ark of Hunger',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R,W',
            },
            {
                cardNumber: 174,
                name: 'Aziza, Mage Tower Captain',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 175,
                name: 'Berta, Wise Extrapolator',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 176,
                name: 'Blech, Loafing Pest',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 177,
                name: 'Bogwater Lumaret',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 178,
                name: 'Borrowed Knowledge',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,W',
            },
            {
                cardNumber: 179,
                name: 'Cauldron of Essence',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B,G',
            },
            {
                cardNumber: 180,
                name: 'Colorstorm Stallion',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 181,
                name: 'Colossus of the Blood Age',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 182,
                name: "Conciliator's Duelist",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 183,
                name: 'Cuboid Colony',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 184,
                name: "Dina's Guidance",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,G',
            },
            {
                cardNumber: 185,
                name: 'Elemental Mascot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 186,
                name: 'Embrace the Paradox',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'G,U',
            },
            {
                cardNumber: 187,
                name: 'Essenceknit Scholar',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 188,
                name: "Fix What's Broken",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 189,
                name: 'Fractal Mascot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 190,
                name: 'Fractal Tender',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 191,
                name: "Geometer's Arthropod",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 192,
                name: 'Grapple with Death',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 193,
                name: 'Growth Curve',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 194,
                name: 'Hardened Academic',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 195,
                name: 'Imperious Inkmage',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 196,
                name: 'Inkling Mascot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 197,
                name: "Killian's Confidence",
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 198,
                name: 'Kirol, History Buff // Pack a Punch',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W,R',
            },
            {
                cardNumber: 199,
                name: 'Lluwen, Exchange Student // Pest Friend',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 200,
                name: 'Lorehold Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,W',
            },
            {
                cardNumber: 201,
                name: 'Lorehold, the Historian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 202,
                name: 'Mind into Matter',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 203,
                name: 'Mind Roots',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 204,
                name: 'Molten Note',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,W',
            },
            {
                cardNumber: 205,
                name: 'Moment of Reckoning',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 206,
                name: 'Nita, Forum Conciliator',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 207,
                name: 'Old-Growth Educator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 208,
                name: 'Paradox Surveyor',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 209,
                name: 'Pest Mascot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 210,
                name: 'Practiced Scrollsmith',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 211,
                name: 'Prismari Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 212,
                name: 'Prismari, the Inspiration',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 213,
                name: "Proctor's Gaze",
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G,U',
            },
            {
                cardNumber: 214,
                name: 'Professor Dellian Fel',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B,G',
            },
            {
                cardNumber: 215,
                name: 'Pterafractyl',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 216,
                name: 'Pursue the Past',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,W',
            },
            {
                cardNumber: 217,
                name: 'Quandrix Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G,U',
            },
            {
                cardNumber: 218,
                name: 'Quandrix, the Proof',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 219,
                name: 'Rapturous Moment',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,U',
            },
            {
                cardNumber: 220,
                name: 'Render Speechless',
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 221,
                name: 'Resonating Lute',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R,U',
            },
            {
                cardNumber: 222,
                name: 'Root Manipulation',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 223,
                name: 'Sanar, Unfinished Genius // Wild Idea',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U,R',
            },
            {
                cardNumber: 224,
                name: 'Scolding Administrator',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 225,
                name: 'Silverquill Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,W',
            },
            {
                cardNumber: 226,
                name: 'Silverquill, the Disputant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 227,
                name: 'Snooping Page',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 228,
                name: 'Social Snub',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 229,
                name: 'Spectacular Skywhale',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 230,
                name: 'Spirit Mascot',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 231,
                name: 'Splatter Technique',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,U',
            },
            {
                cardNumber: 232,
                name: 'Stadium Tidalmage',
                rarity: 'C',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 233,
                name: 'Startled Relic Sloth',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 234,
                name: 'Stirring Honormancer',
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 235,
                name: 'Stress Dream',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 236,
                name: 'Suspend Aggression',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,W',
            },
            {
                cardNumber: 237,
                name: 'Tam, Observant Sequencer // Deep Sight',
                rarity: 'U',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U,G',
            },
            {
                cardNumber: 238,
                name: "Teacher's Pest",
                rarity: 'U',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 239,
                name: 'Traumatic Critique',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 240,
                name: 'Vibrant Outburst',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 241,
                name: 'Vicious Rivalry',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 242,
                name: "Visionary's Dance",
                rarity: 'C',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,U',
            },
            {
                cardNumber: 243,
                name: 'Wilt in the Heat',
                rarity: 'C',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,W',
            },
            {
                cardNumber: 244,
                name: 'Witherbloom Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,G',
            },
            {
                cardNumber: 245,
                name: 'Witherbloom, the Balancer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 246,
                name: 'Zaffai and the Tempests',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 247,
                name: 'Biblioplex Tomekeeper',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 248,
                name: 'Diary of Dreams',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 249,
                name: 'Mage Tower Referee',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 250,
                name: 'Page, Loose Leaf',
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact,Creature',
                colors: '',
            },
            {
                cardNumber: 251,
                name: "Potioner's Trove",
                rarity: 'C',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 252,
                name: 'Strixhaven Skycoach',
                rarity: 'U',
                layout: 'normal',
                types: 'Artifact',
                colors: '',
            },
            {
                cardNumber: 253,
                name: 'Deathcap Glade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 254,
                name: 'Dreamroot Cascade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 255,
                name: 'Fields of Strife',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 256,
                name: 'Forum of Amity',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 257,
                name: 'Great Hall of the Biblioplex',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 258,
                name: 'Paradox Gardens',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 259,
                name: 'Petrified Hamlet',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 260,
                name: 'Shattered Sanctum',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 261,
                name: 'Skycoach Waypoint',
                rarity: 'U',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 262,
                name: 'Spectacle Summit',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 263,
                name: 'Stormcarved Coast',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 264,
                name: 'Sundown Pass',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 265,
                name: 'Terramorphic Expanse',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 266,
                name: "Titan's Grave",
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 267,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 268,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 269,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 270,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 271,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 272,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 273,
                name: 'Plains',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 274,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 275,
                name: 'Island',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 276,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 277,
                name: 'Swamp',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 278,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 279,
                name: 'Mountain',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 280,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 281,
                name: 'Forest',
                rarity: 'C',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 282,
                name: 'Ral Zarek, Guest Lecturer',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B',
            },
            {
                cardNumber: 283,
                name: 'Professor Dellian Fel',
                rarity: 'M',
                layout: 'normal',
                types: 'Planeswalker',
                colors: 'B,G',
            },
            {
                cardNumber: 284,
                name: 'Lorehold, the Historian',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 285,
                name: 'Prismari, the Inspiration',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 286,
                name: 'Quandrix, the Proof',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 287,
                name: 'Silverquill, the Disputant',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 288,
                name: 'Witherbloom, the Balancer',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 289,
                name: 'The Dawning Archaic',
                rarity: 'M',
                layout: 'normal',
                types: 'Creature',
                colors: '',
            },
            {
                cardNumber: 290,
                name: 'Restoration Seminar',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 291,
                name: 'Echocasting Symposium',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 292,
                name: 'Decorum Dissertation',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 293,
                name: 'Tragedy Feaster',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 294,
                name: 'Improvisation Capstone',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 295,
                name: 'Magmablood Archaic',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 296,
                name: 'Germination Practicum',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 297,
                name: 'Wildgrowth Archaic',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 298,
                name: 'Blech, Loafing Pest',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,G',
            },
            {
                cardNumber: 299,
                name: 'Colorstorm Stallion',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 300,
                name: "Geometer's Arthropod",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 301,
                name: 'Deathcap Glade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 302,
                name: 'Dreamroot Cascade',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 303,
                name: 'Shattered Sanctum',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 304,
                name: 'Stormcarved Coast',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 305,
                name: 'Sundown Pass',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 306,
                name: 'Emeritus of Ideation // Ancestral Recall',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 307,
                name: 'Together as One',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: '',
            },
            {
                cardNumber: 308,
                name: 'Antiquities on the Loose',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 309,
                name: 'Emeritus of Truce // Swords to Plowshares',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 310,
                name: 'Erode',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 311,
                name: 'Informed Inkwright',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 312,
                name: 'Joined Researchers // Secret Rendezvous',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 313,
                name: 'Practiced Offense',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 314,
                name: 'Stirring Hopesinger',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'W',
            },
            {
                cardNumber: 315,
                name: 'Emeritus of Ideation // Ancestral Recall',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 316,
                name: 'Exhibition Tidecaller',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 317,
                name: 'Harmonized Trio // Brainstorm',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 318,
                name: "Jadzi, Steward of Fate // Oracle's Gift",
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 319,
                name: 'Mana Sculpt',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 320,
                name: 'Mathemagics',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 321,
                name: 'Pensive Professor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 322,
                name: 'Skycoach Conductor // All Aboard',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'U',
            },
            {
                cardNumber: 323,
                name: 'Wisdom of Ages',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 324,
                name: 'Emeritus of Woe // Demonic Tutor',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 325,
                name: 'Grave Researcher // Reanimate',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 326,
                name: "Moseo, Vein's New Dean",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 327,
                name: 'Postmortem Professor',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 328,
                name: 'Pox Plague',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 329,
                name: 'Scheming Silvertongue // Sign in Blood',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'B',
            },
            {
                cardNumber: 330,
                name: 'Withering Curse',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 331,
                name: 'Choreographed Sparks',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 332,
                name: 'Emeritus of Conflict // Lightning Bolt',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 333,
                name: 'Flashback',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 334,
                name: 'Maelstrom Artisan // Rocket Volley',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 335,
                name: 'Molten-Core Maestro',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R',
            },
            {
                cardNumber: 336,
                name: 'Steal the Show',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 337,
                name: 'Ambitious Augmenter',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 338,
                name: 'Comforting Counsel',
                rarity: 'R',
                layout: 'normal',
                types: 'Enchantment',
                colors: 'G',
            },
            {
                cardNumber: 339,
                name: 'Emeritus of Abundance // Regrowth',
                rarity: 'M',
                layout: 'prepare',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 340,
                name: 'Planar Engineering',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 341,
                name: 'Slumbering Trudge',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 342,
                name: 'Vastlands Scavenger // Bind to Life',
                rarity: 'R',
                layout: 'prepare',
                types: 'Creature',
                colors: 'G',
            },
            {
                cardNumber: 343,
                name: 'Applied Geometry',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 344,
                name: 'Ark of Hunger',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R,W',
            },
            {
                cardNumber: 345,
                name: 'Aziza, Mage Tower Captain',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 346,
                name: 'Berta, Wise Extrapolator',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'G,U',
            },
            {
                cardNumber: 347,
                name: 'Cauldron of Essence',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'B,G',
            },
            {
                cardNumber: 348,
                name: "Conciliator's Duelist",
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 349,
                name: "Dina's Guidance",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,G',
            },
            {
                cardNumber: 350,
                name: "Fix What's Broken",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 351,
                name: 'Hardened Academic',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,W',
            },
            {
                cardNumber: 352,
                name: 'Mind into Matter',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 353,
                name: 'Moment of Reckoning',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,W',
            },
            {
                cardNumber: 354,
                name: 'Nita, Forum Conciliator',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'B,W',
            },
            {
                cardNumber: 355,
                name: 'Resonating Lute',
                rarity: 'R',
                layout: 'normal',
                types: 'Artifact',
                colors: 'R,U',
            },
            {
                cardNumber: 356,
                name: 'Splatter Technique',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,U',
            },
            {
                cardNumber: 357,
                name: 'Suspend Aggression',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,W',
            },
            {
                cardNumber: 358,
                name: 'Traumatic Critique',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 359,
                name: 'Vicious Rivalry',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 360,
                name: 'Zaffai and the Tempests',
                rarity: 'R',
                layout: 'normal',
                types: 'Creature',
                colors: 'R,U',
            },
            {
                cardNumber: 361,
                name: 'Great Hall of the Biblioplex',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 362,
                name: 'Petrified Hamlet',
                rarity: 'R',
                layout: 'normal',
                types: 'Land',
                colors: '',
            },
            {
                cardNumber: 363,
                name: 'Lorehold Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,W',
            },
            {
                cardNumber: 364,
                name: 'Prismari Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,U',
            },
            {
                cardNumber: 365,
                name: 'Quandrix Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G,U',
            },
            {
                cardNumber: 366,
                name: 'Silverquill Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,W',
            },
            {
                cardNumber: 367,
                name: 'Witherbloom Charm',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,G',
            },
            {
                cardNumber: 368,
                name: 'Wisdom of Ages',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'Secrets of Strixhaven',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
