import { MigrationInterface, QueryRunner } from 'typeorm';
import { CardSet } from '../card/entity/card-set.entity';
import { CardVariantType } from '../card/entity/card-variant-type.enum';
import { Card } from '../card/entity/card.entity';
import { PossibleCardVariation } from '../card/entity/possible-card-variation.entity';
import { MigrationHelper } from './helper/migration-helper';

export class addSoa1776021815797 implements MigrationInterface {
    shortName = 'SOA';
    public async up(queryRunner: QueryRunner): Promise<void> {
        const cardValues = [
            {
                cardNumber: 1,
                name: "Akroma's Will",
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 2,
                name: "Angel's Grace",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 3,
                name: 'Armageddon',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 4,
                name: 'Duty Beyond Death',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 5,
                name: 'Helping Hand',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 6,
                name: 'Hop to It',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 7,
                name: 'Prismatic Ending',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 8,
                name: 'Repel Calamity',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 9,
                name: 'Reprieve',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 10,
                name: 'Requisition Raid',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 11,
                name: 'Return to the Ranks',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 12,
                name: 'Winds of Abandon',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 13,
                name: 'Brain Freeze',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 14,
                name: 'Cyclonic Rift',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 15,
                name: 'Daze',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 16,
                name: 'Deduce',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 17,
                name: 'Disdainful Stroke',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 18,
                name: 'Flusterstorm',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 19,
                name: 'Force of Will',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 20,
                name: 'Pongify',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 21,
                name: 'Preordain',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 22,
                name: 'Sleight of Hand',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 23,
                name: 'Spell Pierce',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 24,
                name: 'Stock Up',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 25,
                name: 'Ad Nauseam',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 26,
                name: 'Bitter Triumph',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 27,
                name: 'Culling the Weak',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 28,
                name: 'Dismember',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 29,
                name: 'Feed the Swarm',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 30,
                name: 'Living End',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 31,
                name: 'Locust Spray',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 32,
                name: "Sheoldred's Edict",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 33,
                name: 'Smallpox',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 34,
                name: 'Stargaze',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 35,
                name: 'Vampiric Tutor',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 36,
                name: 'Zombify',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 37,
                name: 'Abrade',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 38,
                name: 'Big Score',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 39,
                name: "Brotherhood's End",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 40,
                name: 'Bulk Up',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 41,
                name: 'Burst Lightning',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 42,
                name: 'Crackle with Power',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 43,
                name: 'Empty the Warrens',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 44,
                name: "Jeska's Will",
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 45,
                name: 'Monstrous Rage',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 46,
                name: 'Pyretic Ritual',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 47,
                name: 'Return the Favor',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 48,
                name: 'Subterranean Tremors',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 49,
                name: 'Awaken the Woods',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 50,
                name: 'Berserk',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 51,
                name: 'Crop Rotation',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 52,
                name: 'Giant Growth',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 53,
                name: 'Glimpse of Nature',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 54,
                name: 'Knockout Maneuver',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 55,
                name: 'Pick Your Poison',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 56,
                name: 'Royal Treatment',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 57,
                name: 'Shamanic Revelation',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 58,
                name: 'Shared Roots',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 59,
                name: 'Triumph of the Hordes',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 60,
                name: 'Veil of Summer',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 61,
                name: 'Bring to Light',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 62,
                name: 'Culling Ritual',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 63,
                name: 'Deflecting Palm',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,W',
            },
            {
                cardNumber: 64,
                name: 'Expressive Iteration',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,U',
            },
            {
                cardNumber: 65,
                name: 'Fracture',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,W',
            },
            {
                cardNumber: 66,
                name: "Akroma's Will",
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 67,
                name: "Angel's Grace",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 68,
                name: 'Armageddon',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 69,
                name: 'Duty Beyond Death',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 70,
                name: 'Helping Hand',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 71,
                name: 'Hop to It',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 72,
                name: 'Prismatic Ending',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 73,
                name: 'Repel Calamity',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 74,
                name: 'Reprieve',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 75,
                name: 'Requisition Raid',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 76,
                name: 'Return to the Ranks',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 77,
                name: 'Winds of Abandon',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 78,
                name: 'Brain Freeze',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 79,
                name: 'Cyclonic Rift',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 80,
                name: 'Daze',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 81,
                name: 'Deduce',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 82,
                name: 'Disdainful Stroke',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 83,
                name: 'Flusterstorm',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 84,
                name: 'Force of Will',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 85,
                name: 'Pongify',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 86,
                name: 'Preordain',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 87,
                name: 'Sleight of Hand',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 88,
                name: 'Spell Pierce',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 89,
                name: 'Stock Up',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 90,
                name: 'Ad Nauseam',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 91,
                name: 'Bitter Triumph',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 92,
                name: 'Culling the Weak',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 93,
                name: 'Dismember',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 94,
                name: 'Feed the Swarm',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 95,
                name: 'Living End',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 96,
                name: 'Locust Spray',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 97,
                name: "Sheoldred's Edict",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 98,
                name: 'Smallpox',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 99,
                name: 'Stargaze',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 100,
                name: 'Vampiric Tutor',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 101,
                name: 'Zombify',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 102,
                name: 'Abrade',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 103,
                name: 'Big Score',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 104,
                name: "Brotherhood's End",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 105,
                name: 'Bulk Up',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 106,
                name: 'Burst Lightning',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 107,
                name: 'Crackle with Power',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 108,
                name: 'Empty the Warrens',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 109,
                name: "Jeska's Will",
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 110,
                name: 'Monstrous Rage',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 111,
                name: 'Pyretic Ritual',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 112,
                name: 'Return the Favor',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 113,
                name: 'Subterranean Tremors',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 114,
                name: 'Awaken the Woods',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 115,
                name: 'Berserk',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 116,
                name: 'Crop Rotation',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 117,
                name: 'Giant Growth',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 118,
                name: 'Glimpse of Nature',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 119,
                name: 'Knockout Maneuver',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 120,
                name: 'Pick Your Poison',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 121,
                name: 'Royal Treatment',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 122,
                name: 'Shamanic Revelation',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 123,
                name: 'Shared Roots',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 124,
                name: 'Triumph of the Hordes',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 125,
                name: 'Veil of Summer',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 126,
                name: 'Bring to Light',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 127,
                name: 'Culling Ritual',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 128,
                name: 'Deflecting Palm',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,W',
            },
            {
                cardNumber: 129,
                name: 'Expressive Iteration',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,U',
            },
            {
                cardNumber: 130,
                name: 'Fracture',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,W',
            },
            {
                cardNumber: 131,
                name: "Akroma's Will",
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 132,
                name: "Angel's Grace",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 133,
                name: 'Armageddon',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 134,
                name: 'Duty Beyond Death',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 135,
                name: 'Helping Hand',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 136,
                name: 'Hop to It',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 137,
                name: 'Prismatic Ending',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 138,
                name: 'Repel Calamity',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 139,
                name: 'Reprieve',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'W',
            },
            {
                cardNumber: 140,
                name: 'Requisition Raid',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 141,
                name: 'Return to the Ranks',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 142,
                name: 'Winds of Abandon',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'W',
            },
            {
                cardNumber: 143,
                name: 'Brain Freeze',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 144,
                name: 'Cyclonic Rift',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 145,
                name: 'Daze',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 146,
                name: 'Deduce',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 147,
                name: 'Disdainful Stroke',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 148,
                name: 'Flusterstorm',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 149,
                name: 'Force of Will',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 150,
                name: 'Pongify',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 151,
                name: 'Preordain',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 152,
                name: 'Sleight of Hand',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 153,
                name: 'Spell Pierce',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'U',
            },
            {
                cardNumber: 154,
                name: 'Stock Up',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'U',
            },
            {
                cardNumber: 155,
                name: 'Ad Nauseam',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 156,
                name: 'Bitter Triumph',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 157,
                name: 'Culling the Weak',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 158,
                name: 'Dismember',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 159,
                name: 'Feed the Swarm',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 160,
                name: 'Living End',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 161,
                name: 'Locust Spray',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 162,
                name: "Sheoldred's Edict",
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 163,
                name: 'Smallpox',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 164,
                name: 'Stargaze',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 165,
                name: 'Vampiric Tutor',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'B',
            },
            {
                cardNumber: 166,
                name: 'Zombify',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B',
            },
            {
                cardNumber: 167,
                name: 'Abrade',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 168,
                name: 'Big Score',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 169,
                name: "Brotherhood's End",
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 170,
                name: 'Bulk Up',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 171,
                name: 'Burst Lightning',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 172,
                name: 'Crackle with Power',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 173,
                name: 'Empty the Warrens',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 174,
                name: "Jeska's Will",
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 175,
                name: 'Monstrous Rage',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 176,
                name: 'Pyretic Ritual',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 177,
                name: 'Return the Favor',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'R',
            },
            {
                cardNumber: 178,
                name: 'Subterranean Tremors',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R',
            },
            {
                cardNumber: 179,
                name: 'Awaken the Woods',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 180,
                name: 'Berserk',
                rarity: 'M',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 181,
                name: 'Crop Rotation',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 182,
                name: 'Giant Growth',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 183,
                name: 'Glimpse of Nature',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 184,
                name: 'Knockout Maneuver',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 185,
                name: 'Pick Your Poison',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 186,
                name: 'Royal Treatment',
                rarity: 'U',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 187,
                name: 'Shamanic Revelation',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 188,
                name: 'Shared Roots',
                rarity: 'U',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 189,
                name: 'Triumph of the Hordes',
                rarity: 'M',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G',
            },
            {
                cardNumber: 190,
                name: 'Veil of Summer',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'G',
            },
            {
                cardNumber: 191,
                name: 'Bring to Light',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'G,U',
            },
            {
                cardNumber: 192,
                name: 'Culling Ritual',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'B,G',
            },
            {
                cardNumber: 193,
                name: 'Deflecting Palm',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'R,W',
            },
            {
                cardNumber: 194,
                name: 'Expressive Iteration',
                rarity: 'R',
                layout: 'normal',
                types: 'Sorcery',
                colors: 'R,U',
            },
            {
                cardNumber: 195,
                name: 'Fracture',
                rarity: 'R',
                layout: 'normal',
                types: 'Instant',
                colors: 'B,W',
            },
        ];

        await MigrationHelper.cardSetUp(
            queryRunner,
            'Secrets of Strixhaven Mystical Archive',
            this.shortName,
            cardValues,
            [`id`, `cardNumber`, `name`, `rarity`, `layout`, `cardSet`, `colors`, `types`],
        );

        const cards = await queryRunner.manager
            .createQueryBuilder<Card>('Card', 'c')
            .select('c.id')
            .leftJoin(CardSet, 'cs', 'c.card_set_1 = cs.id')
            .where('cs.short_name = :shortName', { shortName: this.shortName })
            .getMany();

        const insertDefaultPossibleCards: PossibleCardVariation[] = [];
        cards.forEach(card => {
            const defaultPossibleCard = queryRunner.manager
                .getRepository<PossibleCardVariation>(PossibleCardVariation)
                .create();
            defaultPossibleCard.card = card;
            defaultPossibleCard.cardVariantType = CardVariantType.NORMAL;
            defaultPossibleCard.hasNormal = true;
            defaultPossibleCard.hasFoil = true;
            insertDefaultPossibleCards.push(defaultPossibleCard);
        });

        await queryRunner.manager
            .getRepository<PossibleCardVariation>(PossibleCardVariation)
            .insert(insertDefaultPossibleCards);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        const deletablePossibleCardVariations = await queryRunner.manager
            .createQueryBuilder<PossibleCardVariation>(PossibleCardVariation, 'pcv')
            .select(['pcv.id'])
            .innerJoin(Card, 'c', 'pcv.card_1 = c.id')
            .innerJoin(CardSet, 'cs', 'cs.id = c.card_set_1')
            .where(`cs.short_name = '${this.shortName}'`)
            .getMany();

        if (deletablePossibleCardVariations.length > 0) {
            await queryRunner.manager.delete<PossibleCardVariation>(
                PossibleCardVariation,
                deletablePossibleCardVariations,
            );
        }

        await MigrationHelper.cardSetDown(queryRunner, this.shortName);
    }
}
